// Fertility-related RAG entries for CycleMind Luna AI companion
// These entries provide evidence-based information on fertility, infertility evaluation, causes, and treatments

export const fertilityRagEntries = [
  // === Evaluation of Female Infertility RAG Entries (IDs 3306–3315) ===
  { id: 3306, category: 'fertility', keywords: ['when to start infertility evaluation age thresholds'], question: "When should an infertility evaluation be initiated?", response: "Standard timing is after 12 months of regular unprotected intercourse for women under 35 years and after 6 months for women 35 years and older. Earlier or immediate evaluation is appropriate for women ≥40 years, those with irregular cycles, known risk factors (endometriosis, prior PID, pelvic surgery, reproductive tract anomalies), or known/suspected male factor infertility. Both partners should be evaluated concurrently." },
  { id: 3307, category: 'fertility', keywords: ['initial infertility evaluation components history physical'], question: "What are the key components of the initial infertility evaluation?", response: "A focused history (duration of infertility, menstrual pattern, medical/surgical/gynecologic history, sexual history, family history, lifestyle factors) and physical examination (BMI, signs of endocrinopathy, pelvic findings) should be performed on the female partner. Semen analysis, documentation of ovulation, assessment of tubal patency/uterine cavity, and ovarian reserve testing form the core diagnostic workup. Multiple factors may coexist." },
  { id: 3308, category: 'fertility', keywords: ['ovarian reserve testing AMH day 3 FSH estradiol'], question: "How is ovarian reserve assessed in the infertility evaluation?", response: "Common tests include anti-müllerian hormone (AMH, can be drawn any cycle day), day 3 FSH + estradiol, antral follicle count, and the clomiphene citrate challenge test. AMH and antral follicle count are particularly useful for predicting ovarian response to stimulation. No single test perfectly predicts live birth. Markedly abnormal results (e.g., very low AMH or high day 3 FSH) suggest diminished reserve and warrant referral to a reproductive endocrinologist." },
  { id: 3309, category: 'fertility', keywords: ['tubal patency testing HSG HyCoSy laparoscopy'], question: "How is tubal patency evaluated?", response: "Hysterosalpingogram (HSG) or hysterosalpingo-contrast sonography (HyCoSy) are first-line tests to assess tubal patency and the uterine cavity. HyCoSy is often better tolerated. Laparoscopy with chromotubation (plus hysteroscopy) is preferred when endometriosis, pelvic adhesions, or other pelvic pathology is suspected based on history or exam, as it allows diagnosis and potential treatment in one procedure." },
  { id: 3310, category: 'fertility', keywords: ['ovulation assessment progesterone LH kit'], question: "How is ovulatory function assessed?", response: "Women with regular ~28-day cycles and molimina symptoms are usually ovulatory. In others, a mid-luteal progesterone level (>3 ng/mL) or urinary LH ovulation predictor kits can document ovulation. If anovulation is confirmed, further evaluation for causes (e.g., PCOS, thyroid dysfunction, hyperprolactinemia) is indicated." },
  { id: 3311, category: 'fertility', keywords: ['limited utility tests postcoital endometrial biopsy'], question: "Which tests have limited utility in the basic infertility evaluation?", response: "The postcoital test, routine endometrial biopsy for luteal phase dating, basal body temperature charting, routine mycoplasma cultures, and broad antibody testing have limited or no proven value in guiding treatment or improving outcomes for most couples. Karyotyping is reserved for specific indications (e.g., severe male factor, premature ovarian insufficiency, recurrent pregnancy loss)." },
  { id: 3312, category: 'fertility', keywords: ['CycleMind fertility tracking preconception support'], question: "How can CycleMind support users exploring fertility or undergoing evaluation?", response: "CycleMind can help users track cycle length and regularity, ovulation symptoms or LH surge data (if using kits), menstrual symptoms, mood, sleep, and other factors relevant to fertility awareness. It can provide general education on the basic components of an infertility workup and the importance of preconception health optimization. All specific testing decisions, result interpretation, and treatment planning must be handled by qualified clinicians." },
  { id: 3313, category: 'fertility', keywords: ['CycleMind Luna infertility evaluation boundaries'], question: "What boundaries should Luna maintain when discussing infertility evaluation?", response: "Luna must clearly state she is not a reproductive endocrinologist or fertility specialist and cannot order tests, interpret results, diagnose causes of infertility, or recommend specific treatments. Provide general information about standard evaluation components and timing while strongly redirecting users to their obstetrician-gynecologist or a reproductive endocrinologist for personalized assessment and care." },
  { id: 3314, category: 'fertility', keywords: ['preconception counseling infertility risk factors'], question: "What preconception factors should be addressed in patients concerned about fertility?", response: "Key areas include optimizing BMI, reviewing medications, screening for thyroid dysfunction or other endocrinopathies, addressing lifestyle factors (smoking, alcohol, substance use, exercise), offering genetic carrier screening based on ethnicity/family history, and ensuring up-to-date vaccinations and routine health maintenance. Early identification of risk factors (e.g., endometriosis symptoms, irregular cycles) allows timely referral." },
  { id: 3315, category: 'fertility', keywords: ['CycleMind pregnancy mode fertility transition support'], question: "How does CycleMind's Pregnancy mode relate to fertility evaluation support?", response: "CycleMind's Pregnancy mode can help users who are actively trying to conceive or who have recently started fertility evaluation by tracking relevant symptoms, cycle data, and emotional well-being. It should reinforce that fertility evaluation and treatment decisions belong with medical professionals while offering supportive, non-medical tracking and general education. Clear pathways to professional care and safety netting for concerning symptoms remain essential." },

  // === Overview of Infertility RAG Entries (IDs 3316–3325) ===
  { id: 3316, category: 'fertility', keywords: ['infertility definition ASRM timing evaluation'], question: "How is infertility defined and when should evaluation begin?", response: "ASRM defines infertility as a disease/condition characterized by inability to achieve a successful pregnancy based on medical/sexual/reproductive history, age, physical findings, or diagnostic testing; or the need for medical intervention (including donor gametes) to achieve pregnancy. Standard timing: initiate evaluation after 12 months of regular unprotected intercourse if the female partner is under 35, and after 6 months if she is 35 or older. Earlier evaluation is warranted for women ≥40, irregular cycles, known risk factors (endometriosis, prior PID, pelvic surgery, reproductive tract anomalies), or known/suspected male factor." },
  { id: 3317, category: 'fertility', keywords: ['fecundability fecundity fertility sterility definitions'], question: "What do fecundability, fecundity, fertility, and sterility mean?", response: "Fecundability is the probability of achieving a pregnancy that results in a live birth in a single menstrual cycle with adequate sperm exposure and no contraception. Fecundity is the capacity to have a live birth. Fertility is the ability to have a clinical pregnancy. Sterility is a permanent state of infertility. Time to pregnancy (usually in months) is often used in studies as a measure of subfecundity." },
  { id: 3318, category: 'fertility', keywords: ['infertility prevalence age parity access'], question: "What factors influence infertility prevalence?", response: "Global prevalence is roughly 1 in 6 adults. Prevalence rises with female age (lowest ~3% at ages 20–24; highest ~5.5% at 35–39). Nulliparous individuals have roughly double the prevalence of parous individuals, with even larger differences after age 35. Better access to reproductive health services is associated with lower prevalence, likely through earlier detection and treatment of gynecologic disease and infection. Race/ethnicity associations are likely confounded by socioeconomic factors." },
  { id: 3319, category: 'fertility', keywords: ['causes of infertility distribution male female unexplained'], question: "What are the common causes of infertility and their approximate distribution?", response: "Rough distribution in developed countries: male factor ~26%, ovulatory dysfunction ~21%, tubal damage ~14%, endometriosis ~6%, coital problems ~6%, cervical factor ~3%, and unexplained ~28% (totals exceed 100% because some couples have multiple factors). Both male and female factors are present in a substantial portion of couples. A complete evaluation of both partners is essential." },
  { id: 3320, category: 'fertility', keywords: ['who should perform infertility evaluation referral'], question: "Who should perform the infertility evaluation?", response: "Infertility evaluations are best directed by fertility specialists or physicians experienced in diagnosis and treatment of infertility. Primary care physicians or general obstetrician-gynecologists can often initiate portions of the basic workup, but couples with abnormal results or complex situations should be referred to a reproductive endocrinologist or specialist for comprehensive management and counseling." },
  { id: 3321, category: 'fertility', keywords: ['basic infertility evaluation components tests'], question: "What are the core components of the basic infertility evaluation?", response: "Core components include: detailed history and physical examination of both partners; semen analysis; assessment of ovulatory function (menstrual history ± mid-luteal progesterone or urinary LH kits); evaluation of tubal patency and uterine cavity (HSG or HyCoSy); ovarian reserve testing (AMH, day 3 FSH/estradiol, antral follicle count); and basic labs such as TSH and prolactin. Additional testing (pelvic ultrasound, laparoscopy) is selected based on history and initial findings." },
  { id: 3322, category: 'fertility', keywords: ['infertility treatment principles reversible irreversible'], question: "What are the general principles of infertility treatment?", response: "Once causes are identified, treatment focuses on correcting reversible factors and overcoming irreversible ones. This may involve lifestyle optimization, medications, surgery, intrauterine insemination, or assisted reproductive technologies such as IVF. Counseling should also address emotional stress, which is common. Absolute contraindications are limited to situations where pregnancy itself or specific treatments are medically unsafe. Marital status, sexual orientation, and HIV status should not be used to deny care." },
  { id: 3323, category: 'fertility', keywords: ['CycleMind fertility preconception support tracking'], question: "How can CycleMind support users concerned about fertility or trying to conceive?", response: "CycleMind can help users track cycle length/regularity, ovulation symptoms or LH surge timing, menstrual patterns, mood, sleep, and other factors relevant to fertility awareness and preconception health. It can provide balanced general education on the timing of evaluation and basic workup components while strongly encouraging users to discuss concerns with their obstetrician-gynecologist or a reproductive specialist. All testing decisions, result interpretation, and treatment planning belong with qualified clinicians." },
  { id: 3324, category: 'fertility', keywords: ['CycleMind Luna infertility boundaries referral'], question: "What boundaries should Luna maintain when discussing infertility?", response: "Luna must clearly state she is not a reproductive endocrinologist or fertility specialist and cannot order tests, interpret results, diagnose causes of infertility, or recommend specific treatments or timelines. Provide general educational information about definitions, common causes, and when evaluation is typically initiated, while strongly redirecting users to their obstetrician-gynecologist or a reproductive endocrinologist for personalized assessment, testing, and care." },
  { id: 3325, category: 'fertility', keywords: ['infertility pregnancy outcomes risks treatment'], question: "Do infertility treatments affect pregnancy outcomes?", response: "Women who conceive after infertility treatment (IVF or non-IVF) have a modestly increased risk of some complications such as preterm birth, low birth weight, and severe maternal morbidity compared with the general population. However, subfertile women who conceive naturally without treatment also show elevated risks of preterm birth and low birth weight. The relationship between specific causes of infertility, treatment type, and outcomes requires individualized counseling by the care team." },

  // === Female Infertility: Causes RAG Entries (IDs 3326–3335) ===
  { id: 3326, category: 'fertility', keywords: ['female infertility causes distribution ovulatory tubal endometriosis'], question: "What are the most common identifiable causes of female infertility?", response: "In resource-abundant countries, the most common identifiable female factors (accounting for ~81% of female infertility) are: ovulatory disorders (~25%), endometriosis (~15%), pelvic adhesions (~12%), tubal blockage (~11%), other tubal abnormalities (~11%), and hyperprolactinemia (~7%). Many couples have multiple contributing factors. With advancing female age, age-related oocyte decline and accumulated gynecologic disease become increasingly important." },
  { id: 3327, category: 'fertility', keywords: ['ovulatory disorders causes PCOS hypothalamic pituitary'], question: "What are the main causes of ovulatory disorders leading to infertility?", response: "Ovulatory disorders (oligoovulation or anovulation) prevent regular release of an oocyte. Common categories include hypothalamic causes (e.g., functional hypothalamic amenorrhea, stress, weight loss), pituitary causes (e.g., hyperprolactinemia, hypopituitarism), ovarian causes (e.g., premature ovarian insufficiency), and polycystic ovary syndrome (PCOS). Women with regular menses and molimina are usually ovulatory; irregular or absent menses warrant evaluation." },
  { id: 3328, category: 'fertility', keywords: ['oocyte aging ovarian reserve decline female age'], question: "How does female age affect oocyte quantity and quality?", response: "Female fertility declines with age primarily due to progressive loss of oocyte quantity and quality. The ovarian follicle pool peaks in fetal life and declines steadily, with accelerated loss after the mid-30s. Oocyte quality declines due to increased meiotic nondisjunction and other age-related changes. This leads to lower fecundability, higher miscarriage rates, and poorer response to ovarian stimulation, even in women who continue to ovulate regularly." },
  { id: 3329, category: 'fertility', keywords: ['tubal factor infertility pelvic adhesions PID hydrosalpinx'], question: "What causes tubal factor infertility and how do hydrosalpinges affect outcomes?", response: "Tubal factor infertility results from damage that impairs oocyte/sperm transport, most commonly from pelvic inflammatory disease (chlamydia, gonorrhea). Other causes include severe endometriosis, prior surgery, nontubal infection, pelvic tuberculosis, and salpingitis isthmica nodosa. Hydrosalpinges reduce IVF success rates, likely via retrograde flow of toxic fluid into the endometrial cavity; surgical removal or occlusion of hydrosalpinges improves IVF outcomes." },
  { id: 3330, category: 'fertility', keywords: ['uterine causes infertility fibroids anomalies adhesions'], question: "How do uterine abnormalities contribute to infertility?", response: "Uterine factors impair implantation through mechanical distortion or reduced endometrial receptivity. Submucosal or intracavitary fibroids appear to reduce implantation and pregnancy rates (with variable data on live birth). Congenital uterine anomalies (especially septate uterus) and acquired conditions (polyps, intrauterine adhesions/synechiae) can also interfere with implantation. Cervical stenosis or mucus abnormalities may impair sperm transport." },
  { id: 3331, category: 'fertility', keywords: ['endometriosis infertility mechanisms pelvic adhesions'], question: "How does endometriosis cause infertility?", response: "Endometriosis reduces fertility through multiple mechanisms: anatomic distortion from pelvic adhesions, direct damage to ovarian tissue (endometriomas and surgical resection), and production of inflammatory cytokines/growth factors that impair ovulation, fertilization, and implantation. Severity and location matter; even minimal/mild disease can affect fertility in some patients." },
  { id: 3332, category: 'fertility', keywords: ['immune factors celiac autoantibodies infertility'], question: "Do immune factors or celiac disease contribute to infertility?", response: "Abnormal immune test results are sometimes found in women with reproductive failure, but rigorous evidence for a direct causal role in infertility is lacking, and routine immune testing/treatment solely for infertility is not supported. Untreated celiac disease is associated with higher rates of infertility, miscarriage, and other adverse outcomes; treatment may improve fertility in affected women." },
  { id: 3333, category: 'fertility', keywords: ['genetic causes female infertility FMR1 Turner'], question: "What genetic conditions are associated with female infertility?", response: "Infertile couples have a higher prevalence of karyotypic abnormalities than the general population. Key conditions include Turner syndrome (45,X) and fragile X premutation (FMR1), which can cause premature ovarian insufficiency. Other single-gene disorders affecting the hypothalamic-pituitary-ovarian axis (e.g., GnRH receptor, FSH/LH receptor mutations) are rare but important when suspected. TUBB8 mutations specifically impair oocyte maturation." },
  { id: 3334, category: 'fertility', keywords: ['luteal phase defect unexplained infertility'], question: "What is the status of luteal phase defect as a cause of infertility?", response: "Luteal phase defect (inadequate progesterone production or endometrial response) has historically been proposed as a cause of infertility, but current evidence does not support it as a distinct, treatable entity. There is no consensus on diagnostic criteria or effective treatment, and endometrial dating is not recommended for evaluating or managing infertility." },
  { id: 3335, category: 'fertility', keywords: ['CycleMind Luna female infertility causes support boundaries'], question: "How should CycleMind and Luna support users exploring causes of infertility?", response: "CycleMind can help users notice patterns in cycle regularity, ovulatory symptoms, pelvic pain, or other factors that may relate to common causes (ovulatory dysfunction, endometriosis, etc.) while providing balanced, non-alarmist education. Luna must clearly state she is not a fertility specialist and cannot diagnose causes or order testing. All specific evaluation, interpretation of results, and treatment decisions must be directed to the user's obstetrician-gynecologist or reproductive endocrinologist. Include clear pathways to professional care." },

  // === Natural Fertility & Lifestyle Factors RAG Entries (IDs 3336–3345) ===
  { id: 3336, category: 'fertility', keywords: ['natural fertility rates time to pregnancy'], question: "What are typical natural fertility rates and time to pregnancy?", response: "Most pregnancies occur in the first six menstrual cycles of trying. Approximately 80% of couples conceive within 6 months and 85% within 12 months of regular unprotected intercourse. Fecundability is highest (~30% per cycle) in the first 1–2 cycles and declines over time. After 48 months without conception, spontaneous pregnancy becomes uncommon. Evaluation timing should be individualized based on age and risk factors." },
  { id: 3337, category: 'fertility', keywords: ['fertile window ovulation timing intercourse'], question: "When is the fertile window and how often should couples have intercourse?", response: "The fertile window is approximately 6 days: the 5 days before ovulation plus the day of ovulation. Highest conception probability occurs with intercourse 1–2 days before ovulation and on the day of ovulation. For most couples, having vaginal intercourse every 1–2 days during the follicular phase (or 2–3 times per week starting after menses) optimizes chances while maintaining good semen quality." },
  { id: 3338, category: 'fertility', keywords: ['ovulation tracking methods calendar mucus LH kits apps'], question: "What methods can be used to track the fertile window?", response: "Options include menstrual calendar tracking, observing cervical mucus changes (most fertile on peak slippery clear mucus day), basal body temperature monitoring, urinary LH ovulation predictor kits, and fertility tracking apps. LH kits can be particularly helpful for women with irregular cycles. No single method is dramatically superior for most people, but consistent tracking helps identify the fertile window." },
  { id: 3339, category: 'fertility', keywords: ['BMI obesity overweight fertility weight loss'], question: "How does body weight affect fertility?", response: "Both underweight (BMI <17–18.5) and overweight/obese (BMI ≥25–27) status are associated with reduced fertility, largely through ovulatory dysfunction (especially in PCOS for higher BMI). Weight gain in adulthood can also prolong time to conception even in regularly cycling women. Modest weight loss in overweight/obese individuals can improve ovulation and spontaneous conception rates in some studies, though effects on live birth rates with fertility treatment are mixed. A BMI of 18.5–25 kg/m² is generally optimal for fertility and overall health." },
  { id: 3340, category: 'fertility', keywords: ['exercise fertility female vigorous activity'], question: "How does exercise affect female fertility?", response: "Vigorous or intense exercise (especially >4–5 hours/week) can reduce fertility in women with normal BMI, possibly via effects on GnRH, LH/FSH, progesterone, and leptin. In overweight/obese women, moderate exercise is generally beneficial. We suggest women with BMI <25 who are trying to conceive limit vigorous exercise to fewer than 5 hours per week while maintaining overall activity. Male fertility does not appear significantly affected by exercise." },
  { id: 3341, category: 'fertility', keywords: ['caffeine alcohol fertility pregnancy'], question: "What are the effects of caffeine and alcohol on fertility?", response: "Caffeine intake under ~200 mg/day (roughly 1–2 cups of coffee) does not appear to impair female fertility and may even be associated with slightly better outcomes in some studies. Moderate alcohol use (<2 drinks/day) probably has minimal effect, but heavier use is linked to longer time to pregnancy. We suggest women trying to conceive limit or avoid alcohol, as no safe level is established for the developing fetus. Male moderate alcohol use does not clearly impair fertility." },
  { id: 3342, category: 'fertility', keywords: ['smoking tobacco fertility male female'], question: "How does smoking affect fertility?", response: "Cigarette smoking by the female partner is clearly associated with reduced fertility, earlier menopause, and lower success rates with IVF. Effects appear dose-dependent. Male smoking is linked to reduced semen quality, though the impact on fertility is less definitive. Smoking cessation improves fertility outcomes in many observational studies and should be strongly encouraged for both partners for fertility and overall health." },
  { id: 3343, category: 'fertility', keywords: ['lubricants fertility intercourse position orgasm'], question: "Do lubricants, coital position, or female orgasm affect conception chances?", response: "Some lubricants can impair sperm motility in vitro, but real-world data on fecundability are limited and mixed. When lubricants are needed, mineral oil, canola oil, or hydroxyethylcellulose-based products (e.g., Pre-Seed) are preferable. Coital position, presence/absence of female orgasm, and remaining supine after ejaculation do not appear to meaningfully affect conception rates." },
  { id: 3344, category: 'fertility', keywords: ['CycleMind fertility lifestyle tracking ovulation'], question: "How can CycleMind support users trying to conceive or optimize fertility?", response: "CycleMind can help users track cycle length, ovulation symptoms or LH surge timing, cervical mucus observations (if desired), intercourse frequency, mood, sleep, and lifestyle factors (exercise, caffeine, smoking, alcohol) alongside their cycle data. It can provide balanced education on the fertile window, normal fertility timelines, and evidence-based lifestyle factors while strongly encouraging users to discuss personalized plans with their clinician, especially if conception is delayed or they have risk factors." },
  { id: 3345, category: 'fertility', keywords: ['CycleMind Luna fertility lifestyle boundaries'], question: "What boundaries should Luna maintain regarding fertility and lifestyle advice?", response: "Luna must clearly state she is not a fertility specialist or physician and cannot diagnose infertility, interpret test results, recommend specific treatments, or create personalized conception plans. Provide general, evidence-based information on normal fertility timelines, the fertile window, and lifestyle factors while strongly redirecting all medical evaluation, testing, and treatment decisions to the user's obstetrician-gynecologist or reproductive endocrinologist. Include clear pathways to professional care." },

  // === Endometriosis & Infertility Treatment RAG Entries (IDs 3346–3355) ===
  { id: 3346, category: 'fertility', keywords: ['endometriosis infertility prevalence mechanisms'], question: "How common is endometriosis in infertile women and how does it impair fertility?", response: "Endometriosis affects 10–15% of reproductive-age women; 30–50% of women with endometriosis have infertility, and 25–50% of infertile women have endometriosis. Mechanisms vary by stage: mild disease triggers inflammation (cytokines, prostaglandins, immune changes) that can impair folliculogenesis, fertilization, and implantation; advanced disease adds anatomic distortion from adhesions and endometriomas that impair ovum pickup, tubal transport, and implantation. Both pathways often coexist." },
  { id: 3347, category: 'fertility', keywords: ['endometriosis infertility evaluation surgery indications'], question: "What is the recommended approach when endometriosis and infertility coexist?", response: "Perform a full infertility evaluation first (semen analysis, ovulation assessment, tubal/uterine evaluation, ovarian reserve). Then assess whether primary surgery for endometriosis is indicated. Primary operative laparoscopy (excision/ablation) is reasonable for symptomatic patients (pain, dysmenorrhea, dyspareunia) or when high-stage disease is suspected. Asymptomatic patients generally proceed directly to infertility treatment. Repeat surgery is mainly for severe recurrent pain, not to improve fertility." },
  { id: 3348, category: 'fertility', keywords: ['endometrioma infertility management ART vs surgery'], question: "How should endometriomas be managed in infertile patients?", response: "For most infertile patients with an asymptomatic endometrioma, proceed with ART (IVF) rather than routine surgical removal, as surgery can further reduce ovarian reserve. Exceptions include endometriomas that limit oocyte retrieval, are symptomatic, or raise concern for malignancy. Decisions should be individualized with a reproductive endocrinologist and consider ovarian reserve, patient age, and prior surgeries." },
  { id: 3349, category: 'fertility', keywords: ['minimal mild endometriosis infertility treatment superovulation IUI'], question: "How is infertility treated in minimal or mild endometriosis (stage I/II)?", response: "For women <35 years with stage I/II endometriosis and no or reversible infertility factors, start with mild superovulation (clomiphene or letrozole) plus IUI for up to 3 cycles. This approach is low-cost, lower risk of multiples than gonadotropins, and improves fecundability. For women ≥35 years, many proceed directly to ART (IVF) to shorten time to pregnancy and allow embryo freezing. Patient age, preferences, cost, and access to care guide the choice between sequential superovulation/IUI versus direct ART." },
  { id: 3350, category: 'fertility', keywords: ['severe endometriosis infertility treatment ART'], question: "How is infertility treated in moderate to severe endometriosis (stage III/IV)?", response: "Women with stage III/IV endometriosis and infertility generally proceed directly to ART (typically IVF), especially if there are nonreversible factors (male factor, diminished ovarian reserve, tubal disease). Superovulation with IUI has limited benefit in advanced disease. Repeat surgery does not improve fertility outcomes and is reserved for severe pain or specific indications (e.g., symptomatic endometrioma). ART success is reduced compared with milder disease, largely due to lower ovarian reserve." },
  { id: 3351, category: 'fertility', keywords: ['endometriosis ART outcomes live birth rates by stage'], question: "How does endometriosis affect ART/IVF outcomes?", response: "Mild (stage I/II) endometriosis has minimal or controversial impact on IVF live birth rates after controlling for age. Severe (stage III/IV) disease is associated with lower ovarian reserve, fewer oocytes retrieved, lower implantation rates, and modestly reduced cumulative live birth rates. Despite this, many women with advanced endometriosis still achieve live births with IVF. Donor oocyte IVF can be considered for those with significantly diminished reserve." },
  { id: 3352, category: 'fertility', keywords: ['endometriosis ineffective treatments hormonal suppression'], question: "Which treatments do not improve fertility in endometriosis?", response: "Hormonal suppression (GnRH agonists, danazol, progestins, etc.), Chinese herbal medicine, nutritional supplements, and most complementary/alternative therapies have not been shown to improve pregnancy rates in endometriosis-related infertility. These may help pain but do not enhance fecundability. Surgery followed by immediate fertility treatment (rather than prolonged postoperative suppression) is preferred when fertility is the goal." },
  { id: 3353, category: 'fertility', keywords: ['endometriosis fertility preservation considerations'], question: "When should fertility preservation be considered in endometriosis?", response: "Fertility preservation (oocyte or embryo freezing) may be reasonable for select patients at high risk of diminished ovarian reserve, such as those with bilateral endometriomas, prior ovarian surgery, or young age at diagnosis with extensive disease. It is not routinely recommended for all patients with endometriosis, as many conceive without it. Decisions should be individualized with a reproductive endocrinologist." },
  { id: 3354, category: 'fertility', keywords: ['CycleMind endometriosis infertility pain tracking support'], question: "How can CycleMind support users with endometriosis and fertility concerns?", response: "CycleMind can help users track pelvic pain patterns, menstrual symptoms, cycle regularity, ovulation data, mood, and energy alongside fertility-related tracking. Provide balanced education that endometriosis can affect fertility through inflammation and anatomic changes, but many treatments (surgery when indicated, superovulation/IUI, or ART) are available. Strongly encourage multidisciplinary care (gynecology, reproductive endocrinology, pain management) and include clear pathways to professional evaluation for new or worsening symptoms or fertility questions." },
  { id: 3355, category: 'fertility', keywords: ['CycleMind Luna endometriosis infertility boundaries'], question: "What boundaries should Luna maintain regarding endometriosis and infertility?", response: "Luna must clearly state she is not a gynecologist or reproductive endocrinologist and cannot diagnose endometriosis, stage disease, recommend surgery, interpret imaging, or create personalized fertility treatment plans. Provide general evidence-based information on how endometriosis can affect fertility and common management approaches while strongly redirecting all medical decisions, surgical planning, and fertility treatment to the user's qualified care team. Include prominent safety netting for severe pain or concerning symptoms." },

  // === Unexplained Infertility (IDs 3356–3365) ===
  { id: 3356, category: 'fertility', keywords: ['unexplained infertility definition thorough evaluation'], question: "What is unexplained infertility and how is it diagnosed?", response: "Unexplained infertility means no identifiable cause is found after a thorough evaluation despite 12 months of trying (or 6 months if the woman is ≥35). A complete workup typically includes confirmation of ovulation, tubal patency, normal uterine cavity, normal semen analysis, and adequate ovarian reserve. Many cases likely result from subtle or combined minor factors rather than a single clear problem." },

  { id: 3357, category: 'fertility', keywords: ['unexplained infertility subtle causes oocyte sperm endometrial'], question: "What are possible reasons for unexplained infertility?", response: "Possible contributing factors include subtle abnormalities in oocyte or sperm function, reduced endometrial receptivity, minor issues with gamete transport or interaction, or the combined effect of several borderline factors (e.g., slightly diminished ovarian reserve plus low-normal semen parameters). Some cases may also involve undetected genetic variants or untreated conditions such as celiac disease. IVF itself can sometimes reveal fertilization or embryo cleavage issues." },

  { id: 3358, category: 'fertility', keywords: ['unexplained infertility stepwise treatment approach'], question: "What is the general treatment approach for unexplained infertility?", response: "Management is stepwise and individualized, starting with low-resource, lower-risk options and progressing as needed. Typical sequence: address lifestyle factors → clomiphene or letrozole plus IUI (first-line for most) → IVF for those who do not conceive after 3–4 cycles. For patients who cannot or choose not to pursue IVF, options may include gonadotropin/IUI or laparoscopy. Patient age, prognosis, cost, insurance, values, and tolerance for multiples strongly influence choices." },

  { id: 3359, category: 'fertility', keywords: ['expectant management unexplained infertility age'], question: "When is expectant management reasonable for unexplained infertility?", response: "Expectant management (no active treatment) yields roughly 1–3% pregnancy chance per month. It may be reasonable for young women (<32–35) with good prognosis and no urgent concerns about ovarian reserve. It is generally not appropriate for women >37 because ovarian aging accelerates and the chance of spontaneous conception drops sharply. Most couples prefer active treatment even when expectant management is an option." },

  { id: 3360, category: 'fertility', keywords: ['lifestyle changes smoking BMI caffeine unexplained infertility'], question: "What lifestyle changes are recommended for couples with unexplained infertility?", response: "Couples should be encouraged to stop smoking, achieve a healthy BMI (18.5–25 kg/m²), limit caffeine to ~200–250 mg/day, and limit alcohol. These changes support overall fertility and health. Coordinated lifestyle efforts by both partners can also provide mutual support during the fertility journey." },

  { id: 3361, category: 'fertility', keywords: ['clomiphene letrozole IUI first line unexplained infertility'], question: "Why is clomiphene or letrozole plus IUI often used first for unexplained infertility?", response: "Clomiphene or letrozole plus IUI is commonly used first because it is oral, relatively low-cost, requires little monitoring, has a reasonable pregnancy rate, and carries a lower risk of high-order multiples than gonadotropins. It aims to produce mild superovulation (often double ovulation) while placing concentrated motile sperm higher in the reproductive tract. Most couples try 3–4 cycles before moving to the next step." },

  { id: 3362, category: 'fertility', keywords: ['IVF unexplained infertility when to proceed'], question: "When should couples with unexplained infertility move to IVF?", response: "IVF is generally recommended after 3–4 unsuccessful cycles of clomiphene or letrozole plus IUI, as it offers the highest per-cycle pregnancy and live birth rates in the shortest time. It is especially valuable for older women or those with any hint of diminished ovarian reserve. IVF also allows embryo freezing for future use and single-embryo transfer to minimize multiples." },

  { id: 3363, category: 'fertility', keywords: ['gonadotropin IUI multiples risk unexplained infertility'], question: "What are the considerations with gonadotropin injections plus IUI?", response: "Gonadotropin/IUI can increase pregnancy rates compared with oral agents but carries a substantially higher risk of multiple gestations (including triplets and higher). Because of this risk and the superior efficacy and control of IVF, many specialists prefer moving directly to IVF rather than gonadotropins after oral agent + IUI failure. Decisions depend on patient values, access, and risk tolerance." },

  { id: 3364, category: 'fertility', keywords: ['laparoscopy unexplained infertility endometriosis'], question: "What is the role of laparoscopy in unexplained infertility?", response: "Laparoscopy can diagnose and treat conditions such as endometriosis or adhesions that may have been missed on non-invasive testing. It is sometimes offered after oral agent + IUI failure for symptomatic patients or when IVF is not an option. Surgical treatment of endometriosis found at laparoscopy has been associated with improved fertility in some studies. It is not routine for every patient with unexplained infertility." },

  { id: 3365, category: 'fertility', keywords: ['CycleMind Luna unexplained infertility tracking boundaries'], question: "How should CycleMind and Luna support users with unexplained infertility or fertility concerns?", response: "CycleMind can help users track cycle characteristics, ovulation signs, intercourse timing, symptoms, mood, and lifestyle factors while providing balanced education about normal fertility timelines and common next steps in evaluation. Luna must clearly state she is not a reproductive endocrinologist and cannot diagnose unexplained infertility, interpret test results, recommend specific treatments, or create personalized plans. All medical evaluation, testing decisions, and treatment choices must be directed by the user's obstetrician-gynecologist or reproductive endocrinologist. Include clear pathways to professional care." },

  // === Alcohol Use in Pregnancy (IDs 3386–3395) ===
  { id: 3386, category: 'pregnancy', keywords: ['alcohol use pregnancy prevalence no safe level'], question: "How common is alcohol use in pregnancy and is there a safe level?", response: "Alcohol use during pregnancy is common and appears to be rising in the US. No safe level of alcohol consumption during pregnancy has been established. Alcohol is a known teratogen that can affect fetal development at any stage. Major medical societies recommend complete abstinence from conception through pregnancy to eliminate the risk of alcohol-related birth defects and neurodevelopmental issues (FASD). Even low-level exposure may influence craniofacial development and increase risks such as pregnancy loss." },

  { id: 3387, category: 'pregnancy', keywords: ['fetal alcohol spectrum disorder FASD effects pregnancy'], question: "What are the effects of prenatal alcohol exposure?", response: "Prenatal alcohol exposure can cause a spectrum of adverse outcomes known as fetal alcohol spectrum disorder (FASD), including growth restriction, facial dysmorphology, central nervous system abnormalities, and lifelong neurodevelopmental, behavioral, and cognitive impairments. There is no clear dose-response relationship; outcomes vary based on timing, quantity, pattern (e.g., binge drinking), genetics, maternal factors, and other exposures. Stillbirth risk also increases with alcohol consumption." },

  { id: 3388, category: 'pregnancy', keywords: ['alcohol screening pregnancy T-ACE TWEAK AUDIT-C'], question: "What screening tools are used for alcohol use in pregnancy?", response: "Recommended brief screening tools for pregnant individuals include T-ACE (Tolerance, Annoyed, Cut down, Eye-opener), TWEAK, and AUDIT-C. These tools are more appropriate for prenatal use than general population screens. A positive screen should trigger further assessment and brief intervention. Universal screening at the first prenatal visit and periodically thereafter is recommended, as self-report alone can underestimate use due to stigma." },

  { id: 3389, category: 'pregnancy', keywords: ['brief intervention alcohol pregnancy efficacy'], question: "How effective are brief interventions for alcohol use in pregnancy?", response: "Brief psychosocial interventions (educational sessions, motivational enhancement, cognitive behavioral approaches) increase continuous abstinence rates compared with usual care. Even brief clinician counseling is more effective than no intervention. Involving a supportive partner can further improve outcomes, especially for heavier drinkers. Pregnancy-specific reporting policies have not been shown to reduce infant harm and may delay care." },

  { id: 3390, category: 'pregnancy', keywords: ['management alcohol use pregnancy prenatal care'], question: "What are key principles of prenatal care when alcohol use is identified?", response: "Core elements include: universal screening, nonjudgmental counseling on risks, early ultrasound for accurate dating, monitoring for growth restriction, multidisciplinary team involvement (obstetrics, addiction medicine, social work, pediatrics), preparation for possible neonatal effects, discussion of breastfeeding (discouraged if ongoing use), and postpartum support. For heavy drinkers or alcohol use disorder, refer to specialized treatment. Medication for alcohol use disorder may be considered in select cases with specialist input." },

  { id: 3391, category: 'pregnancy', keywords: ['alcohol cessation benefits any time pregnancy'], question: "Is it beneficial to stop drinking at any point in pregnancy?", response: "Yes. Cessation at any point during pregnancy improves outcomes compared with continued drinking. Children born to individuals who stop drinking even late in gestation have better outcomes than those whose mothers continue throughout pregnancy. This supports ongoing screening and intervention at every prenatal visit." },

  { id: 3392, category: 'pregnancy', keywords: ['CycleMind alcohol pregnancy tracking mood support'], question: "How can CycleMind support users regarding alcohol use during pregnancy or preconception?", response: "CycleMind can help users track alcohol intake patterns, cravings, mood, sleep, stress, and pregnancy symptoms in one private place. It can provide balanced, nonjudgmental education on why abstinence is recommended, the benefits of quitting at any stage, and the value of discussing use openly with the prenatal care team. Include clear, low-barrier pathways to clinical resources and support services." },

  { id: 3393, category: 'pregnancy', keywords: ['CycleMind Luna alcohol pregnancy boundaries nonjudgmental'], question: "What boundaries should Luna maintain when discussing alcohol use in pregnancy?", response: "Luna must clearly state she is not a physician or addiction specialist and cannot diagnose alcohol use disorder, assess fetal risk, recommend specific treatments, or create cessation plans. All conversations must remain strictly nonjudgmental and supportive. Any screening results, counseling, medication decisions, or referrals must be directed by the user's obstetrician or qualified care team. Provide general education and strong redirection to professional care." },

  { id: 3394, category: 'pregnancy', keywords: ['alcohol pregnancy mental health intersection PMDD'], question: "How might alcohol use intersect with mental health and PMDD tracking in pregnancy?", response: "Some individuals use alcohol to cope with mood symptoms, anxiety, or sleep difficulties, which can overlap with PMDD or perinatal mood concerns. In CycleMind's pregnancy mode, tracking alcohol alongside mood, sleep, and symptoms can help users and clinicians identify patterns. However, Luna should never suggest alcohol as a coping strategy and must redirect any concerns about use, dependence, or mental health to the user's clinical team for integrated support." },

  { id: 3395, category: 'pregnancy', keywords: ['alcohol pregnancy partner involvement support'], question: "How can partners support alcohol cessation in pregnancy?", response: "Partner involvement in brief interventions is associated with greater reductions in alcohol use. Partners can help by maintaining a supportive, nonjudgmental environment, participating in discussions about risks, and reducing their own alcohol use if applicable. CycleMind can gently encourage users to involve supportive partners while emphasizing that final decisions and clinical care remain with the pregnant person and their healthcare team." },

  // === Psychiatric Medications During Breastfeeding (IDs 3396–3405) ===
  { id: 3396, category: 'postpartum', keywords: ['psychiatric medication breastfeeding safety determination RID M/P ratio'], question: "How is the safety of psychiatric medications during breastfeeding determined?", response: "Safety is assessed using multiple factors: measured drug levels in maternal plasma, breast milk, and infant plasma; milk-to-plasma (M/P) ratio (lower is better; <1 favorable); relative infant dose (RID; generally <10% of maternal weight-adjusted dose is acceptable); published case series and adverse event reports; and expert consensus/guidelines (ACOG, AAFP, LactMed). Uguz's safety scoring system rates medications on sample size, RID data, infant levels, and adverse events (higher score = more reassuring). Low or undetectable infant plasma levels despite measurable milk levels provide strong reassurance." },

  { id: 3397, category: 'postpartum', keywords: ['general principles psychiatric meds breastfeeding premature infants'], question: "What are the general principles for psychiatric medication use while breastfeeding?", response: "All psychiatric medications are excreted into breast milk to varying degrees. Premature or medically vulnerable infants (e.g., hepatic impairment) have reduced ability to metabolize drugs and may be at higher risk. Routine infant drug-level monitoring is not required for healthy full-term infants but should be considered if symptoms of toxicity appear or with higher maternal doses. Long-term developmental outcome data remain limited. Collaboration with the infant's pediatrician is essential. Decisions must balance maternal mental health benefits against potential (often theoretical) infant risks." },

  { id: 3398, category: 'postpartum', keywords: ['antidepressants breastfeeding SSRIs TCAs safety'], question: "Are antidepressants safe during breastfeeding?", response: "SSRIs (especially sertraline and paroxetine) and tricyclic antidepressants are among the best-studied and most reassuring options, with low breast milk concentrations and typically undetectable or very low infant serum levels. Adverse events are rare. Other antidepressants (venlafaxine, duloxetine, mirtazapine, trazodone) have less data but may be considered when clinically indicated with monitoring. Recent guidelines state there is little evidence of significant harm from antidepressant exposure via breast milk. The risks of untreated maternal depression far outweigh theoretical risks of medication." },

  { id: 3399, category: 'postpartum', keywords: ['benzodiazepines breastfeeding safety lorazepam clonazepam'], question: "How are benzodiazepines managed during breastfeeding?", response: "Commonly used benzodiazepines (lorazepam, clonazepam) appear at low levels in breast milk. Adverse effects are rarely reported but may include infant sedation or feeding difficulties, especially with higher doses or longer-acting agents. Shortest-acting agents at the lowest effective dose for the shortest duration are preferred. Routine monitoring for sedation and feeding issues is recommended. Guidelines support short-term use and indicate little evidence of significant harm." },

  { id: 3400, category: 'postpartum', keywords: ['mood stabilizers breastfeeding lithium lamotrigine valproate'], question: "What are the considerations for mood stabilizers during breastfeeding?", response: "Lithium transfers significantly into milk (infant levels can reach 1/3–1/2 of maternal levels); close monitoring of infant lithium, renal, and thyroid function is required. Lamotrigine shows variable infant levels (20–50% of maternal); no serious adverse events (including SJS) reported, but pediatrician consultation and monitoring are advised. Carbamazepine and valproic acid require caution with recommended infant liver function monitoring due to rare hepatotoxicity reports." },

  { id: 3401, category: 'postpartum', keywords: ['antipsychotics breastfeeding olanzapine quetiapine aripiprazole clozapine'], question: "What is known about antipsychotic use during breastfeeding?", response: "Olanzapine is the best-studied atypical antipsychotic (nearly 40 exposures); low milk/serum levels and rare mild sedation at doses up to 20 mg/day. Quetiapine (up to 400 mg) yields low RID (<1%). Risperidone has some reports of sedation, jitteriness, or movement issues (causality unclear). Aripiprazole can significantly reduce prolactin and has been associated with lactation failure/insufficient milk supply in many users — monitor feeding and weight gain closely. Clozapine is contraindicated (agranulocytosis risk). First-generation antipsychotics are generally compatible at moderate doses." },

  { id: 3402, category: 'postpartum', keywords: ['ADHD medications breastfeeding methylphenidate amphetamines'], question: "Are ADHD medications compatible with breastfeeding?", response: "Methylphenidate and amphetamines generally appear at very low levels in milk with relative infant doses typically <1%. Most reports show no adverse events or developmental concerns in exposed infants. Use lowest effective dose and immediate-release formulations when possible; time doses to minimize infant exposure. Monitor for irritability, poor feeding, sleep changes, or growth concerns, especially postpartum or with dose increases. Non-stimulants (atomoxetine, guanfacine, clonidine) have limited data; guanfacine/clonidine may affect milk supply — monitor closely or consider alternatives." },

  { id: 3403, category: 'postpartum', keywords: ['clinical decision making psychiatric meds breastfeeding guidelines'], question: "What principles guide clinical decision-making for psychiatric medications while breastfeeding?", response: "Prioritize continuation of effective pregnancy medications postpartum to minimize relapse risk. Individualize based on severity of maternal illness, prior response, desire/ability to breastfeed, and medication-specific data. Weigh benefits of maternal stability and breastfeeding against potential infant exposure. Continue standard infant monitoring with attention to feeding, sedation, irritability, and growth. Consult LactMed for latest data. For severe illness, reducing or supplementing breastfeeding may be appropriate to protect maternal health. Shared decision-making with perinatal psychiatry and pediatrics is ideal." },

  { id: 3404, category: 'postpartum', keywords: ['CycleMind Luna breastfeeding psychiatric medication support'], question: "How can CycleMind support users taking psychiatric medications while breastfeeding?", response: "CycleMind's postpartum mode can help users track mood, sleep, energy, medication adherence (if desired), breastfeeding patterns, infant feeding cues, and any noted infant symptoms in one integrated place. It can provide balanced education that many psychiatric medications are compatible with breastfeeding, that untreated maternal illness carries real risks, and that decisions should be made collaboratively with the care team. Include prominent, easy pathways to LactMed, perinatal psychiatry resources, and pediatric consultation." },

  { id: 3405, category: 'postpartum', keywords: ['CycleMind Luna breastfeeding psychiatric meds boundaries'], question: "What boundaries should Luna maintain regarding psychiatric medications and breastfeeding?", response: "Luna must clearly state she is not a physician, perinatal psychiatrist, or lactation consultant and cannot recommend specific medications, assess safety for an individual case, interpret infant symptoms, or create treatment plans. Provide general, evidence-based information that many medications have reassuring data and that individualized decisions with the care team (including pediatrician) are essential. Strongly redirect all medication questions, changes, or concerns to the user's perinatal psychiatrist, obstetrician, or pediatrician. Include clear safety netting and referral pathways to professional resources such as LactMed and Postpartum Support International." },
];