// RAG Clinical Entries Part 2 (IDs 2200–3305 + 4186–4245)
// Covers: Menopause biology/epidemiology, GSM management, MHT deep dive, birth control clinical,
// PMDD overview, AUB management, contraception FAB methods, sexual dysfunction management,
// oophorectomy, absent/irregular periods, psychotherapy overview, depression management,
// suicidality, course of depression, SAD treatment, postpartum depression management,
// prevention of PPD, anxiety (GAD, SAD, panic, PTSD, OCD, BDD, hoarding, eating disorders),
// ADHD adult, perinatal antidepressant risks, Chapter 24 (forensic) + Appendix (psychotropic safety)

export const ragEntriesClinical2 = [

  // === Menopause biology IDs 2099–2108 ===
  { id: 2099, category: 'menopause', keywords: ['oocyte number at birth and menopause follicular atresia'], question: "What causes the decline in ovarian follicles over a woman's lifetime?", response: "From fetal life onward, there is continuous follicular growth and atresia. Most follicles undergo atresia (degeneration) rather than ovulation. This leads to a steady exponential decline in oocyte number, which accelerates in the years before menopause." },
  { id: 2100, category: 'menopause', keywords: ['AMH anti-Mullerian hormone ovarian reserve marker'], question: "How useful is anti-Müllerian hormone (AMH) as a marker of reproductive aging?", response: "AMH, produced by small growing follicles, declines steadily with age and is a good marker of remaining ovarian reserve. Low AMH levels correlate with a shorter time to menopause and poorer response to ovarian stimulation, though it is not routinely used to diagnose menopause itself." },
  { id: 2101, category: 'menopause', keywords: ['factors affecting age at menopause smoking genetics'], question: "What factors influence the age at which a woman reaches menopause?", response: "Genetics play a major role. Other factors include smoking (advances menopause by 1–2 years), ethnicity, night shift work, and hysterectomy (even with ovarian conservation). Family history of early menopause increases risk." },
  { id: 2102, category: 'menopause', keywords: ['definition natural menopause 12 months amenorrhea average age'], question: "How is natural menopause defined?", response: "Natural menopause is defined as the permanent cessation of menstrual periods, diagnosed retrospectively after 12 consecutive months of amenorrhea without any other obvious cause. It occurs at a median age of 51.4 years and reflects near-complete ovarian follicular depletion with resulting hypoestrogenemia and elevated FSH." },

  // === MHT risks/benefits IDs 2362–2370 ===
  { id: 2362, category: 'menopause', keywords: ['MHT risk benefit by age 50-59 younger women'], question: "How do the risks and benefits of MHT differ by age?", response: "For healthy women ages 50–59 (or <10 years since menopause), the absolute risks of MHT for 5 years are very low. In contrast, women ≥60–70 years have a less favorable risk-benefit profile, particularly for cardiovascular events. Individualized assessment is essential, and MHT is generally avoided in women ≥70 years." },
  { id: 2363, category: 'menopause', keywords: ['transdermal estrogen lower VTE stroke risk than oral'], question: "Does transdermal estrogen have a lower risk of VTE and stroke than oral?", response: "Yes. Low-dose transdermal estradiol (≤50 mcg) does not appear to increase VTE or stroke risk, while oral estrogen does. Transdermal estrogen is preferred in women with higher baseline cardiovascular or VTE risk, thrombophilias, or migraine with aura." },
  { id: 2364, category: 'menopause', keywords: ['breast cancer risk combined MHT estrogen alone WHI'], question: "How does breast cancer risk differ between combined MHT and estrogen-alone?", response: "Combined estrogen-progestin therapy (especially with medroxyprogesterone acetate) increases breast cancer risk. Estrogen-alone therapy is associated with a small reduction in breast cancer risk in the WHI. Current regimens using transdermal estradiol and micronized progesterone may have a more favorable profile, though long-term data are still limited." },
  { id: 2365, category: 'menopause', keywords: ['endometrial protection progestogen all women intact uterus'], question: "Do all women on systemic estrogen need a progestogen?", response: "Yes. Women with an intact uterus require a progestogen (micronized progesterone preferred) to prevent endometrial hyperplasia and cancer. Women who have had a hysterectomy should not take a progestogen. Low-dose vaginal estrogen does not require a progestogen." },

  // === Surgical menopause IDs 2471–2498 ===
  { id: 2471, category: 'surgical menopause', keywords: ['bilateral oophorectomy surgical menopause symptoms'], question: "What happens after bilateral oophorectomy?", response: "Bilateral oophorectomy in a premenopausal woman causes surgical menopause. Estrogen and progesterone production drops abruptly, leading to hot flashes, night sweats, vaginal dryness, low mood, sleep disturbance, difficulty concentrating, and accelerated bone loss. Symptoms can be more sudden and intense than in natural menopause. Treatment options should be discussed preoperatively." },
  { id: 2472, category: 'surgical menopause', keywords: ['oophorectomy fertility effect planning IVF donor eggs'], question: "How does oophorectomy affect fertility?", response: "Bilateral oophorectomy causes infertility without assisted reproduction. Options include egg freezing before surgery (with later IVF) or using donor eggs. Women with one remaining ovary usually retain good fertility potential. Pre-surgical fertility counseling and referral to a reproductive endocrinologist are essential if future childbearing is desired." },
  { id: 2473, category: 'surgical menopause', keywords: ['surgical menopause management hormone therapy bone health'], question: "How should surgical menopause be managed?", response: "Surgical menopause causes abrupt estrogen deficiency. Management may include menopausal hormone therapy (if not contraindicated), nonhormonal options for hot flashes, vaginal estrogen or moisturizers for GSM, and attention to bone health (calcium, vitamin D, weight-bearing exercise, and possible bone density testing). Psychological support is often needed due to the sudden transition." },

  // === Absent/irregular periods IDs 2481–2489 ===
  { id: 2481, category: 'menstrual disorders', keywords: ['absent or irregular periods definition oligomenorrhea'], question: "What are absent or irregular periods?", response: "Absent periods (amenorrhea) means no periods at all. Irregular periods (oligomenorrhea) typically means fewer than 6–8 periods per year or cycles longer than 45 days. A single missed period is common, but persistent absence or irregularity warrants evaluation after ruling out pregnancy." },
  { id: 2482, category: 'menstrual disorders', keywords: ['evaluation absent irregular periods workup FSH prolactin'], question: "What is the initial evaluation for absent or irregular periods?", response: "Start with a pregnancy test. Then obtain FSH, prolactin, TSH, and estradiol. Add total testosterone ± 17-hydroxyprogesterone if hyperandrogenism is present. Pelvic ultrasound can assess for PCOS morphology or other uterine/ovarian pathology. MRI of the pituitary is indicated if prolactin is significantly elevated or if there are neurologic symptoms." },
  { id: 2483, category: 'menstrual disorders', keywords: ['treatment of irregular periods PCOS hypothalamic contraceptives'], question: "How are absent or irregular periods treated?", response: "Treatment depends on the cause and fertility goals. Options include: combined hormonal contraceptives for regulation (if not trying to conceive), lifestyle changes (weight restoration, reduced exercise, stress management) for functional hypothalamic amenorrhea, metformin or other agents for PCOS, dopamine agonists for hyperprolactinemia, and hormone therapy for POI/early menopause." },

  // === Psychotherapy overview IDs 2521–2529 ===
  { id: 2521, category: 'psychotherapy', keywords: ['cognitive behavioral therapy CBT overview effective conditions'], question: "What is cognitive-behavioral therapy (CBT) and for which conditions is it effective?", response: "CBT helps patients identify and change maladaptive thoughts and behaviors. It is one of the most evidence-based psychotherapies and is effective for depression, anxiety disorders (including generalized anxiety, panic, and social anxiety), PTSD, OCD, eating disorders, substance use disorders, and some medical conditions (e.g., insomnia, chronic pain). It is structured, skill-based, and works best for motivated patients who value a problem-solving approach." },
  { id: 2522, category: 'psychotherapy', keywords: ['interpersonal psychotherapy IPT depression relationships'], question: "What is interpersonal psychotherapy (IPT) and when is it used?", response: "IPT is a time-limited, evidence-based therapy that focuses on improving interpersonal relationships and social functioning. It targets four main areas: grief, interpersonal disputes, role transitions, and interpersonal deficits. It is particularly effective for depression and eating disorders, and is well-suited for patients whose symptoms are linked to relationship or life transition issues." },
  { id: 2523, category: 'psychotherapy', keywords: ['dialectical behavior therapy DBT borderline emotion regulation'], question: "What is dialectical behavior therapy (DBT) and who is it best for?", response: "DBT is a structured therapy originally developed for borderline personality disorder. It combines cognitive-behavioral techniques with mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness skills. It is especially helpful for patients with severe emotion dysregulation, self-harm, or chronic suicidal thoughts." },
  { id: 2524, category: 'psychotherapy', keywords: ['motivational interviewing behavior change substance use'], question: "What is motivational interviewing and when is it useful?", response: "Motivational interviewing is a collaborative, patient-centered counseling style that helps people resolve ambivalence and increase motivation for behavior change. It is effective for substance use disorders, smoking cessation, weight management, medication adherence, and other health behavior changes." },
  { id: 2525, category: 'psychotherapy', keywords: ['remote telehealth psychotherapy as effective as in-person CBT'], question: "Is remote (telehealth) psychotherapy as effective as in-person therapy?", response: "For CBT, remote delivery appears to be as effective as in-person therapy for anxiety disorders, depression, insomnia, chronic pain, and several other conditions. Remote options significantly improve access, especially for patients with scheduling, transportation, or geographic barriers." },

  // === Depression management IDs 2531–2558 ===
  { id: 2531, category: 'depression', keywords: ['major depression severity assessment PHQ-9 treatment planning'], question: "How is the severity of major depression determined for treatment planning?", response: "Severity is based on the number, frequency, and intensity of symptoms plus the degree of functional impairment. Use the PHQ-9 (mild 5–9, moderate 10–14, moderately severe 15–19, severe ≥20). Also consider symptom duration, trajectory, suicidal ideation, psychosis, and catatonia. Treatment selection (active surveillance, psychotherapy, antidepressants, or combination) is guided by overall severity." },
  { id: 2532, category: 'depression', keywords: ['urgent management major depression emergency hospitalization'], question: "When does major depression require urgent or emergency management?", response: "Refer to the emergency department for imminent suicide risk (plan + intent + means), active suicidal behavior, intent to harm others, inability to care for self (e.g., dehydration, malnutrition), psychotic features, mania, catatonia, or need for safe detoxification. These patients generally require inpatient evaluation and stabilization." },
  { id: 2533, category: 'depression', keywords: ['treatment selection by depression severity mild moderate severe'], question: "How should initial treatment for major depression be selected based on severity?", response: "Mild (short duration, minimal impairment): Consider active surveillance + exercise or psychotherapy. Mild (prior episodes or longer duration): Antidepressant or psychotherapy. Moderate: Antidepressant or psychotherapy (combination if marked impairment). Severe: Combination of antidepressant + psychotherapy (or ECT if rapid response needed). Patient preference, access to quality psychotherapy, and prior treatment response guide the final choice." },
  { id: 2534, category: 'depression', keywords: ['antidepressant vs psychotherapy major depression comparison'], question: "How do antidepressants and psychotherapy compare for initial treatment of major depression?", response: "Both are more effective than placebo and have roughly comparable efficacy for response and remission in moderate-to-severe depression. Psychotherapy may have more lasting benefits after treatment ends. Combination therapy is often preferred for severe depression. Choice depends mainly on patient preference, availability of high-quality psychotherapy, cost, and prior treatment response." },
  { id: 2535, category: 'depression', keywords: ['SSRI selection depression which antidepressant first line'], question: "Why are SSRIs often preferred for initial treatment of mild to moderate MDD?", response: "SSRIs (e.g., escitalopram, sertraline) offer a favorable balance of efficacy, tolerability, safety in overdose, and low cost. They are effective across a range of depressive symptoms and have a well-established safety profile. Other second-generation agents (SNRIs, bupropion, mirtazapine, vortioxetine) are good alternatives when side-effect profile or specific symptoms make them more suitable." },
  { id: 2536, category: 'depression', keywords: ['antidepressant starting dose titration monitoring'], question: "How should antidepressants be initiated and titrated?", response: "Start at a low dose (often half the usual starting dose in sensitive patients) to minimize side effects, then titrate upward to the minimum therapeutic dose over 1–3 weeks. Reassess at 2–4 weeks. If there is no meaningful improvement, increase the dose toward the upper end of the usual range as tolerated. Slow titration is appropriate if side effects occur." },
  { id: 2537, category: 'depression', keywords: ['next steps partial nonresponse antidepressant switch augment'], question: "What are reasonable next steps when a patient has partial or no response to the first antidepressant?", response: "For minimal/no response: Switch to an antidepressant from a different class. For partial response: Either switch to a different-class agent or augment with a second medication (e.g., bupropion or mirtazapine). Psychotherapy can be added at any point. Reserve more complex augmentation strategies (e.g., atypical antipsychotics) for patients who have not responded to two adequate antidepressant trials." },
  { id: 2538, category: 'depression', keywords: ['antidepressant discontinuation syndrome withdrawal stopping'], question: "How should antidepressants be discontinued to minimize withdrawal symptoms?", response: "Taper antidepressants gradually rather than stopping abruptly, especially those with short half-lives (paroxetine, venlafaxine, desvenlafaxine). Fluoxetine has a long half-life and is less likely to cause discontinuation symptoms. Educate patients about possible withdrawal symptoms and taper over weeks to months depending on dose and duration of use." },
  { id: 2539, category: 'depression', keywords: ['supplemental interventions depression exercise bright light yoga'], question: "What is the role of supplemental interventions in treating major depression?", response: "Supplemental interventions (exercise, bright light therapy, mind-body practices, internet-based psychotherapy, and self-help) are primarily used as adjuncts to standard treatment. For selected patients with mild MDD (short duration, no prior episodes, minimal impairment), they can serve as stand-alone alternatives when patients prefer to avoid or cannot access standard care." },

  // === Suicidality management IDs 2561–2568 ===
  { id: 2561, category: 'suicide prevention', keywords: ['hospitalization suicidality when needed imminent risk'], question: "When should patients with suicidal ideation or behavior be hospitalized?", response: "Hospitalization is typically indicated for imminent/high risk of suicide, a recent life-threatening suicide attempt, persistent suicidal intent after an attempt, inability to ensure safety in a less restrictive setting, or lack of social support. Involuntary hospitalization may be necessary if the patient poses imminent danger to self and refuses voluntary admission." },
  { id: 2562, category: 'suicide prevention', keywords: ['safety plan for suicidality crisis warning signs coping'], question: "What is a safety plan and how is it used in managing suicidality?", response: "A safety plan is a collaboratively written document that helps patients recognize warning signs of a suicidal crisis, identify coping strategies, restrict access to lethal means, and know who to contact for support. It is used in conjunction with other treatments (not as a stand-alone intervention) and should be reviewed and updated regularly." },
  { id: 2563, category: 'suicide prevention', keywords: ['firearm safety counseling suicidality means restriction'], question: "How should clinicians counsel patients about firearm access when there is suicide risk?", response: "For patients at increased suicide risk who have access to firearms, clinicians should recommend either temporary removal of firearms or secure storage (unloaded, locked, ammunition stored separately). This is a critical, evidence-based intervention. Involve family members when appropriate and be aware of local extreme risk protection order laws." },
  { id: 2564, category: 'suicide prevention', keywords: ['lithium suicide prevention bipolar depression'], question: "When is lithium recommended for suicide prevention?", response: "Lithium is recommended for maintenance treatment in patients with bipolar disorder or major depressive disorder who remain at elevated suicide risk after acute treatment (e.g., history of multiple attempts). It has demonstrated efficacy in reducing suicide mortality in both disorders. Monitor renal and thyroid function regularly." },

  // === Course of depression IDs 2571–2579 ===
  { id: 2571, category: 'depression', keywords: ['recovery time major depressive episode typical timeline'], question: "What is the typical time to recovery from a major depressive episode?", response: "The median time to recovery from a major depressive episode is approximately 20 weeks. Many episodes remit relatively quickly (within 8 weeks), but the probability of recovery progressively decreases as episode duration increases. Risk factors for longer time to recovery include greater baseline severity, psychotic features, comorbid anxiety or personality disorders, high neuroticism, poor psychosocial functioning, and history of childhood maltreatment." },
  { id: 2572, category: 'depression', keywords: ['recurrence risk major depressive disorder after episode'], question: "What is the risk of recurrence after a major depressive episode?", response: "Major depressive disorder is highly recurrent. Approximately 50% of patients experience recurrence. The risk is highest in the first few months after recovery and then gradually declines. Each prior episode increases the risk of future recurrence by about 16%. Residual depressive symptoms after recovery are one of the strongest predictors of early recurrence." },
  { id: 2573, category: 'depression', keywords: ['residual symptoms depression recurrence predictor'], question: "How do residual symptoms affect the course of depression?", response: "Residual symptoms after recovery from a major depressive episode are one of the strongest predictors of early recurrence. Even mild residual symptoms significantly shorten the time to the next episode. This supports the importance of treating to full remission rather than just response, and continuing maintenance treatment when residual symptoms persist." },

  // === SAD treatment IDs 2581–2589 ===
  { id: 2581, category: 'seasonal affective disorder', keywords: ['winter depression first-line treatment antidepressant light therapy'], question: "What is first-line treatment for winter depression (SAD)?", response: "For winter depression, first-line treatment is typically an antidepressant (usually an SSRI) plus artificial light therapy (bright light therapy and/or dawn simulation). Antidepressants alone are a reasonable alternative. For mild to moderate winter depression, light therapy alone can also be used as first-line treatment. Severe episodes generally require pharmacotherapy, often combined with light therapy." },
  { id: 2582, category: 'seasonal affective disorder', keywords: ['bright light therapy SAD administration lux morning'], question: "How is bright light therapy administered for winter depression?", response: "Use a 10,000 lux light box with white fluorescent light. Position it ~40–80 cm away so light enters the eyes at a downward angle. Administer for 30 minutes in the early morning soon after waking. Start with 30 minutes; increase to 45–60 minutes if no response after 1–2 weeks. Treatment is typically continued daily until at least 2 weeks past the usual spring/summer offset of symptoms." },
  { id: 2583, category: 'seasonal affective disorder', keywords: ['maintenance treatment winter depression prevention relapse'], question: "How should maintenance treatment be managed after winter depression remits?", response: "Continue the acute treatment (antidepressant ± light therapy) for at least 2 weeks beyond the usual spontaneous spring/summer offset. Light therapy is typically stopped in late spring/summer and restarted in the fall (2–4 weeks before expected symptom onset). Antidepressants may be used seasonally or year-round, depending on history and severity." },

  // === Postpartum depression management IDs 2591–2598 ===
  { id: 2591, category: 'postpartum depression', keywords: ['prevalence postpartum unipolar major depression 10-15 percent'], question: "What is the prevalence of postpartum unipolar major depression?", response: "The prevalence of postpartum major depression is approximately 10–15% across studies in different countries and settings. Rates appear higher in low- and middle-income countries. Onset occurs before or during pregnancy in roughly 50% of cases. Most episodes that begin after delivery start within the first few months postpartum." },
  { id: 2592, category: 'postpartum depression', keywords: ['risk factors postpartum depression history antenatal depression'], question: "What are the strongest risk factors for postpartum depression?", response: "The two strongest and most consistent risk factors are: (1) depression during pregnancy, and (2) a prior history of depression (perinatal or non-perinatal). Other important risk factors include stressful life events, poor social support, perinatal anxiety, intimate partner violence, young maternal age, unintended pregnancy, and personality traits such as high neuroticism." },
  { id: 2593, category: 'postpartum depression', keywords: ['screening postpartum depression EPDS cutoff score'], question: "How should postpartum women be screened for depression?", response: "We recommend screening all postpartum women for depression when follow-up systems are in place. The most widely used and validated tool is the 10-item Edinburgh Postnatal Depression Scale (EPDS). A cutoff score of ≥11 maximizes sensitivity plus specificity. Screening is typically done once between 4–8 weeks postpartum, though some clinicians screen multiple times in the first year." },
  { id: 2594, category: 'postpartum depression', keywords: ['severe postpartum depression treatment zuranolone SSRIs'], question: "What is recommended as initial treatment for severe postpartum major depression?", response: "For patients with severe postpartum unipolar major depression and no prior history of depression, zuranolone is often preferred as initial treatment due to ease of administration, relatively rapid onset, and good tolerability. For patients with a prior history of successful response to a standard antidepressant, resuming that same medication is recommended. Standard antidepressants remain a reasonable alternative in both scenarios. Most options are compatible with breastfeeding." },
  { id: 2595, category: 'postpartum depression', keywords: ['zuranolone postpartum depression dosing side effects breastfeeding'], question: "How is zuranolone used for postpartum depression?", response: "Zuranolone is given orally at 50 mg each evening for 14 days (with fat-containing food). The dose can be reduced to 40 mg if sedation occurs. It has demonstrated efficacy in randomized trials, with higher remission rates than placebo at day 45. The most common side effect is sedation/somnolence. It is compatible with breastfeeding and has a low relative infant dose." },

  // === Prevention of PPD IDs 2691–2696 ===
  { id: 2691, category: 'postpartum depression prevention', keywords: ['who should receive prevention interventions postpartum depression high risk'], question: "Who should receive interventions to prevent postpartum depression?", response: "Prevention is indicated for euthymic women at increased risk of postpartum major depression, especially those with a prior history of perinatal or non-perinatal depression and/or depressive symptoms during the current pregnancy. These women are at highest risk and should be offered proactive preventive interventions." },
  { id: 2692, category: 'postpartum depression prevention', keywords: ['antidepressant prophylaxis postpartum depression prevention'], question: "When should antidepressants be used to prevent postpartum depression?", response: "For women with a prior history of successful antidepressant treatment who are at high risk, we recommend resuming (or continuing) the previously effective antidepressant, ideally starting in the third trimester. This is often the preferred approach when there is a strong history of response to medication. Most antidepressants are compatible with breastfeeding with appropriate infant monitoring." },
  { id: 2693, category: 'postpartum depression prevention', keywords: ['psychotherapy prevention postpartum depression CBT IPT'], question: "What psychotherapies are effective for preventing postpartum depression?", response: "Cognitive-behavioral therapy (CBT) and interpersonal psychotherapy have the strongest evidence for preventing postpartum depression in high-risk women. Mindfulness-based cognitive therapy is also a reasonable option. These are particularly useful for women without a prior strong response to antidepressants or those who prefer non-medication approaches." },

  // === GAD treatment IDs 2753–2761 ===
  { id: 2753, category: 'generalized anxiety disorder', keywords: ['initial treatment GAD SSRI SNRI first-line pharmacotherapy'], question: "What is recommended as initial pharmacotherapy for generalized anxiety disorder?", response: "For patients who choose pharmacotherapy for GAD, initial treatment with a serotonin reuptake inhibitor (SRI) — either an SSRI or SNRI — is preferred. All SRIs have roughly comparable efficacy. Selection among specific agents is guided by side-effect profile, drug-drug interactions, prior treatment history, and patient preference. Response rates are typically 60–70%." },
  { id: 2754, category: 'generalized anxiety disorder', keywords: ['CBT versus medication GAD how to choose'], question: "How should clinicians choose between CBT and medication for GAD?", response: "Both CBT and SRIs are effective first-line options with roughly equivalent benefits based on indirect comparisons. Choice is individualized: prefer CBT for patients who want to avoid medications or side effects; prefer pharmacotherapy when CBT is unavailable, too burdensome, or the patient cannot participate due to symptom severity. Combination treatment may be superior but most patients start with one modality." },
  { id: 2755, category: 'generalized anxiety disorder', keywords: ['buspirone gabapentin GAD augmentation suboptimal response'], question: "How should suboptimal response to initial SSRI treatment in GAD be managed?", response: "Add CBT if not already done. For partial response, augment the SRI with buspirone (first choice); gabapentin or pregabalin are reasonable next options. For no response, switch to a second SRI. If still unresponsive, trial buspirone, gabapentin, or pregabalin." },
  { id: 2756, category: 'generalized anxiety disorder', keywords: ['duration of treatment GAD how long 12 months maintenance'], question: "How long should pharmacotherapy for GAD be continued after response?", response: "Continue effective pharmacotherapy for at least 12 months after symptom control to reduce risk of relapse. If relapse occurs after discontinuation, extend the treatment duration. After two relapses on taper, consider ongoing maintenance. CBT typically involves 10–15 sessions with encouragement to continue using skills; monthly booster sessions may help maintain gains." },
  { id: 2757, category: 'generalized anxiety disorder', keywords: ['GAD epidemiology prevalence comorbidity female sex'], question: "What is the prevalence and comorbidity pattern of generalized anxiety disorder?", response: "GAD is common, with lifetime prevalence estimates of 5–12% and past-year prevalence of ~2–3% in the US. It is approximately twice as common in females. Comorbidity is very high: ~66% of current cases and ~90% of lifetime cases have at least one other psychiatric disorder. Major depressive disorder is the most frequent comorbidity (39% current, 62% lifetime)." },
  { id: 2758, category: 'generalized anxiety disorder', keywords: ['GAD diagnostic criteria DSM-5 excessive worry 6 months'], question: "What are the DSM-5-TR diagnostic criteria for generalized anxiety disorder?", response: "Diagnosis requires: (A) excessive anxiety/worry occurring more days than not for ≥6 months about multiple events/activities; (B) difficulty controlling the worry; (C) ≥3 of 6 associated symptoms (restlessness, fatigability, concentration problems, irritability, muscle tension, sleep disturbance) present more days than not; (D) clinically significant distress or impairment; (E) not due to substances or another medical condition." },

  // === Social anxiety IDs 2779–2787 ===
  { id: 2779, category: 'social anxiety disorder', keywords: ['social anxiety disorder epidemiology prevalence CBT SSRI'], question: "What is the prevalence and treatment of social anxiety disorder?", response: "SAD is one of the most common psychiatric disorders, with lifetime prevalence in the US estimated at 5–12% and 12-month prevalence of 3–7%. It is more common in women. CBT (particularly with exposure) is the preferred first-line psychotherapy. SSRIs or SNRIs are first-line pharmacologic treatment. Combined treatment may be used when symptoms are severe or there is prominent comorbidity." },
  { id: 2780, category: 'social anxiety disorder', keywords: ['social anxiety disorder DSM-5 criteria fear scrutiny'], question: "What are the clinical features of social anxiety disorder?", response: "Core features include marked fear of scrutiny, embarrassment, or humiliation in social or performance situations. Patients often appear shy or ill at ease in interviews, make poor eye contact, and give brief answers. They experience anticipatory anxiety, physical symptoms (blushing, sweating, trembling, palpitations), and post-event rumination. Fear may be generalized across most social situations or limited to performance situations." },

  // === Panic disorder IDs 2805–2813 ===
  { id: 2805, category: 'panic disorder', keywords: ['panic disorder CBT exposure first-line psychotherapy'], question: "What is the preferred psychotherapy for panic disorder?", response: "Cognitive-behavioral therapy (CBT), particularly with exposure, is the preferred first-line psychotherapy. It has the strongest evidence base among psychotherapies for panic disorder and is effective when delivered by trained clinicians. Remote CBT options (internet, videoconference, bibliotherapy) can also be useful when in-person treatment is unavailable." },
  { id: 2806, category: 'panic disorder', keywords: ['SSRI first-line pharmacotherapy panic disorder dosing low start'], question: "What is recommended as initial pharmacotherapy for panic disorder?", response: "Selective serotonin reuptake inhibitors (SSRIs) are first-line pharmacotherapy. Start at lower doses than for depression (e.g., sertraline 25 mg, escitalopram 5 mg, fluoxetine 5 mg) because patients with panic disorder are sensitive to initial overstimulation. Titrate gradually to the usual therapeutic range. Allow at least 6 weeks at the maximally tolerated dose before judging full response." },
  { id: 2807, category: 'panic disorder', keywords: ['panic disorder duration of treatment 12 months maintenance'], question: "How long should pharmacotherapy for panic disorder be continued?", response: "Continue effective medication for at least 12 months after symptom control is achieved. Many patients benefit from 12–24 months, especially those with more severe initial illness, comorbidity (depression, agoraphobia), residual symptoms, or ongoing stressors. Relapse risk after discontinuation is substantial (25–50%). CBT gains are often more durable; booster sessions can help maintain benefits." },

  // === PTSD management IDs 2814–2840 ===
  { id: 2814, category: 'ptsd', keywords: ['PTSD trauma-focused psychotherapy first-line CPT prolonged exposure EMDR'], question: "What is the preferred first-line treatment for most adults with PTSD?", response: "Trauma-focused psychotherapy that includes exposure (e.g., prolonged exposure, cognitive processing therapy, written exposure) is preferred first-line over medication or other therapies for most adults with PTSD. These approaches have the strongest evidence base. Choice among trauma-focused therapies is guided by patient presentation, preference, and therapist expertise." },
  { id: 2815, category: 'ptsd', keywords: ['SSRI SNRI PTSD pharmacotherapy when to use'], question: "When and how are SSRIs or SNRIs used in PTSD?", response: "SSRIs (e.g., sertraline, paroxetine, escitalopram) or SNRIs (e.g., venlafaxine ER) are appropriate first-line alternatives to trauma-focused therapy, especially when comorbid depression or other anxiety disorders are prominent or when patients prefer medication. Start at low doses and titrate gradually. Allow a full therapeutic trial of at least 6–8 weeks at the maximally tolerated dose within the therapeutic range before judging response." },
  { id: 2816, category: 'ptsd', keywords: ['prazosin nightmares sleep PTSD treatment'], question: "How is prazosin used in PTSD with prominent sleep disturbance or nightmares?", response: "Prazosin is recommended for significant sleep disturbance, especially nightmares. It can be used as monotherapy, combined with trauma-focused therapy, or as augmentation of an SSRI/SNRI. Start at 1 mg 30–60 min before bedtime and titrate gradually to 3–15 mg. Avoid abrupt discontinuation (risk of rebound hypertension)." },
  { id: 2817, category: 'ptsd', keywords: ['PTSD epidemiology prevalence risk factors female sex twice as common'], question: "What is the prevalence of PTSD and which trauma types are most strongly associated with it?", response: "Lifetime prevalence in the US/Canada is approximately 6–9%, with 12-month prevalence of 3.5–4.7%. Highest conditional risk follows sexual assault/relationship violence, followed by interpersonal-network traumas and interpersonal violence. Females have roughly twice the risk of males after adjusting for exposure." },
  { id: 2818, category: 'ptsd', keywords: ['PTSD DSM-5 clinical features cardinal symptoms clusters'], question: "What are the cardinal symptom clusters of PTSD?", response: "Criterion A: Exposure to actual/threatened death, serious injury, or sexual violence. B: Intrusion symptoms (intrusive memories, nightmares, flashbacks, distress at reminders). C: Avoidance of trauma-related thoughts, feelings, or external reminders. D: Negative alterations in cognitions and mood. E: Arousal and reactivity changes (irritability/aggression, recklessness, hypervigilance, exaggerated startle, concentration problems, sleep disturbance). Symptoms must persist >1 month and cause impairment." },

  // === OCD treatment IDs 2886–2903 ===
  { id: 2886, category: 'ocd', keywords: ['OCD initial treatment CBT ERP SSRI choice'], question: "How should clinicians choose initial treatment for OCD in adults?", response: "Choice depends on symptom severity, suicidality, comorbidities, prior treatment response, ability/willingness to engage in CBT/ERP, availability of CBT/ERP, and patient preference. For mild-moderate symptoms without suicidality: CBT/ERP monotherapy is often preferred. For severe symptoms (CGI ≥5 or Y-BOCS 30–40) or suicidality: start combined CBT/ERP + pharmacotherapy. For patients unwilling/unable to do CBT/ERP: start SSRI." },
  { id: 2887, category: 'ocd', keywords: ['SSRI first-line OCD dosing supratherapeutic'], question: "What is first-line pharmacotherapy for OCD and how is it dosed?", response: "Selective serotonin reuptake inhibitors (SSRIs) are first-line pharmacotherapy. Start at lowest recommended dose and titrate gradually. Target doses are often higher than for depression. Therapeutic trial = at least 12 weeks total, with ≥6 weeks at target dose. Supratherapeutic dosing (e.g., fluoxetine up to 120 mg) can be tried if partial response and tolerated." },
  { id: 2888, category: 'ocd', keywords: ['antipsychotic augmentation partial response OCD aripiprazole risperidone'], question: "When and how is antipsychotic augmentation used in OCD?", response: "For partial responders to adequate SSRI (or clomipramine) treatment, second-generation antipsychotics are a first-line augmentation option with the strongest supporting evidence. Start low and titrate slowly (e.g., aripiprazole 1–2 mg → 5–10 mg; risperidone 0.5 mg → 2–4 mg). Continue effective augmentation for ≥12 months before attempting slow taper." },
  { id: 2889, category: 'ocd', keywords: ['maintenance OCD medication how long 2-3 years'], question: "How long should effective OCD medication be continued?", response: "Continue effective pharmacotherapy for at least 2–3 years in most patients who achieve remission. OCD is often chronic; even initial responders have substantial relapse risk upon discontinuation. Taper slowly (e.g., up to 20–25% every 1–2 months) while monitoring closely. Patients who completed CBT/ERP have lower relapse risk after medication discontinuation." },
  { id: 2890, category: 'ocd', keywords: ['OCD epidemiology prevalence lifetime 1-1.5 percent comorbidity'], question: "What is the prevalence of OCD and how common are comorbidities?", response: "Lifetime prevalence is approximately 1–1.5% worldwide and 2.3% in the US, with slightly higher rates in adult women than men. OCD is highly comorbid: ~76% have a lifetime anxiety disorder, ~63% a mood disorder (most often MDD), and substantial rates of tic disorders and OCPD. Comorbidity (especially depression, tics, OCPD) is associated with lower treatment response rates." },
  { id: 2891, category: 'ocd', keywords: ['perinatal OCD prevalence intrusive thoughts harm infant'], question: "How common is OCD and intrusive thoughts in pregnancy and postpartum?", response: "Full OCD is elevated in the perinatal period (roughly 2–4% or higher). Intrusive thoughts (especially of accidental harm to the baby) are extremely common in new mothers — reported in up to 100% in some studies, including women without psychiatric illness. Many women with perinatal OCD symptoms also have comorbid depression (~70% in postpartum OCD) or anxiety." },
  { id: 2892, category: 'ocd', keywords: ['perinatal OCD treatment CBT ERP SSRI sertraline'], question: "What is the recommended treatment for OCD in pregnancy and postpartum?", response: "CBT incorporating exposure and response prevention (ERP) is first-line for most patients across severity levels. For severe symptoms, significant functional impairment, or comorbid depression/anxiety, combine CBT/ERP with an SSRI. Sertraline is often preferred when starting a new medication (good safety data in pregnancy and breastfeeding)." },

  // === BDD IDs 2913–2921 ===
  { id: 2913, category: 'bdd', keywords: ['BDD body dysmorphic disorder definition preoccupation appearance'], question: "What is body dysmorphic disorder?", response: "BDD is characterized by preoccupation with one or more nonexistent or slight defects in physical appearance (thoughts occupy ≥1 hour/day total), repetitive behaviors or mental acts performed in response to the preoccupations, and clinically significant distress or impairment. It is common but usually underrecognized in clinical settings (2–3% general population; up to 13–20% in dermatology and cosmetic surgery settings)." },
  { id: 2914, category: 'bdd', keywords: ['BDD suicidality elevated risk attempts lifetime'], question: "What is the suicidality risk in BDD?", response: "Suicidality is markedly elevated in BDD. Meta-analyses show ~53% lifetime suicidal ideation and ~24% lifetime suicide attempts. Individuals with BDD have 4–7 times higher odds of suicidal ideation and 2–6 times higher odds of attempts compared with controls. Risk factors include greater BDD severity, early onset, poor functioning, and multiple comorbidities." },
  { id: 2915, category: 'bdd', keywords: ['BDD cosmetic procedures outcomes do not help'], question: "What happens when patients with BDD receive cosmetic procedures?", response: "Most patients with BDD (64–71% in studies) seek and obtain dermatologic or surgical cosmetic treatments. Outcomes are poor: in one study of 419 procedures, 91% resulted in no change in BDD symptoms and 5% led to worsening. Symptoms rarely improve and often intensify. Cosmetic procedures do not treat the underlying body image distortion." },

  // === Anorexia nervosa IDs 2996–3005 ===
  { id: 2996, category: 'anorexia', keywords: ['anorexia nervosa core features weight restriction fear'], question: "What are the core clinical features of anorexia nervosa?", response: "Anorexia nervosa is defined by three core features: (1) persistent restriction of energy intake leading to abnormally low body weight; (2) intense fear of gaining weight or becoming fat, or persistent behavior that prevents weight gain; and (3) distorted perception of body weight/shape, undue influence of weight/shape on self-worth, or denial of the medical seriousness of low weight." },
  { id: 2997, category: 'anorexia', keywords: ['anorexia nervosa comorbidity anxiety OCD depression eating disorders'], question: "What psychiatric disorders commonly co-occur with anorexia nervosa?", response: "Lifetime psychiatric comorbidity is very common. Most patients have at least one comorbid mental disorder; many have three or more. Frequent comorbidities include anxiety disorders, OCD, body dysmorphic disorder, depressive disorders (especially major depression), PTSD, substance use disorders, and personality disorders. Many comorbidities (particularly depression) are secondary to starvation and improve with weight restoration." },
  { id: 2998, category: 'anorexia', keywords: ['anorexia nervosa suicide risk attempts mortality'], question: "What is the suicide risk in anorexia nervosa?", response: "Suicidality is markedly elevated. Lifetime suicide attempt rates are approximately 10–25%. Suicide deaths are roughly 5–6 times higher than the general population. Risk factors include comorbid substance use disorders, history of sexual abuse, and having a sibling with an eating disorder. All patients require careful suicide risk assessment." },

  // === Binge eating disorder IDs 3006–3015 ===
  { id: 3006, category: 'binge-eating', keywords: ['binge eating disorder definition DSM-5 loss of control episodes'], question: "What is binge eating disorder?", response: "Binge eating disorder involves recurrent episodes of eating an unusually large amount of food in a discrete period (e.g., 2 hours) with a sense of loss of control, occurring on average at least once per week for 3 months. Episodes are associated with distress and often with eating rapidly, until uncomfortably full, when not hungry, alone due to embarrassment, or with subsequent guilt/shame. Unlike bulimia nervosa, there are no regular compensatory behaviors." },
  { id: 3007, category: 'binge-eating', keywords: ['binge eating disorder first-line treatment CBT psychotherapy'], question: "What is the first-line treatment for binge eating disorder?", response: "Psychotherapy, particularly cognitive-behavioral therapy (CBT) adapted for binge eating disorder, is first-line treatment. CBT has the strongest evidence base and can be delivered in individual, group, or guided self-help formats. It focuses on normalizing eating patterns, reducing binge episodes, addressing shape/weight concerns, and building coping skills. Interpersonal psychotherapy is a reasonable alternative with comparable efficacy for many patients." },
  { id: 3008, category: 'binge-eating', keywords: ['binge eating disorder medication SSRI topiramate lisdexamfetamine'], question: "What is the role of medication in treating binge eating disorder?", response: "Medication is generally second-line after psychotherapy. Selective serotonin reuptake inhibitors (SSRIs) are the preferred pharmacologic option due to modest efficacy and good tolerability. For patients who do not respond to SSRIs, topiramate or lisdexamfetamine can be considered, though both have more side effects. Medication alone is less effective than CBT." },

  // === Eating disorders in pregnancy IDs 3016–3025 ===
  { id: 3016, category: 'eating-pregnancy', keywords: ['eating disorders pregnancy screening warning signs management'], question: "How should eating disorders be managed during pregnancy?", response: "Pregnant women with eating disorders should be managed by a coordinated team (psychiatrist, dietitian, obstetrician). Key elements include: regular communication among providers; close monitoring of weight gain and fetal growth; nutritional guidance focused on eating for the baby; screening for comorbid depression/anxiety; and medication review for safety in pregnancy. Severe cases require referral to a specialized eating disorders program." },
  { id: 3017, category: 'eating-pregnancy', keywords: ['anorexia nervosa pregnancy outcomes gestational weight gain'], question: "What are key considerations for anorexia nervosa during pregnancy?", response: "Gestational weight gain is inadequate in ~20% of cases. Average birth weight is modestly lower in offspring of mothers with anorexia nervosa. Many women experience symptom improvement during pregnancy, but relapse is common postpartum. Coordinated care with close monitoring of weight gain and nutrition is essential." },
  { id: 3018, category: 'eating-pregnancy', keywords: ['bulimia nervosa pregnancy outcomes relapse postpartum'], question: "What are key considerations for bulimia nervosa during pregnancy?", response: "Bulimia nervosa is associated with higher rates of miscarriage. It typically remits during pregnancy in many women (~74% in one study), but relapse or persistence is common postpartum. Hyperemesis gravidarum may have a bidirectional relationship with bulimia nervosa." },
  { id: 3019, category: 'eating-pregnancy', keywords: ['binge eating disorder pregnancy prevalence outcomes excessive weight gain'], question: "What are key considerations for binge eating disorder during pregnancy?", response: "Prevalence during pregnancy is higher (~5%), with many cases representing new onset. Gestational weight gain is typically excessive (65% in one study). Binge eating disorder may increase miscarriage risk. It often persists during pregnancy (~61% in one study) and frequently continues or recurs postpartum." },

  // === Medical complications of bulimia IDs 3026–3035 ===
  { id: 3026, category: 'bulimia', keywords: ['bulimia nervosa medical evaluation electrolytes hypokalemia'], question: "What medical evaluation is recommended for patients with bulimia nervosa?", response: "All patients with bulimia nervosa should receive: serum electrolytes, BUN, creatinine, CBC with differential, liver function tests, and urinalysis. Severely ill patients also need calcium, magnesium, phosphorus, and an ECG. A pregnancy test is required for all females. The most common abnormalities are hypokalemia, hypochloremia, hyponatremia, and metabolic alkalosis from self-induced vomiting or laxative/diuretic misuse." },
  { id: 3027, category: 'bulimia', keywords: ['bulimia nervosa dental complications enamel erosion Russell sign'], question: "What dental and skin findings are seen in bulimia nervosa?", response: "Dental complications from repeated vomiting include enamel erosion (especially lingual surfaces of maxillary teeth), tooth sensitivity, caries, and gum disease. Patients should rinse with water or baking soda after vomiting, wait 30+ minutes before brushing, and use fluoride. A nearly pathognomonic skin finding is Russell's sign — calluses or scarring on the dorsum of the hand from inducing vomiting." },
  { id: 3028, category: 'bulimia', keywords: ['bulimia nervosa cardiovascular complications QT prolongation arrhythmia'], question: "What cardiovascular risks are associated with bulimia nervosa?", response: "Short-term complications include orthostasis, tachycardia, palpitations, edema, ECG changes (QT prolongation, ST depression), and arrhythmias. Longer-term registry data suggest patients hospitalized for bulimia nervosa have significantly elevated risk of future cardiovascular disease. QT-prolonging medications should be avoided when QT prolongation is present." },

  // === Personality disorders IDs 3036–3039 ===
  { id: 3036, category: 'personality', keywords: ['personality disorder definition inflexible maladaptive traits impairment'], question: "What is a personality disorder?", response: "A personality disorder is diagnosed when personality traits are inflexible and maladaptive across many situations, causing significant distress or impairment in social, occupational, or role functioning. The pattern is stable, long-standing (usually traceable to adolescence or early adulthood), and not better explained by another mental disorder, substance use, or medical condition." },
  { id: 3037, category: 'personality', keywords: ['personality disorder clusters A B C classification DSM'], question: "How are personality disorders classified into clusters?", response: "DSM-5-TR groups the 10 personality disorders into three clusters: Cluster A (odd/eccentric: Paranoid, Schizoid, Schizotypal); Cluster B (dramatic/emotional/erratic: Antisocial, Borderline, Histrionic, Narcissistic); Cluster C (anxious/fearful: Avoidant, Dependent, Obsessive-Compulsive). These clusters are descriptive only and do not imply etiology or treatment implications." },

  // === Chapter 24: Forensic issues (IDs 4186–4215) ===
  { id: 4186, category: 'chapter24', keywords: ['forensic issues perinatal psychiatry overview filicide'], question: "What forensic psychiatry topics are relevant in the perinatal period?", response: "Perinatal forensic psychiatry covers maternal filicide, infanticide, neonaticide, capacity assessments, civil commitment, and legal/ethical considerations for pregnant and postpartum women with mental illness. Risk factors include severe postpartum psychosis, untreated severe depression, substance use, and prior history of violence or child abuse." },
  { id: 4187, category: 'chapter24', keywords: ['postpartum psychosis filicide risk link emergency'], question: "What is the link between postpartum psychosis and filicide?", response: "Postpartum psychosis carries a significant risk of infanticide; early recognition, immediate hospitalization, and safety planning are essential when psychotic symptoms are present." },
  { id: 4188, category: 'chapter24', keywords: ['postpartum psychosis filicide prevention hospitalization safety'], question: "How can filicide be prevented?", response: "Early recognition of postpartum psychosis, immediate hospitalization, and family involvement are key preventive measures. CycleMind includes optional psychosis and severe depression screeners with immediate crisis resource buttons and clinician alerts for any endorsement of harm thoughts." },
  { id: 4189, category: 'chapter24', keywords: ['capacity assessment pregnancy mental illness decision making'], question: "What capacity assessments are discussed in perinatal forensic psychiatry?", response: "Capacity to consent to treatment, refuse care, or make decisions about pregnancy continuation requires careful evaluation when psychiatric illness is present. Civil commitment may be necessary when a pregnant or postpartum woman poses imminent danger to herself or her infant due to severe mental illness." },
  { id: 4190, category: 'chapter24', keywords: ['neonaticide risk factors denial of pregnancy psychosis isolation'], question: "What is neonaticide and its risk factors?", response: "Neonaticide (killing of an infant within 24 hours of birth) is often linked to denial of pregnancy, untreated psychosis, or severe social isolation." },
  { id: 4191, category: 'chapter24', keywords: ['infanticide risk assessment factors psychiatric evaluation'], question: "How is infanticide risk assessed?", response: "Key risk factors include psychosis, depression, substance use, and prior violence. Thorough safety planning and hospitalization are needed when indicated. Chapter 24 of the Women's Reproductive Mental Health textbook reviews key risk factors and stresses the need for thorough safety planning and hospitalization when indicated." },
  { id: 4192, category: 'chapter24', keywords: ['legal issues pregnancy mental illness custody involuntary treatment'], question: "What legal issues arise with psychiatric illness in pregnancy?", response: "Legal issues include involuntary treatment, guardianship, child protective services involvement, and capacity to make medical decisions during pregnancy and postpartum. Collaboration between reproductive psychiatrists, forensic experts, obstetricians, and legal professionals is essential for high-risk cases." },
  { id: 4193, category: 'chapter24', keywords: ['perinatal mental illness legal rights patients'], question: "What legal rights are important for pregnant and postpartum women with mental illness?", response: "Women with mental illness have rights regarding treatment refusal, civil commitment, and child custody proceedings. All care must balance safety with respect for patient autonomy and legal rights." },

  // === Appendix: Psychotropic medications pregnancy/lactation (IDs 4216–4245) ===
  { id: 4216, category: 'appendix', keywords: ['psychotropic medications pregnancy lactation safety overview'], question: "What does the psychotropic medication safety appendix for pregnancy and lactation cover?", response: "The Appendix provides a concise, up-to-date summary of pregnancy and lactation safety data for all major classes of psychotropic medications (antidepressants, mood stabilizers, antipsychotics, anxiolytics, stimulants, etc.). All medication decisions during pregnancy and lactation require individualized, collaborative risk-benefit analysis involving the patient, psychiatrist, and obstetrician." },
  { id: 4217, category: 'appendix', keywords: ['SSRIs pregnancy lactation safety sertraline breastfeeding'], question: "What are the considerations for SSRIs in pregnancy and lactation?", response: "SSRIs (especially sertraline) have the most reassuring safety data. Small increased risk of specific malformations is outweighed by risks of untreated illness for most patients. Sertraline, paroxetine, and nortriptyline have the lowest infant exposure and are generally preferred during breastfeeding." },
  { id: 4218, category: 'appendix', keywords: ['lithium pregnancy lactation Ebstein anomaly renal monitoring'], question: "What are the considerations for lithium in pregnancy and lactation?", response: "Lithium requires close monitoring due to teratogenic risk (Ebstein's anomaly) and changes in renal clearance during pregnancy. Breastfeeding is possible with infant lithium, renal, and thyroid function monitoring. Lithium is recommended for maintenance treatment in patients with bipolar disorder who remain at elevated suicide risk." },
  { id: 4219, category: 'appendix', keywords: ['atypical antipsychotics pregnancy metabolic monitoring neonatal'], question: "What data exist for atypical antipsychotics in pregnancy?", response: "Most atypical antipsychotics have reassuring data for major malformations; metabolic monitoring and neonatal observation for withdrawal are recommended. Second-generation antipsychotics such as olanzapine, quetiapine, and risperidone have the most safety data for use in pregnancy." },
  { id: 4220, category: 'appendix', keywords: ['lamotrigine pregnancy lactation dose adjustment breastfeeding'], question: "What are the considerations for lamotrigine in pregnancy and lactation?", response: "Lamotrigine clearance increases significantly in pregnancy, requiring dose adjustment; it is generally considered compatible with breastfeeding. Variable infant levels (20–50% of maternal) have been reported; no serious adverse events including SJS have been reported, but pediatrician consultation and monitoring are advised." },
  { id: 4221, category: 'appendix', keywords: ['valproate pregnancy avoid teratogen neural tube defects'], question: "Why is valproate generally avoided in pregnancy?", response: "Valproate has high teratogenic risk (neural tube defects, cognitive teratogenicity) and is typically avoided in women of reproductive age unless no safer alternative exists. Carbamazepine and valproic acid require caution with recommended infant liver function monitoring due to rare hepatotoxicity reports." },
  { id: 4222, category: 'appendix', keywords: ['benzodiazepines perinatal neonatal sedation withdrawal short duration'], question: "What are the considerations for benzodiazepines in the perinatal period?", response: "Short-term, low-dose use may be necessary for severe anxiety or agitation; risks include neonatal sedation and withdrawal. Commonly used benzodiazepines (lorazepam, clonazepam) appear at low levels in breast milk. Adverse effects are rarely reported but may include infant sedation or feeding difficulties, especially with higher doses or longer-acting agents." },
  { id: 4223, category: 'appendix', keywords: ['stimulants ADHD pregnancy lactation methylphenidate amphetamine'], question: "What data exist for ADHD stimulants in pregnancy and lactation?", response: "Stimulants have relatively reassuring safety data; monitoring for fetal growth and neonatal withdrawal is recommended when used during pregnancy or lactation. Methylphenidate and amphetamines generally appear at very low levels in milk with relative infant doses typically <1%." },
  { id: 4224, category: 'appendix', keywords: ['psychiatric medication breastfeeding safety RID relative infant dose'], question: "How is the safety of psychiatric medications during breastfeeding determined?", response: "Safety is assessed using multiple factors: measured drug levels in maternal plasma, breast milk, and infant plasma; milk-to-plasma (M/P) ratio (lower is better; <1 favorable); relative infant dose (RID; generally <10% of maternal weight-adjusted dose is acceptable); published case series and adverse event reports; and expert consensus/guidelines (ACOG, AAFP, LactMed). The risks of untreated maternal illness far outweigh theoretical risks of medication via breast milk for most agents." },
  { id: 4225, category: 'appendix', keywords: ['antipsychotics breastfeeding safety olanzapine quetiapine aripiprazole lactation'], question: "What is known about antipsychotic use during breastfeeding?", response: "Olanzapine is the best-studied atypical antipsychotic; low milk/serum levels and rare mild sedation at doses up to 20 mg/day. Quetiapine (up to 400 mg) yields low RID (<1%). Aripiprazole can significantly reduce prolactin and has been associated with lactation failure/insufficient milk supply — monitor feeding and weight gain closely. Clozapine is contraindicated (agranulocytosis risk)." },
  { id: 4226, category: 'appendix', keywords: ['mood stabilizers breastfeeding lithium lamotrigine valproate monitoring'], question: "What are the considerations for mood stabilizers during breastfeeding?", response: "Lithium transfers significantly into milk (infant levels can reach 1/3–1/2 of maternal levels); close monitoring of infant lithium, renal, and thyroid function is required. Lamotrigine shows variable infant levels (20–50% of maternal); no serious adverse events reported, but pediatrician consultation and monitoring are advised. Carbamazepine and valproic acid require caution with recommended infant liver function monitoring." },
  { id: 4227, category: 'appendix', keywords: ['clinical decision making psychiatric meds breastfeeding guidelines priorities'], question: "What principles guide clinical decision-making for psychiatric medications while breastfeeding?", response: "Prioritize continuation of effective pregnancy medications postpartum to minimize relapse risk. Individualize based on severity of maternal illness, prior response, desire/ability to breastfeed, and medication-specific data. Weigh benefits of maternal stability and breastfeeding against potential infant exposure. Consult LactMed for latest data. For severe illness, reducing or supplementing breastfeeding may be appropriate to protect maternal health. Shared decision-making with perinatal psychiatry and pediatrics is ideal." },
  { id: 4228, category: 'appendix', keywords: ['antidepressants breastfeeding SSRIs TCAs compatible low risk'], question: "Are antidepressants safe during breastfeeding?", response: "SSRIs (especially sertraline and paroxetine) and tricyclic antidepressants are among the best-studied and most reassuring options, with low breast milk concentrations and typically undetectable or very low infant serum levels. Adverse events are rare. Recent guidelines state there is little evidence of significant harm from antidepressant exposure via breast milk. The risks of untreated maternal depression far outweigh theoretical risks of medication." },
  { id: 4229, category: 'appendix', keywords: ['ADHD medications breastfeeding methylphenidate amphetamines compatibility'], question: "Are ADHD medications compatible with breastfeeding?", response: "Methylphenidate and amphetamines generally appear at very low levels in milk with relative infant doses typically <1%. Most reports show no adverse events or developmental concerns in exposed infants. Use lowest effective dose and immediate-release formulations when possible; time doses to minimize infant exposure. Monitor for irritability, poor feeding, sleep changes, or growth concerns." },
  { id: 4230, category: 'appendix', keywords: ['psychotropic medications pregnancy key takeaway individualized collaborative'], question: "What is the core message of the psychotropic medication safety appendix?", response: "Psychotropic medication decisions in pregnancy and lactation require individualized, collaborative decision-making that balances maternal mental health needs with fetal/infant safety. All medication decisions should be made with the patient's obstetric and psychiatric providers. Never stop or change psychiatric medications without medical advice." },
  { id: 4231, category: 'appendix', keywords: ['CycleMind medication tracking pregnancy lactation safety cards'], question: "How should CycleMind use psychotropic medication safety information?", response: "CycleMind can display concise, referenced safety summaries for common psychotropics with strong disclaimers and direct links to the user's clinician for individualized decisions. All medication logs are fully optional, encrypted, and user-controlled with no automatic sharing. Luna must always state she is not a prescribing clinician and cannot recommend or adjust any medication. All decisions require consultation with a perinatal psychiatrist or OB/GYN." },

  // === Additional obesity/pregnancy/menopause summary entries ===
  { id: 3266, category: 'pregnancy', keywords: ['obesity pregnancy risks maternal perinatal complications preeclampsia'], question: "What are the key maternal and perinatal risks associated with obesity in pregnancy?", response: "Pregnant people with obesity (prepregnancy BMI ≥30) have higher risks of gestational diabetes, preeclampsia/gestational hypertension, preterm birth, postterm pregnancy, cesarean birth, labor induction failure, postpartum hemorrhage, VTE, wound infection, and postpartum depression. Offspring risks include congenital anomalies, perinatal mortality/stillbirth, LGA/macrosomia, and childhood obesity. Most people with obesity have normal pregnancies, but risks increase with higher BMI classes and excessive gestational weight gain." },
  { id: 3267, category: 'pregnancy', keywords: ['gestational weight gain recommendations IOM NAM BMI targets'], question: "What are the gestational weight gain recommendations?", response: "The 2009 Institute of Medicine (now NAM) recommendations for total gestational weight gain in singleton pregnancies are: Underweight (<18.5 kg/m²): 28–40 lb; Normal (18.5–24.9): 25–35 lb; Overweight (25–29.9): 15–25 lb; Obese (≥30): 11–20 lb. Your provider will monitor your pattern and discuss what's healthy for you and your baby." },
  { id: 3268, category: 'pregnancy', keywords: ['GLP-1 semaglutide tirzepatide preconception pregnancy stop when'], question: "How should GLP-1 medications be managed around pregnancy?", response: "GLP-1-based therapies (e.g., semaglutide, tirzepatide) should ideally be stopped at least 2 months before conception due to limited human safety data and potential fetal risks seen in animal studies. Stopping them can lead to weight regain. Patients should be counseled about this possibility and supported with nutrition and lifestyle strategies. All medication decisions belong with the prescribing clinician." },

];