// RAG Entries: Pregnancy, Postpartum & Birth Control Clinical (from MissingRAGData.docx)
// Covers: Prenatal care, nutrition, genetic screening, ectopic pregnancy, smoking in pregnancy,
// vaccines in pregnancy, high-risk pregnancy, breech, postpartum hemorrhage, postpartum physiology,
// menstrual suppression, birth control deep dive, depression in pregnancy

export const ragEntriesPregnancy = [

  // === Initial Prenatal Assessment (IDs 1085–1100) ===
  { id: 1085, category: 'pregnancy', keywords: ['when to start prenatal care', 'first prenatal visit timing'], question: "When should I start prenatal care?", response: "Ideally, you should begin prenatal care in the first trimester, preferably by 10 weeks of gestation. This allows accurate dating, early baseline testing, and timely screening. Starting early gives you and your baby the best chance for a healthy pregnancy and delivery." },
  { id: 1086, category: 'pregnancy', keywords: ['what happens at first prenatal visit'], question: "What should I expect at my first prenatal visit?", response: "Your first visit usually includes a detailed medical, obstetric, and family history, physical exam, confirmation of pregnancy, calculation of your due date, baseline measurements (weight, blood pressure, BMI), and a standard set of lab tests. You'll also discuss screening options for genetic conditions, infections, and mental health, plus receive guidance on nutrition, weight gain, and what to expect." },
  { id: 1087, category: 'pregnancy', keywords: ['why is early prenatal care important'], question: "Why is it important to start prenatal care early?", response: "Early care helps establish accurate gestational age, identifies risks early, allows timely screening and interventions, and gives you the best chance to prevent or manage complications. It also lets your care team support you with nutrition, mental health, and any social needs from the beginning." },
  { id: 1088, category: 'pregnancy', keywords: ['depression screening in pregnancy'], question: "Will I be screened for depression or anxiety during pregnancy?", response: "Yes. Most prenatal providers screen for depression and anxiety at the first visit, later in pregnancy, and postpartum using validated tools like the PHQ-9 or Edinburgh Postnatal Depression Scale. Pregnancy and the postpartum period are high-risk times for mood changes, so early identification and support are important." },
  { id: 1089, category: 'pregnancy', keywords: ['weight gain in pregnancy by BMI'], question: "How much weight should I gain during pregnancy?", response: "Recommended total weight gain depends on your pre-pregnancy BMI. For example, if you have a normal BMI (18.5–24.9), the goal is usually 25–35 pounds. If you're underweight, more gain is recommended; if you have obesity, less total gain is advised. Your provider will discuss a personalized target with you." },
  { id: 1090, category: 'pregnancy', keywords: ['standard blood tests at first prenatal visit'], question: "What blood tests are done at the first prenatal visit?", response: "Common tests include blood type and Rh factor, antibody screen, complete blood count (for anemia), rubella and varicella immunity, hepatitis B and C, HIV, syphilis, and often chlamydia. You may also have a urine culture and screening for other conditions based on your history and risk factors." },
  { id: 1091, category: 'pregnancy', keywords: ['genetic screening in pregnancy options'], question: "What genetic screening or testing options are available in early pregnancy?", response: "You'll be offered options to screen or test for chromosomal conditions like Down syndrome. Common choices include cell-free DNA screening (from a maternal blood draw) or traditional serum screening with or without nuchal translucency ultrasound. You can also choose diagnostic testing (CVS or amniocentesis) if you prefer definitive results." },
  { id: 1092, category: 'pregnancy', keywords: ['ultrasound at first prenatal visit'], question: "Will I have an ultrasound at my first prenatal visit?", response: "Often yes — especially if your dates are uncertain, you have bleeding, pain, or risk factors. An early ultrasound confirms the pregnancy location, checks for heartbeat, determines the number of babies, and gives the most accurate due date. A full anatomy scan usually happens later, around 18–20 weeks." },
  { id: 1093, category: 'pregnancy', keywords: ['intimate partner violence screening pregnancy'], question: "Will my prenatal provider ask about safety or domestic violence?", response: "Yes. Routine screening for intimate partner violence is recommended at prenatal visits because pregnancy can increase risk. Your provider should ask in a private, nonjudgmental way and connect you with resources if needed. This is done to help keep you and your baby safe." },
  { id: 1094, category: 'pregnancy', keywords: ['substance use screening in pregnancy'], question: "Will I be asked about alcohol, drugs, or smoking during pregnancy?", response: "Yes. Your provider will ask about tobacco, alcohol, cannabis, and other substance use using validated questions. Being honest helps them support you and reduce risks to you and your baby. Many people need extra help to quit or cut back, and nonjudgmental support is available." },
  { id: 1095, category: 'pregnancy', keywords: ['benefits of prenatal care'], question: "Does going to prenatal care really make a difference?", response: "Yes. Good prenatal care is associated with earlier detection of problems, better management of conditions like high blood pressure or diabetes, reduced risk of certain complications, and improved outcomes for both mother and baby. It also provides education, emotional support, and a chance to build a trusting relationship with your care team." },
  { id: 1096, category: 'pregnancy', keywords: ['group prenatal care vs traditional'], question: "What is group prenatal care and is it a good option?", response: "Group prenatal care brings together people with similar due dates for longer visits that combine medical check-ins with education and peer support. Many people find it empowering and appreciate the community. Outcomes are generally as good as or better than traditional one-on-one care." },
  { id: 1097, category: 'pregnancy', keywords: ['when to see maternal fetal medicine'], question: "When would I need to see a high-risk pregnancy specialist (MFM)?", response: "You may be referred to a Maternal-Fetal Medicine specialist if you have chronic medical conditions (like diabetes, hypertension, or autoimmune disease), a history of pregnancy complications, or if problems develop during your current pregnancy. Many people see both their regular OB and an MFM for collaborative care." },
  { id: 1098, category: 'pregnancy', keywords: ['trauma informed prenatal care'], question: "What if I have a history of trauma — will that be considered in my prenatal care?", response: "Good prenatal care should be trauma-informed. This means your provider should ask sensitively about past trauma, respect your boundaries, explain procedures clearly, and offer choices whenever possible. If you have a history of sexual trauma or abuse, let your provider know so they can adapt care to help you feel safer and more in control." },
  { id: 1099, category: 'pregnancy', keywords: ['carrier screening in pregnancy'], question: "What is carrier screening and should I have it?", response: "Carrier screening checks whether you carry genes for certain inherited conditions (like cystic fibrosis, spinal muscular atrophy, or hemoglobin disorders). It's usually done with a blood or saliva test. Many people choose expanded carrier screening so they can understand risks and options before or early in pregnancy." },
  { id: 1100, category: 'pregnancy', keywords: ['infectious disease screening pregnancy'], question: "Why am I being tested for so many infections at my first prenatal visit?", response: "Certain infections (HIV, syphilis, hepatitis B and C, chlamydia, etc.) can affect your pregnancy and baby if untreated. Early detection allows treatment that protects both of you. Screening is routine because many of these infections have no symptoms, and treating them early makes a big difference in outcomes." },

  // === Early Pregnancy Diagnosis (IDs 1101–1116) ===
  { id: 1101, category: 'pregnancy', keywords: ['early signs of pregnancy', 'first symptoms of pregnancy'], question: "What are the earliest signs and symptoms of pregnancy?", response: "The most common early signs include a missed period, nausea (with or without vomiting), breast tenderness or enlargement, increased urinary frequency, and fatigue. Some people also notice mild cramping, bloating, food cravings or aversions, mood changes, or nasal congestion. Symptoms often start around 5–6 weeks." },
  { id: 1102, category: 'pregnancy', keywords: ['when can pregnancy be detected by hCG'], question: "How soon after conception can pregnancy be detected with a test?", response: "hCG can sometimes be detected in blood as early as 6–8 days after ovulation, but most people won't get a positive test until closer to or after their expected period. Urine tests are usually positive about a week after a missed period. Testing too early is the most common reason for a false-negative result." },
  { id: 1103, category: 'pregnancy', keywords: ['how does hCG level change in early pregnancy'], question: "How fast should hCG levels rise in early pregnancy?", response: "In a healthy early pregnancy, hCG levels typically double every 29 to 53 hours during the first month after implantation. Levels peak around 8–10 weeks and then gradually decline. A slower rise can suggest an abnormal pregnancy (such as ectopic or miscarriage), but there is a wide normal range." },
  { id: 1104, category: 'pregnancy', keywords: ['when can fetal heartbeat be heard or seen'], question: "When can a fetal heartbeat be detected in early pregnancy?", response: "With a transvaginal ultrasound, cardiac activity can often be seen around 5.5–6.5 weeks. A handheld Doppler device can usually pick up the heartbeat by 10–12 weeks. Seeing or hearing the heartbeat is very reassuring but timing varies." },
  { id: 1105, category: 'pregnancy', keywords: ['home pregnancy test false negative causes'], question: "Why might a home pregnancy test be negative even if I'm pregnant?", response: "The most common reason is testing too early — before there's enough hCG in your urine. Other causes include very dilute urine, using the test incorrectly, or (rarely) the 'hook effect' with extremely high hCG levels. If you still suspect pregnancy, retest in a few days or get a serum test." },
  { id: 1106, category: 'pregnancy', keywords: ['false positive pregnancy test causes'], question: "Can you get a false-positive pregnancy test?", response: "False positives are uncommon but can happen from operator error, certain medications containing hCG, recent pregnancy loss, tumors that produce hCG, pituitary hCG in perimenopause, or very rarely antibody interference. A positive home test should usually be confirmed with a blood test or ultrasound." },
  { id: 1107, category: 'pregnancy', keywords: ['when to worry about bleeding in early pregnancy'], question: "When should I be concerned about bleeding in early pregnancy?", response: "Any bleeding in early pregnancy deserves evaluation, but heavier bleeding, bleeding with pain/cramping, dizziness, or shoulder pain can be signs of ectopic pregnancy or miscarriage. Light spotting around the time of an expected period can sometimes occur in normal pregnancies, but it's still best to get checked." },
  { id: 1108, category: 'pregnancy', keywords: ['nausea and vomiting in early pregnancy when to worry'], question: "When is nausea and vomiting in pregnancy a concern?", response: "Mild nausea is very common. Severe or persistent vomiting with weight loss, dehydration, dizziness, or inability to keep fluids down may be hyperemesis gravidarum and needs medical care. Vomiting that starts after 10 weeks or comes with fever, severe pain, or headache should also be evaluated promptly." },
  { id: 1109, category: 'pregnancy', keywords: ['pregnancy of unknown location what to do'], question: "What does it mean if my pregnancy test is positive but ultrasound doesn't show anything yet?", response: "This is called a pregnancy of unknown location. It can be a very early intrauterine pregnancy, an ectopic pregnancy, or a pregnancy that isn't developing normally. Serial hCG blood tests and follow-up ultrasounds are used to figure it out. Any pain or bleeding should be reported right away." },
  { id: 1110, category: 'pregnancy', keywords: ['when to seek care in early pregnancy'], question: "When should I contact my provider in early pregnancy?", response: "Contact your provider for heavy bleeding, severe pain, dizziness, shoulder pain, fever, vomiting that prevents keeping fluids down, or if you have risk factors for ectopic pregnancy (prior ectopic, IUD, tubal surgery, assisted reproduction). Even mild symptoms are worth reporting if you're worried." },

  // === Second & Third Trimester Prenatal Care (IDs 1117–1132) ===
  { id: 1117, category: 'pregnancy', keywords: ['how often are prenatal visits in second and third trimester'], question: "How often are prenatal visits in the second and third trimester?", response: "For most low-risk pregnancies in the United States, visits are typically every 4 weeks until 28 weeks, every 2 weeks from 28 to 36 weeks, and then weekly until delivery. Your provider may adjust this schedule based on your individual needs, risk factors, or use of telehealth visits." },
  { id: 1118, category: 'pregnancy', keywords: ['alarm symptoms in pregnancy to report'], question: "What symptoms in pregnancy should I report right away?", response: "Report vaginal bleeding, leaking fluid, decreased fetal movement, severe or persistent abdominal pain, signs of preterm labor (cramping, backache, pelvic pressure), signs of preeclampsia (headache, vision changes, upper abdominal pain), or any symptoms that worry you. It's always better to call than to wait." },
  { id: 1119, category: 'pregnancy', keywords: ['gestational diabetes screening timing'], question: "When is screening for gestational diabetes done?", response: "Universal screening is usually performed between 24 and 28 weeks of pregnancy with a glucose challenge test (one-step or two-step approach). If you have strong risk factors, you may be screened earlier and then again at the usual time if the early test was normal." },
  { id: 1120, category: 'pregnancy', keywords: ['Rh negative pregnancy anti-D shot'], question: "Why do Rh-negative patients get a shot at 28 weeks?", response: "If you are Rh-negative, you receive anti-D immune globulin (RhoGAM) around 28 weeks to prevent your body from making antibodies against an Rh-positive baby. This protects future pregnancies. You'll also get another dose after birth if your baby is Rh-positive." },
  { id: 1121, category: 'pregnancy', keywords: ['GBS screening timing and why'], question: "What is group B strep (GBS) screening and when is it done?", response: "GBS screening is done with vaginal and rectal swabs between 36+0 and 37+6 weeks. If you test positive, you'll receive IV antibiotics during labor to protect your baby from early-onset GBS infection. It's a routine and important part of late pregnancy care." },
  { id: 1122, category: 'pregnancy', keywords: ['Tdap and RSV vaccine in pregnancy'], question: "Why do I need Tdap and RSV vaccines in pregnancy?", response: "Tdap (usually given 27–36 weeks) protects your newborn from whooping cough. The RSV vaccine (given 32–36 weeks during RSV season) helps protect your baby from severe RSV illness in the first months of life. Both are recommended for almost all pregnant people." },
  { id: 1123, category: 'pregnancy', keywords: ['preparing for labor and birth education'], question: "What should I learn about labor and birth in late pregnancy?", response: "In the third trimester, focus on pain relief options, what to expect during labor, signs of labor, when to go to the hospital, and your preferences for birth. Discussing these topics helps you feel more prepared and in control." },
  { id: 1124, category: 'pregnancy', keywords: ['postpartum contraception planning'], question: "When should I think about postpartum birth control?", response: "It's best to discuss postpartum contraception during pregnancy so you can choose a method that fits your needs and start it before or soon after delivery if desired. Many options (including IUDs and implants) can be placed right after birth." },

  // === Pregnancy Patient Education & Medication Safety (IDs 1133–1148) ===
  { id: 1133, category: 'pregnancy', keywords: ['prenatal vitamins what to take'], question: "What prenatal vitamins should I take?", response: "A standard prenatal multivitamin is recommended for most people. The two most important components are folic acid (0.4–0.8 mg daily) to help prevent neural tube defects and iron (usually 27–30 mg elemental iron). Your provider may adjust this based on your diet, bloodwork, or specific needs like higher-dose vitamin D." },
  { id: 1134, category: 'pregnancy', keywords: ['foods to avoid in pregnancy'], question: "What foods should I avoid during pregnancy?", response: "Avoid unpasteurized dairy and juices, undercooked meats/poultry/eggs/fish, raw sprouts, high-mercury fish, and deli meats/hot dogs unless reheated until steaming hot. Also limit caffeine to under 200–300 mg per day. These precautions help reduce risks of listeria, toxoplasmosis, and other foodborne illnesses." },
  { id: 1135, category: 'pregnancy', keywords: ['exercise during pregnancy guidelines'], question: "Is it safe to exercise during pregnancy?", response: "Yes, for most people with uncomplicated pregnancies. Aim for moderate-intensity exercise (you can still talk normally) that includes aerobic activity and strength training, about 30 minutes most days. Always check with your provider first, especially if you have any complications." },
  { id: 1136, category: 'pregnancy', keywords: ['acetaminophen in pregnancy safety'], question: "Is acetaminophen (Tylenol) safe during pregnancy?", response: "Acetaminophen is still considered the preferred medication for short-term fever or significant pain in pregnancy when needed. Use the lowest effective dose for the shortest time. While some studies have raised questions about long-term use, major medical organizations continue to support its use when clinically indicated after discussing risks and benefits with your provider." },
  { id: 1137, category: 'pregnancy', keywords: ['NSAIDs in pregnancy risks'], question: "Can I take ibuprofen or other NSAIDs during pregnancy?", response: "NSAIDs are generally avoided, especially after 20 weeks, because they can cause premature closure of the fetal ductus arteriosus and reduce amniotic fluid. Occasional short-term use early in pregnancy may be considered in some situations, but always check with your provider first — acetaminophen is usually preferred." },
  { id: 1138, category: 'pregnancy', keywords: ['antibiotics safe in pregnancy'], question: "Which antibiotics are safe during pregnancy?", response: "Penicillins, cephalosporins, clindamycin, and azithromycin are generally considered safe. Some antibiotics like tetracyclines, fluoroquinolones, and trimethoprim-sulfamethoxazole have risks and are usually avoided, especially in the first trimester or near term. Your provider will choose the safest effective option for your infection." },
  { id: 1139, category: 'pregnancy', keywords: ['seat belt use in pregnancy'], question: "Should I wear a seat belt while pregnant?", response: "Yes — always wear your three-point seat belt. Place the lap belt across your hips below the uterus and the shoulder belt between your breasts. Seat belts significantly reduce injury risk to you and your baby in a crash and are strongly recommended throughout pregnancy." },
  { id: 1140, category: 'pregnancy', keywords: ['travel during pregnancy precautions'], question: "Is it safe to travel while pregnant?", response: "Most people with uncomplicated pregnancies can travel, but check with your provider. Avoid areas with high infection risk, stay hydrated, move regularly on long trips, and wear compression stockings for flights. Many airlines restrict travel after 36–37 weeks. Discuss your specific plans with your care team." },
  { id: 1141, category: 'pregnancy', keywords: ['sleep position in pregnancy'], question: "What's the best sleep position during pregnancy?", response: "Sleep in whatever position feels most comfortable. While the left side is often recommended to improve blood flow, recent studies show that sleeping on your back or right side does not significantly increase risks like stillbirth for most people. Use pillows for support as your belly grows." },
  { id: 1142, category: 'pregnancy', keywords: ['managing nausea in pregnancy'], question: "How can I manage nausea and vomiting in pregnancy?", response: "Many people find relief with small frequent meals, avoiding triggers, ginger, vitamin B6, or acupressure. If symptoms are severe, your provider can prescribe safe medications. Severe vomiting with weight loss or dehydration needs prompt medical attention." },
  { id: 1143, category: 'pregnancy', keywords: ['constipation in pregnancy remedies'], question: "What helps with constipation during pregnancy?", response: "Increase fiber and fluids, stay active, and consider a stool softener or bulk-forming laxative if needed. Avoid harsh laxatives. Your provider can recommend safe options. Constipation is very common due to hormones and iron supplements." },
  { id: 1144, category: 'pregnancy', keywords: ['back pain in pregnancy'], question: "Is back pain normal in pregnancy and what helps?", response: "Yes, back pain is very common due to posture changes, weight gain, and ligament laxity. Gentle exercise, good posture, supportive shoes, prenatal yoga or physical therapy, and warm compresses often help. Report severe or new pain to your provider." },

  // === Nutrition in Pregnancy (IDs 1149–1164) ===
  { id: 1149, category: 'pregnancy', keywords: ['calories needed in pregnancy', 'energy requirements by trimester'], question: "How many extra calories do I need during pregnancy?", response: "In the first trimester, most people don't need extra calories. In the second and third trimesters, needs increase based on your pre-pregnancy BMI, activity level, and trimester. Focus on nutrient-dense foods rather than 'eating for two.' Your provider will monitor your weight gain to help guide this." },
  { id: 1150, category: 'pregnancy', keywords: ['protein needs in pregnancy'], question: "How much protein should I eat while pregnant?", response: "Aim for about 71 grams of protein per day in the second and third trimesters. Good sources include lean meats, poultry, eggs, seafood, beans, lentils, nuts, and dairy. Most people in high-income countries already get enough, but spreading intake across meals helps." },
  { id: 1151, category: 'pregnancy', keywords: ['omega-3 DHA in pregnancy', 'fish oil or algae for baby brain'], question: "Why is DHA important in pregnancy and how do I get enough?", response: "DHA (an omega-3) supports your baby's brain and eye development. Aim for 250–450 mg of DHA + EPA daily, ideally from low-mercury fish (2–3 servings per week) or an algae/fish oil supplement if you don't eat fish. Many prenatal vitamins now include DHA." },
  { id: 1152, category: 'pregnancy', keywords: ['iron needs in pregnancy', 'why iron is important'], question: "Why do I need more iron during pregnancy?", response: "Iron supports your expanding blood volume and your baby's growth. Most people need 27 mg per day. Many prenatal vitamins provide this, but some people need extra. Your provider will check your levels and may recommend additional iron if you're low or anemic." },
  { id: 1153, category: 'pregnancy', keywords: ['folic acid vs folate in pregnancy'], question: "How much folic acid or folate do I need?", response: "Take 400–800 mcg of folic acid daily starting at least one month before conception and through the first trimester to help prevent neural tube defects. Continue eating folate-rich foods (leafy greens, beans, fortified grains) throughout pregnancy." },
  { id: 1154, category: 'pregnancy', keywords: ['calcium and vitamin D in pregnancy'], question: "How much calcium and vitamin D do I need while pregnant?", response: "Aim for 1000–1300 mg of calcium daily (depending on your age) from dairy, fortified plant milks, leafy greens, or supplements. Most people also need 600 IU of vitamin D. These support your baby's bones and teeth and help maintain your own bone health." },
  { id: 1155, category: 'pregnancy', keywords: ['choline in pregnancy benefits'], question: "What is choline and why is it important in pregnancy?", response: "Choline supports your baby's brain development and may help reduce certain birth defect risks. Aim for 450 mg per day from eggs, meat, poultry, fish, beans, and some prenatal vitamins. Many people don't get enough from diet alone." },
  { id: 1156, category: 'pregnancy', keywords: ['vegetarian or vegan diet in pregnancy'], question: "Can I eat a vegetarian or vegan diet while pregnant?", response: "Yes, with planning. Pay special attention to protein, iron, zinc, vitamin B12, choline, iodine, and omega-3s (from algae supplements). A well-chosen prenatal vitamin and working with a dietitian can help ensure you and your baby get everything you need." },
  { id: 1157, category: 'pregnancy', keywords: ['gestational weight gain recommendations'], question: "How much weight should I gain during pregnancy?", response: "Recommended weight gain depends on your pre-pregnancy BMI. People with a normal BMI are generally advised to gain 25–35 pounds total. Your provider will track your pattern and discuss what's healthy for you and your baby." },

  // === Down Syndrome Screening (IDs 1165–1180) ===
  { id: 1165, category: 'pregnancy', keywords: ['down syndrome screening options'], question: "What are the options for screening for Down syndrome in pregnancy?", response: "The main options are cell-free DNA (cfDNA) testing from a maternal blood draw and traditional serum biochemical marker screening with or without nuchal translucency ultrasound. cfDNA is now the most common choice because it has higher accuracy. All pregnant people should be offered screening, and you can also choose diagnostic testing directly if you prefer certainty." },
  { id: 1166, category: 'pregnancy', keywords: ['cell free DNA cfDNA test for down syndrome'], question: "What is cell-free DNA (cfDNA) screening and how accurate is it?", response: "cfDNA screening looks at fragments of fetal DNA in your blood. It has very high detection rates for Down syndrome (over 99%) and very low false-positive rates. It can also screen for trisomy 18, trisomy 13, and sometimes sex chromosome differences. A positive result still needs confirmation with diagnostic testing." },
  { id: 1167, category: 'pregnancy', keywords: ['diagnostic testing CVS vs amniocentesis'], question: "What are the options for diagnostic testing?", response: "Chorionic villus sampling (CVS) can be done earlier (usually 10–13 weeks) and amniocentesis is typically done after 15 weeks. Both can give a definitive diagnosis. The procedure-related miscarriage risk is low (roughly 1 in 300 to 1 in 1000 at experienced centers). Your provider can help you choose based on timing and preference." },
  { id: 1168, category: 'pregnancy', keywords: ['screen positive result what next'], question: "What happens if my screening test is positive?", response: "A positive screening result means your baby is at higher risk, but it is not a diagnosis. You'll be offered genetic counseling and the option of diagnostic testing (CVS or amniocentesis) for confirmation. Many people also choose cfDNA as a secondary screen to get more information before deciding on an invasive test." },
  { id: 1169, category: 'pregnancy', keywords: ['options after down syndrome diagnosis'], question: "What are my options if screening or testing shows Down syndrome?", response: "You have three main options: continue the pregnancy, end the pregnancy, or make an adoption plan. Many families raise children with Down syndrome successfully. Genetic counseling and connection with support organizations can help you explore what feels right for your family." },
  { id: 1170, category: 'pregnancy', keywords: ['making decisions about prenatal genetic testing'], question: "How do I decide whether to do screening or diagnostic testing?", response: "Think about what matters most to you: early information, highest accuracy, avoiding invasive procedures, or having definitive answers. There is no right or wrong choice. Many people start with screening and move to diagnostic testing only if results are concerning. Genetic counseling can support you in making a decision that fits your values." },

  // === Neural Tube Defects (IDs 1181–1196) ===
  { id: 1181, category: 'pregnancy', keywords: ['neural tube defects types', 'spina bifida vs anencephaly'], question: "What are neural tube defects and what are the main types?", response: "Neural tube defects happen when the neural tube doesn't close properly early in pregnancy. The most common open defects are myelomeningocele (open spina bifida), anencephaly, and encephalocele. These can affect the spine, brain, and skull and often have serious consequences." },
  { id: 1182, category: 'pregnancy', keywords: ['folic acid and neural tube defects prevention'], question: "How does folic acid help prevent neural tube defects?", response: "Taking folic acid before and during early pregnancy greatly reduces the risk of neural tube defects. Most cases are related to folate deficiency. It's recommended to start at least one month before conception and continue through the first trimester." },
  { id: 1183, category: 'pregnancy', keywords: ['folic acid dose after previous neural tube defect'], question: "How much folic acid should I take if I've had a previous neural tube defect?", response: "If you've had a previous pregnancy affected by a neural tube defect, a higher dose of folic acid (usually 4 mg daily) is recommended starting at least one month before conception and continuing through the first trimester. Your provider can confirm the right dose for you." },
  { id: 1184, category: 'pregnancy', keywords: ['options after neural tube defect diagnosis'], question: "What are my options if a neural tube defect is diagnosed?", response: "Options include continuing the pregnancy with specialized care, considering fetal surgery (for some types of spina bifida), or ending the pregnancy. Many families choose to continue and connect with support resources. Genetic counseling can help you explore what feels right." },

  // === Ectopic Pregnancy Patient Education (IDs 1245–1260) ===
  { id: 1245, category: 'pregnancy', keywords: ['what is an ectopic pregnancy'], question: "What is an ectopic pregnancy?", response: "An ectopic pregnancy is a pregnancy that grows outside the uterus, most commonly in a fallopian tube. It cannot develop into a baby and can become life-threatening if not treated. It requires prompt medical care to protect your health." },
  { id: 1246, category: 'pregnancy', keywords: ['ectopic pregnancy symptoms early signs'], question: "What are the early symptoms of an ectopic pregnancy?", response: "Early symptoms can include lower belly pain and vaginal bleeding or spotting. Some people have no symptoms at first. If the pregnancy grows in a fallopian tube and causes it to rupture, symptoms become severe: sudden intense pain, heavy bleeding, dizziness, or fainting. Go to the ER immediately if this happens." },
  { id: 1247, category: 'pregnancy', keywords: ['ectopic pregnancy risk factors'], question: "What increases the risk of having an ectopic pregnancy?", response: "Risk is higher if you have damaged fallopian tubes (from infections, surgery, or endometriosis), had a previous ectopic pregnancy, smoke, or are using certain fertility treatments. Having an IUD or prior tubal ligation lowers overall pregnancy risk but raises the chance that any pregnancy will be ectopic." },
  { id: 1248, category: 'pregnancy', keywords: ['ectopic pregnancy treatment options'], question: "How is an ectopic pregnancy treated?", response: "Treatment depends on how far along it is and your symptoms. Options include a medication called methotrexate (given as an injection) to stop the pregnancy from growing, or surgery to remove the pregnancy (sometimes the affected fallopian tube too). Your doctor will choose the safest option for your situation." },
  { id: 1249, category: 'pregnancy', keywords: ['ectopic pregnancy rupture emergency'], question: "When is an ectopic pregnancy an emergency?", response: "It's an emergency if you have severe sudden abdominal pain, heavy vaginal bleeding, shoulder pain, dizziness, fainting, or feel like you might pass out. These can be signs of a ruptured fallopian tube and internal bleeding. Call emergency services or go to the ER right away." },
  { id: 1250, category: 'pregnancy', keywords: ['can I get pregnant after ectopic pregnancy'], question: "Can I have a normal pregnancy after an ectopic pregnancy?", response: "Yes, most people can have a healthy pregnancy after an ectopic. However, having one ectopic increases your risk of another. When you're ready to try again, tell your doctor so they can monitor you closely from the beginning with early ultrasounds and hCG tracking." },
  { id: 1251, category: 'pregnancy', keywords: ['how soon can I try to conceive after ectopic'], question: "How long should I wait to try to get pregnant again after an ectopic?", response: "Many doctors recommend waiting at least 3 months after treatment (especially after methotrexate) so your body can heal and hormone levels normalize. Your provider will give you personalized guidance based on how you were treated and your overall health." },
  { id: 1252, category: 'pregnancy', keywords: ['emotional support after ectopic pregnancy'], question: "I'm feeling sad or anxious after my ectopic pregnancy. Is that normal?", response: "Yes, it's very common to feel grief, anxiety, fear, or sadness after an ectopic pregnancy. It's a loss, and the experience can be frightening. Many people benefit from talking with a therapist, joining a pregnancy loss support group, or connecting with others who have been through it." },

  // === Smoking in Pregnancy (IDs 1261–1276) ===
  { id: 1261, category: 'pregnancy', keywords: ['smoking during pregnancy risks'], question: "How can smoking affect my pregnancy?", response: "Smoking during pregnancy increases the risk of serious complications including preterm labor, problems with the placenta (such as previa or abruption), miscarriage, and stillbirth. It also raises the chance that your baby will be born too early or too small, and it increases the risk of sudden infant death syndrome (SIDS)." },
  { id: 1262, category: 'pregnancy', keywords: ['effects of smoking on baby'], question: "How does smoking during pregnancy affect my baby?", response: "Babies exposed to smoking in pregnancy are more likely to be born premature or with low birth weight. These babies have higher risks of feeding, breathing, and developmental problems. Smoking also significantly increases the risk of sudden infant death syndrome (SIDS) in the first year of life." },
  { id: 1263, category: 'pregnancy', keywords: ['vaping or e-cigarettes in pregnancy'], question: "Is vaping or using e-cigarettes safe during pregnancy?", response: "No. It is best to avoid all tobacco and nicotine products during pregnancy, including e-cigarettes and vaping. These products contain nicotine and other harmful chemicals that can affect your baby's development. Quitting completely is the safest choice." },
  { id: 1264, category: 'pregnancy', keywords: ['marijuana in pregnancy risks'], question: "Is it okay to use marijuana during pregnancy?", response: "Doctors recommend avoiding marijuana during pregnancy. Some studies suggest it can affect fetal brain development and increase risks for the baby. Even in places where it's legal, it's safest to stop using it while pregnant and breastfeeding." },
  { id: 1265, category: 'pregnancy', keywords: ['when is the best time to quit smoking in pregnancy'], question: "Is it too late to quit if I'm already pregnant?", response: "No — it's never too late. Quitting at any point in pregnancy helps your baby. The earlier you quit, the better, but stopping even in the second or third trimester still reduces risks of preterm birth, low birth weight, and other complications." },
  { id: 1266, category: 'pregnancy', keywords: ['smoking and miscarriage stillbirth risk'], question: "Does smoking increase the risk of miscarriage or stillbirth?", response: "Yes. Smoking raises the risk of both miscarriage (pregnancy loss before 20 weeks) and stillbirth (loss after 20 weeks). Quitting reduces these risks and improves the chances of a healthy pregnancy and baby." },
  { id: 1267, category: 'pregnancy', keywords: ['benefits of quitting smoking for mom and baby'], question: "What are the benefits of quitting smoking during pregnancy?", response: "Quitting lowers your risk of preterm birth, placental problems, miscarriage, and stillbirth. Your baby is more likely to be born at a healthy weight and has a lower risk of SIDS. You'll also breathe easier, have more energy, and reduce your own long-term risks of heart disease and cancer." },
  { id: 1268, category: 'pregnancy', keywords: ['support to quit smoking while pregnant'], question: "Where can I get help to quit smoking during pregnancy?", response: "Talk to your prenatal provider — they can connect you with counseling, quitlines, apps, or local programs. Many people find that combining counseling with support from family and friends works best. Free resources like 1-800-QUIT-NOW are also available." },

  // === Vaccines in Pregnancy (IDs 1277–1292) ===
  { id: 1277, category: 'pregnancy', keywords: ['vaccines in pregnancy why important'], question: "Why should I get vaccinated during pregnancy?", response: "Vaccines help protect you from serious infections that can be more dangerous during pregnancy. They also pass some protection to your baby in the first few months of life. Getting recommended vaccines is one of the best ways to keep both you and your newborn healthy." },
  { id: 1278, category: 'pregnancy', keywords: ['flu vaccine during pregnancy'], question: "Should I get the flu shot while pregnant?", response: "Yes. The flu vaccine is strongly recommended every year during pregnancy. Pregnant people can get much sicker from the flu. The vaccine protects you and also helps protect your baby from the flu in the first few months after birth." },
  { id: 1279, category: 'pregnancy', keywords: ['Tdap vaccine pregnancy whooping cough'], question: "Why do I need the Tdap vaccine during pregnancy?", response: "The Tdap vaccine (tetanus, diphtheria, and pertussis/whooping cough) is recommended between 27 and 36 weeks of every pregnancy. It mainly protects your newborn from whooping cough, which can be very serious or even deadly in young babies." },
  { id: 1280, category: 'pregnancy', keywords: ['RSV vaccine in pregnancy'], question: "What is the RSV vaccine and should I get it?", response: "There is now an RSV vaccine that can be given during pregnancy (between 32 and 36 weeks). It helps protect your baby from severe RSV illness in the first 6 months of life. Your provider can also discuss giving your baby a preventive shot after birth instead. Both options are safe and effective." },
  { id: 1281, category: 'pregnancy', keywords: ['which vaccines are safe in pregnancy'], question: "Which vaccines are safe to get while pregnant?", response: "Safe vaccines during pregnancy include COVID-19, flu (inactivated), Tdap, and the RSV vaccine (when indicated). Live vaccines like MMR and varicella are not given during pregnancy. Your provider will recommend the right ones based on your health and risk factors." },
  { id: 1282, category: 'pregnancy', keywords: ['COVID vaccine in pregnancy'], question: "Is the COVID-19 vaccine safe during pregnancy?", response: "Yes. The COVID-19 vaccine is recommended during pregnancy. Pregnant people are at higher risk of severe illness from COVID-19. Getting vaccinated also helps protect your baby from COVID-19 in the first 6 months of life." },
  { id: 1283, category: 'pregnancy', keywords: ['how vaccines protect baby after birth'], question: "How do vaccines during pregnancy help my baby?", response: "When you get vaccinated during pregnancy, you pass antibodies to your baby through the placenta. This gives your newborn some protection in the first few months of life, before they can receive their own vaccines (especially important for whooping cough, flu, and RSV)." },
  { id: 1284, category: 'pregnancy', keywords: ['vaccines and autism myth'], question: "Do vaccines cause autism?", response: "No. There is no scientific link between vaccines and autism. This has been studied extensively. Getting recommended vaccines during pregnancy is safe and helps protect both you and your baby." },
  { id: 1285, category: 'pregnancy', keywords: ['Tdap every pregnancy'], question: "Do I need the Tdap vaccine with every pregnancy?", response: "Yes. You should get the Tdap vaccine during every pregnancy, ideally between 27 and 36 weeks, even if you received it before. This ensures your newborn gets the best protection against whooping cough." },

  // === High-Risk Pregnancy & Late Pregnancy (IDs 1309–1340) ===
  { id: 1309, category: 'pregnancy', keywords: ['what is a high risk pregnancy'], question: "What does it mean to have a high-risk pregnancy?", response: "A high-risk pregnancy means there is an increased chance of problems for you, your baby, or both. It does not mean problems will definitely happen. You will receive closer monitoring, more frequent visits, and possibly care from a maternal-fetal medicine specialist to catch and manage any issues early." },
  { id: 1310, category: 'pregnancy', keywords: ['breech baby position what happens'], question: "What happens if my baby is breech near the end of pregnancy?", response: "Many breech babies turn head-down on their own. If your baby is still breech near your due date, your provider may offer an external cephalic version (gently turning the baby by pressing on your belly under ultrasound guidance). If that doesn't work, a cesarean birth is usually recommended for safety." },
  { id: 1311, category: 'pregnancy', keywords: ['signs of labor approaching third trimester'], question: "What are signs that labor is getting close?", response: "You may notice the baby dropping lower, increased pelvic pressure, more frequent Braxton-Hicks contractions, loss of the mucus plug, or lightening (easier breathing). True labor contractions become regular, stronger, and closer together." },
  { id: 1312, category: 'pregnancy', keywords: ['Braxton Hicks vs real contractions'], question: "How do I tell Braxton Hicks contractions from real labor?", response: "Braxton Hicks are usually irregular, not very painful, and often go away with rest or hydration. Real labor contractions become progressively stronger, longer, and closer together. They don't go away with position changes." },
  { id: 1313, category: 'pregnancy', keywords: ['fetal movement in third trimester kick counts'], question: "How often should I feel my baby move in the third trimester?", response: "You should continue to feel regular movement every day. Many providers recommend doing daily kick counts. Contact your provider if you notice a significant decrease in movement." },
  { id: 1314, category: 'pregnancy', keywords: ['preterm labor signs third trimester'], question: "What are signs of preterm labor I should watch for?", response: "Watch for regular contractions (especially if painful or more than 5–6 per hour), pelvic pressure, low backache, changes in vaginal discharge, or fluid leaking. Call your provider right away if you have these symptoms before 37 weeks." },
  { id: 1315, category: 'pregnancy', keywords: ['preparing for birth third trimester checklist'], question: "What should I do to prepare for birth in the third trimester?", response: "Take a childbirth class, pack your hospital bag, install your car seat, arrange help at home, discuss your birth preferences with your provider, and think about postpartum support and contraception. Also finalize pediatric care." },
  { id: 1316, category: 'pregnancy', keywords: ['when to go to hospital for labor'], question: "When should I go to the hospital when I think I'm in labor?", response: "Go when contractions are regular and strong (usually 5 minutes apart for an hour), your water breaks, or you have heavy bleeding or decreased fetal movement. Your provider will give you specific guidelines based on your situation." },
  { id: 1317, category: 'pregnancy', keywords: ['alcohol during pregnancy risks'], question: "How does alcohol affect pregnancy?", response: "No amount of alcohol is known to be safe. Drinking during pregnancy can cause fetal alcohol spectrum disorders, growth problems, miscarriage, and stillbirth. It's best to avoid alcohol completely while trying to conceive and during pregnancy." },
  { id: 1318, category: 'pregnancy', keywords: ['is acetaminophen safe in pregnancy third trimester'], question: "Is acetaminophen (Tylenol) safe during pregnancy (third trimester)?", response: "Acetaminophen is generally considered the safest option for short-term relief of pain or fever during pregnancy when used at the recommended dose. Always check with your provider, especially if you need it frequently or for a long time." },
  { id: 1319, category: 'pregnancy', keywords: ['NSAIDs ibuprofen risks third trimester'], question: "Can I take ibuprofen or other NSAIDs while pregnant?", response: "NSAIDs (like ibuprofen) are usually avoided after 20 weeks because they can affect the baby's kidneys and amniotic fluid. They may be used briefly earlier in pregnancy only if recommended by your provider." },
  { id: 1320, category: 'pregnancy', keywords: ['Rh negative pregnancy RhoGAM what it is'], question: "What does it mean if I'm Rh-negative during pregnancy?", response: "If you are Rh-negative and your baby is Rh-positive, your body can develop antibodies that may affect future pregnancies. You will receive RhoGAM (anti-D immune globulin) around 28 weeks and after birth to prevent this from happening." },
  { id: 1321, category: 'pregnancy', keywords: ['UTI symptoms in pregnancy'], question: "What are the symptoms of a UTI during pregnancy?", response: "Common symptoms include burning with urination, frequent or urgent urination, and sometimes blood in the urine. A kidney infection can also cause fever, back pain, nausea, or vomiting. Tell your provider right away if you have these symptoms." },
  { id: 1322, category: 'pregnancy', keywords: ['asymptomatic bacteriuria pregnancy treatment'], question: "Why is asymptomatic bacteriuria treated in pregnancy?", response: "Even without symptoms, bacteria in the urine during pregnancy can lead to kidney infections, preterm birth, or low birth weight. That's why it is routinely screened for and treated with antibiotics that are safe in pregnancy." },
  { id: 1323, category: 'pregnancy', keywords: ['bleeding in early pregnancy is it normal'], question: "Is bleeding in early pregnancy normal?", response: "Light bleeding or spotting in early pregnancy is common and often not serious. However, it can sometimes signal a miscarriage or ectopic pregnancy. Always call your provider if you have any bleeding so they can evaluate you." },
  { id: 1324, category: 'pregnancy', keywords: ['causes of bleeding in late pregnancy'], question: "What can cause bleeding in late pregnancy?", response: "Possible causes include placental abruption, placenta previa, labor starting, cervical changes, or (rarely) vasa previa. Any bleeding after 20 weeks should be checked promptly, as some causes can be serious." },

  // === Postpartum Warning Signs & Common Issues (IDs 1341–1362) ===
  { id: 1341, category: 'postpartum', keywords: ['postpartum headache when to worry'], question: "When should I worry about a postpartum headache?", response: "Most postpartum headaches are from fatigue, dehydration, or hormonal shifts, but call your provider right away if the headache is severe, comes with vision changes, high blood pressure, or feels different from your usual headaches. These can be signs of something more serious like preeclampsia or a blood clot." },
  { id: 1342, category: 'postpartum', keywords: ['high blood pressure after birth'], question: "Why is high blood pressure a big deal after giving birth?", response: "Blood pressure can spike or stay high after delivery and increase the risk of stroke. If your readings are 140/90 or higher, contact your provider immediately — they may need to adjust medications or monitor you more closely." },
  { id: 1343, category: 'postpartum', keywords: ['heavy bleeding after birth when to worry'], question: "How much bleeding is too much after delivery?", response: "Soaking a pad in an hour or passing large clots is too much. Heavy bleeding, dizziness, or feeling faint can signal postpartum hemorrhage. Go to the ER or call your provider immediately." },
  { id: 1344, category: 'postpartum', keywords: ['shortness of breath after birth'], question: "Why would I have shortness of breath or chest pain after giving birth?", response: "These can be signs of a blood clot in the lungs, heart muscle weakness (peripartum cardiomyopathy), or other serious issues. Don't wait — get checked right away." },
  { id: 1345, category: 'postpartum', keywords: ['difficulty peeing after birth'], question: "Why is it hard to pee after giving birth?", response: "Swelling, nerve stretching during delivery, or anesthesia can cause temporary urinary retention. It usually improves within a week, but if you can't pee or only pass small amounts, tell your provider — they may need to catheterize you temporarily." },
  { id: 1346, category: 'postpartum', keywords: ['hemorrhoids after birth'], question: "Are hemorrhoids common after delivery?", response: "Yes — about one in three people get them. Warm baths, stool softeners, and over-the-counter creams help. Let your provider know if they're very painful or bleeding heavily." },
  { id: 1347, category: 'postpartum', keywords: ['vaginal dryness after birth'], question: "Why do I feel so dry down there after having a baby?", response: "Low estrogen (especially while breastfeeding) is the main culprit. Use a vaginal moisturizer daily and a lubricant for sex. Low-dose vaginal estrogen is safe for most people and very effective if needed." },
  { id: 1348, category: 'postpartum', keywords: ['fever after birth infection'], question: "What does a fever mean after giving birth?", response: "It can signal an infection in the uterus, breasts, urinary tract, or a wound. Any fever over 100.4°F (38°C) after the first 24 hours should be reported to your provider right away." },
  { id: 1349, category: 'postpartum', keywords: ['mastitis symptoms'], question: "What are the signs of mastitis?", response: "A red, hot, painful area on one breast plus flu-like symptoms (fever, chills, body aches) usually means mastitis. Keep nursing or pumping on that side and call your provider — antibiotics are often needed." },
  { id: 1350, category: 'postpartum', keywords: ['postpartum PTSD birth trauma'], question: "Can giving birth cause PTSD?", response: "Yes — traumatic births, emergency cesareans, or feeling out of control can lead to postpartum PTSD. Flashbacks, nightmares, or avoiding reminders are common signs. Therapy can help a lot — you're not alone." },
  { id: 1351, category: 'postpartum', keywords: ['sex after birth when is it safe'], question: "When is it safe to have sex again after giving birth?", response: "Most providers recommend waiting until your bleeding has stopped and any tears or incisions have healed — usually about 4–6 weeks. Go at your own pace and use plenty of lube if you feel dry." },
  { id: 1352, category: 'postpartum', keywords: ['birth control after having a baby'], question: "When should I start birth control after giving birth?", response: "You can start most methods right away, even while breastfeeding. Progestin-only options (mini-pill, IUD, implant, shot) are safe immediately. Talk to your provider about what fits your life best." },
  { id: 1353, category: 'postpartum', keywords: ['when to call doctor after birth postpartum'], question: "When should I call my doctor after giving birth?", response: "Call for heavy bleeding, fever, severe pain, bad-smelling discharge, difficulty peeing, chest pain, shortness of breath, severe headache, or if you just don't feel right. It's always better to check than to wait." },
  { id: 1354, category: 'postpartum', keywords: ['postpartum checkup what to expect'], question: "What happens at the postpartum checkup?", response: "Your provider will check your healing, blood pressure, mood, bleeding, and ask about contraception and how you're feeling emotionally. It's a great time to bring up any concerns." },

  // === Postpartum Hemorrhage (IDs 1363–1376) ===
  { id: 1363, category: 'postpartum', keywords: ['what is postpartum hemorrhage'], question: "What is postpartum hemorrhage?", response: "Postpartum hemorrhage is when someone loses a large amount of blood after giving birth. It can happen after a vaginal birth or a cesarean. The most common reason is that the uterus doesn't contract strongly enough after the baby is born." },
  { id: 1364, category: 'postpartum', keywords: ['why does the uterus not contract after birth'], question: "Why doesn't the uterus contract well after birth?", response: "After the baby is born, the uterus needs to tighten firmly to close off the blood vessels where the placenta was attached. If it stays relaxed (called uterine atony), bleeding can become very heavy." },
  { id: 1365, category: 'postpartum', keywords: ['signs of postpartum hemorrhage'], question: "What are the signs of postpartum hemorrhage?", response: "The main sign is heavy vaginal bleeding. You might also feel weak, dizzy, lightheaded, or like your heart is racing. These symptoms mean you're losing too much blood and need help right away." },
  { id: 1366, category: 'postpartum', keywords: ['uterine massage for bleeding after birth'], question: "What is uterine massage and why is it done?", response: "Uterine massage is when a nurse, doctor, or midwife presses firmly on your lower belly and rubs the uterus. This helps the uterus contract and can slow or stop heavy bleeding." },
  { id: 1367, category: 'postpartum', keywords: ['medicines for postpartum hemorrhage'], question: "What medicines are used for heavy bleeding after birth?", response: "Medications called uterotonics are given to help the uterus contract and reduce bleeding. Common ones include oxytocin, misoprostol, methylergonovine, and carboprost. Your provider will choose the best one for your situation." },
  { id: 1368, category: 'postpartum', keywords: ['what to do if bleeding heavily after birth'], question: "What should I do if I'm bleeding heavily after going home?", response: "Heavy bleeding after you've been discharged is an emergency. Soak through a pad in an hour, pass large clots, or feel dizzy or faint — go to the ER or call emergency services right away." },
  { id: 1369, category: 'postpartum', keywords: ['will postpartum hemorrhage happen again'], question: "Will I have heavy bleeding again in future pregnancies?", response: "Having postpartum hemorrhage once does increase your risk of having it again in future pregnancies, but most people do not experience it a second time. Make sure your provider knows your history so they can be prepared." },
  { id: 1370, category: 'postpartum', keywords: ['how common is postpartum hemorrhage'], question: "How common is postpartum hemorrhage?", response: "It is one of the most common serious complications after birth, but with quick recognition and treatment, most people recover well. Your care team is trained to watch for and manage it." },

  // === Normal Postpartum Physiology (IDs 1377–1395) ===
  { id: 1377, category: 'postpartum', keywords: ['how long is the postpartum period'], question: "How long does the postpartum period last?", response: "The postpartum period, sometimes called the fourth trimester, begins right after birth. While many physical changes return to normal by 6–8 weeks, full recovery can take up to 12 weeks or longer. ACOG considers postpartum care to extend through the first 12 weeks after delivery." },
  { id: 1378, category: 'postpartum', keywords: ['what is the fourth trimester'], question: "What is the fourth trimester?", response: "The fourth trimester refers to the first 12 weeks after giving birth. It's a time of major physical, emotional, and hormonal adjustment as your body heals and you adapt to caring for a newborn." },
  { id: 1379, category: 'postpartum', keywords: ['shivering after birth'], question: "Why am I shivering or feeling cold after giving birth?", response: "Shivering or chills are very common in the first hours after delivery. It can be caused by hormonal shifts, fluid changes, or the body cooling down after labor. Warm blankets usually help, and it typically passes within an hour." },
  { id: 1380, category: 'postpartum', keywords: ['uterus shrinking after birth'], question: "How long does it take for the uterus to go back to normal size?", response: "Your uterus starts shrinking right after birth. It drops about 1 cm per day and is usually back to its normal size by 6–8 weeks. You may feel afterpains (cramping) as it contracts, especially while breastfeeding." },
  { id: 1381, category: 'postpartum', keywords: ['lochia how long does it last'], question: "How long does bleeding (lochia) last after birth?", response: "Lochia (postpartum bleeding) usually lasts about 4–6 weeks. It starts bright red, becomes pinkish-brown, then turns yellowish-white. Heavy bleeding or foul smell should be reported." },
  { id: 1382, category: 'postpartum', keywords: ['abdominal wall after pregnancy'], question: "Why does my belly still look pregnant after birth?", response: "Your abdominal muscles and skin stretched during pregnancy. It takes time for them to regain tone. Some people develop a separation of the rectus muscles (diastasis recti) that may need targeted exercises or physical therapy." },
  { id: 1383, category: 'postpartum', keywords: ['hair loss after pregnancy postpartum'], question: "Why is my hair falling out after having a baby?", response: "This is called telogen effluvium. Pregnancy hormones keep more hair in the growth phase. After birth, it sheds. It's usually temporary and peaks around 3–4 months postpartum. Most people see normal hair growth return by 6–15 months." },
  { id: 1384, category: 'postpartum', keywords: ['breast engorgement what to do'], question: "What helps with breast engorgement?", response: "Engorgement is common as milk comes in (usually days 3–5). Warm showers or compresses before feeding, cool packs after, gentle massage, and frequent nursing or pumping help. Ibuprofen can reduce pain and swelling." },

  // === Menstrual Suppression (IDs 1053–1068) ===
  { id: 1053, category: 'menstrual_suppression', keywords: ['is it safe to skip periods', 'menstrual suppression safety'], question: "Is it safe to stop having periods with birth control?", response: "Yes — it's medically safe for most people. Having a monthly period isn't necessary for your health. Suppressing periods with hormonal methods doesn't cause harm and can actually reduce risks linked to frequent ovulation, like endometriosis or ovarian cancer for some people." },
  { id: 1054, category: 'menstrual_suppression', keywords: ['why skip periods', 'reasons for menstrual suppression'], question: "Why would someone want to stop their period?", response: "There are lots of good reasons. Some people do it for medical issues like heavy bleeding, severe cramps, endometriosis, anemia, or bleeding disorders. Others do it for convenience, travel, sports, work, school, or because periods cause significant mood or physical symptoms. Gender-expansive people may also choose it to reduce gender dysphoria related to menstruation." },
  { id: 1055, category: 'menstrual_suppression', keywords: ['best way to stop periods', 'methods for amenorrhea'], question: "What are the best ways to stop having periods?", response: "The most effective options for achieving amenorrhea include the hormonal IUD (52 mg levonorgestrel), the Depo-Provera shot, and continuous or extended use of combined birth control pills or the vaginal ring. The hormonal IUD and shot tend to have higher rates of stopping periods over time." },
  { id: 1056, category: 'menstrual_suppression', keywords: ['continuous birth control pills to skip period'], question: "Can I take birth control pills continuously to skip my period?", response: "Yes. You can take the active pills every day without the placebo week, or use extended-cycle packs. This is safe and effective. You might have some irregular spotting at first, but it usually improves after a few months." },
  { id: 1057, category: 'menstrual_suppression', keywords: ['hormonal IUD for no periods'], question: "How effective is the hormonal IUD at stopping periods?", response: "The 52 mg levonorgestrel IUD (like Mirena or Liletta) is one of the best options for stopping periods. After one year, about 20% of users have no periods, and by two years that rises to 30–50%. It also provides excellent contraception for up to 8 years." },
  { id: 1058, category: 'menstrual_suppression', keywords: ['menstrual suppression for endometriosis'], question: "Is menstrual suppression helpful for endometriosis?", response: "Yes — it's often very helpful. Continuous or extended combined hormonal methods, the hormonal IUD, or progestin-only options can reduce pain by limiting periods and keeping the endometrial tissue thinner." },
  { id: 1059, category: 'menstrual_suppression', keywords: ['fertility after stopping period suppression'], question: "Will stopping period suppression affect my future fertility?", response: "For most methods (pills, ring, hormonal IUD, implant), fertility returns quickly after stopping — usually within 1–3 months. The Depo shot can sometimes delay return of periods and fertility a bit longer. Menstrual suppression itself does not cause long-term infertility." },
  { id: 1060, category: 'menstrual_suppression', keywords: ['gender affirming menstrual suppression'], question: "Can menstrual suppression help with gender dysphoria?", response: "Yes — for many transgender and gender-expansive people, reducing or stopping periods can significantly decrease gender dysphoria related to menstruation. Options like the hormonal IUD, continuous pills, or the shot are commonly used. We work with each person to find a method that feels affirming and safe." },

  // === COC Deep Dive (IDs 1037–1052) ===
  { id: 1037, category: 'birth_control', keywords: ['how do birth control pills work', 'mechanism of COCs'], question: "How do combined birth control pills actually prevent pregnancy?", response: "They mainly work by stopping ovulation — they suppress the hormones that trigger egg release. They also thicken cervical mucus so sperm have a harder time getting through and thin the uterine lining so it's less welcoming for a fertilized egg. Both the estrogen and progestin work together to make this happen reliably when taken correctly." },
  { id: 1038, category: 'birth_control', keywords: ['risks of birth control pills', 'blood clot risk with COCs'], question: "How risky are birth control pills for blood clots?", response: "There is a small increased risk of blood clots with combined pills, especially in the first year and if you have other risk factors (smoking, obesity, age over 35, or personal/family history). The absolute risk is still low for most healthy people — lower than the clot risk during pregnancy and postpartum. We weigh your personal risks carefully when choosing a method." },
  { id: 1039, category: 'birth_control', keywords: ['noncontraceptive benefits of the pill'], question: "What are the benefits of birth control pills besides preventing pregnancy?", response: "They often make periods lighter, shorter, and less painful. They can improve acne, reduce ovarian cysts, help with endometriosis pain, regulate cycles in PCOS, and lower the lifetime risk of ovarian and endometrial cancer. Many people also use them to skip periods entirely for lifestyle or medical reasons." },
  { id: 1040, category: 'birth_control', keywords: ['starting birth control pills quick start'], question: "Can I start birth control pills any day, or do I have to wait for my period?", response: "You can start the same day you get the prescription (quick start) as long as we're reasonably sure you're not pregnant. If it's been more than 5 days since your period started, you'll need backup contraception (like condoms) for the first 7 days." },
  { id: 1041, category: 'birth_control', keywords: ['missed birth control pills what to do'], question: "What should I do if I miss a birth control pill?", response: "If you miss just one pill, take it as soon as you remember and continue your pack as usual — you may take two pills in one day. If you miss two or more pills, especially in the first week, use backup contraception and consider emergency contraception if you've had unprotected sex." },
  { id: 1042, category: 'birth_control', keywords: ['continuous or extended cycle birth control pills'], question: "Can I take birth control pills continuously to skip my period?", response: "Yes — many people do this safely. You can take active pills continuously (no placebo week) or use extended-cycle packs that give you a period only every 3 months. Unscheduled spotting is common at first but usually improves after a few months. This is a great option for heavy periods, endometriosis, PMDD, or if you just prefer fewer periods." },
  { id: 1043, category: 'birth_control', keywords: ['common side effects when starting the pill'], question: "What side effects should I expect when I first start birth control pills?", response: "Many people notice breast tenderness, nausea, bloating, or mood changes in the first 1–3 months. These often improve as your body adjusts. Unscheduled spotting is also common early on. If side effects are bothersome after 3 months, we can try a different formulation." },
  { id: 1044, category: 'birth_control', keywords: ['return of fertility after stopping the pill'], question: "How quickly can I get pregnant after stopping birth control pills?", response: "Most people ovulate within 1–3 months after stopping. Your period and fertility usually return within 90 days. The pill does not cause long-term infertility — any delay is usually just your body returning to its natural cycle." },
  { id: 1045, category: 'birth_control', keywords: ['cancer risk with birth control pills'], question: "Do birth control pills increase cancer risk?", response: "Combined pills slightly increase the risk of breast and cervical cancer while you're taking them, but that risk goes back down after stopping. On the positive side, they significantly lower lifetime risk of ovarian and endometrial cancers. Overall, for most people the benefits outweigh the risks, but we discuss your personal and family history when choosing a method." },
  { id: 1046, category: 'birth_control', keywords: ['perimenopause and birth control pills'], question: "Can I use birth control pills during perimenopause?", response: "Yes — low-dose combined pills are often helpful in perimenopause for regulating cycles, reducing hot flashes, and providing contraception. We usually choose lower estrogen doses and monitor for clot risk as you get older. Many women use them until menopause and then transition to hormone therapy if needed." },

];