// RAG Knowledge Base Entries for Luna Chat
// Organized by category for efficient retrieval

export const ragEntries = [
  // === Postpartum Depression: Paternal PPD (IDs 1520–1531) ===
  { id: 1520, category: 'postpartum', keywords: ['father postpartum depression symptoms'], question: "Can fathers get postpartum depression?", response: "Yes. About 1 in 10 fathers experience depression during the perinatal period. Symptoms include irritability, withdrawal, fatigue, and mood changes. It's often underrecognized but treatable." },
  { id: 1521, category: 'postpartum', keywords: ['paternal postpartum depression prevalence'], question: "How common is postpartum depression in fathers?", response: "Studies show 8–10% of fathers experience depression during pregnancy or the first year postpartum. Rates are higher (24–50%) when the mother also has postpartum depression." },
  { id: 1522, category: 'postpartum', keywords: ['father postpartum depression risk factors'], question: "What increases a father's risk of postpartum depression?", response: "Key risk factors include: partner with depression, history of depression, relationship stress, financial stress, sleep deprivation, and lack of social support. Younger age and unplanned pregnancy also increase risk." },
  { id: 1523, category: 'postpartum', keywords: ['how paternal depression affects bonding'], question: "How does a father's depression affect bonding with the baby?", response: "Depression can make it harder to engage in sensitive, responsive parenting. Affected fathers may interact less, read fewer books, and sing fewer songs to their infants. Early treatment improves bonding outcomes." },
  { id: 1524, category: 'postpartum', keywords: ['screening fathers for postpartum depression'], question: "Should fathers be screened for postpartum depression?", response: "Yes. The Edinburgh Postnatal Depression Scale (EPDS) can be used with fathers. Screening is recommended during pregnancy and postpartum, especially if the mother has depression or there are relationship stressors." },
  { id: 1525, category: 'postpartum', keywords: ['treatment for fathers with postpartum depression'], question: "How is paternal postpartum depression treated?", response: "Treatment includes psychotherapy (CBT or IPT), support groups, lifestyle changes (sleep, exercise), and sometimes medication. Involving the partner in treatment can improve outcomes for both parents." },
  { id: 1526, category: 'postpartum', keywords: ['impact of father depression on child development'], question: "How does a father's depression affect child development?", response: "Untreated paternal depression is linked to increased behavioral problems, emotional difficulties, and cognitive delays in children. Early identification and treatment protect child outcomes." },
  { id: 1527, category: 'postpartum', keywords: ['when do fathers get postpartum depression'], question: "When does postpartum depression typically start in fathers?", response: "Paternal depression peaks between 3–6 months postpartum, but can start during pregnancy or anytime in the first year. Ongoing monitoring is important throughout the perinatal period." },
  { id: 1528, category: 'postpartum', keywords: ['signs of father postpartum depression'], question: "What are the signs of postpartum depression in fathers?", response: "Common signs include: increased irritability or anger, withdrawal from family, loss of interest in activities, fatigue, changes in appetite or sleep, and increased risk-taking behavior or substance use." },
  { id: 1529, category: 'postpartum', keywords: ['supporting partner with postpartum depression as a father'], question: "How can fathers support a partner with postpartum depression?", response: "Fathers can help by: sharing nighttime feedings, encouraging professional help, attending appointments, providing emotional support, managing household tasks, and being patient and understanding." },
  { id: 1530, category: 'postpartum', keywords: ['father postpartum depression and relationship'], question: "How does paternal postpartum depression affect the relationship?", response: "It can increase conflict, reduce intimacy, and create communication challenges. Couples therapy or involving the partner in individual treatment can help repair and strengthen the relationship." },
  { id: 1531, category: 'postpartum', keywords: ['father postpartum depression resources'], question: "Where can fathers get help for postpartum depression?", response: "Resources include: primary care providers, mental health professionals, Postpartum Support International (PSI), online support groups, and father-specific programs. Many therapists specialize in perinatal mental health." },

  // === Postpartum Depression: Prevention (IDs 1532–1543) ===
  { id: 1532, category: 'postpartum', keywords: ['who should prevent postpartum depression'], question: "Who should get preventive treatment for postpartum depression?", response: "Prevention is recommended for those with: a history of postpartum or major depression, depression during pregnancy, bipolar disorder, or significant psychosocial stressors. Early intervention reduces recurrence risk." },
  { id: 1533, category: 'postpartum', keywords: ['antidepressants to prevent postpartum depression'], question: "Can antidepressants prevent postpartum depression?", response: "For those with a history of severe postpartum depression, starting antidepressants immediately after delivery can significantly reduce recurrence risk. This should be discussed during pregnancy with a psychiatrist." },
  { id: 1534, category: 'postpartum', keywords: ['psychotherapy to prevent postpartum depression'], question: "Can therapy prevent postpartum depression?", response: "Yes. Starting CBT or IPT during pregnancy significantly reduces the risk of developing postpartum depression, especially for those with a history of depression or current mild symptoms." },
  { id: 1535, category: 'postpartum', keywords: ['mindfulness to prevent postpartum depression'], question: "Does mindfulness help prevent postpartum depression?", response: "Mindfulness-based interventions during pregnancy show promise in reducing postpartum depression risk. They help with stress management, emotional regulation, and present-moment awareness." },
  { id: 1536, category: 'postpartum', keywords: ['psychosocial support to prevent postpartum depression'], question: "What role does support play in preventing postpartum depression?", response: "Strong social support is protective. This includes partner support, family help, peer groups, and professional support. Practical help with baby care and household tasks reduces stress and isolation." },
  { id: 1537, category: 'postpartum', keywords: ['omega-3 for preventing postpartum depression'], question: "Do omega-3 supplements prevent postpartum depression?", response: "Evidence is mixed. Some studies suggest omega-3s may help, but they are not considered a standalone preventive treatment. They can be part of a comprehensive approach including therapy and support." },
  { id: 1538, category: 'postpartum', keywords: ['exercise for preventing postpartum depression'], question: "Can exercise prevent postpartum depression?", response: "Regular physical activity during and after pregnancy is associated with lower depression risk. Even moderate exercise like walking can improve mood and reduce stress, though it's not a replacement for treatment in high-risk individuals." },
  { id: 1539, category: 'postpartum', keywords: ['planning ahead to prevent postpartum depression'], question: "How can I plan ahead to prevent postpartum depression?", response: "Create a postpartum plan that includes: arranging support, planning for sleep, identifying warning signs, scheduling follow-up appointments, and discussing medication decisions with your provider before delivery." },
  { id: 1540, category: 'postpartum', keywords: ['what does not prevent postpartum depression'], question: "Do supplements or exercise prevent postpartum depression?", response: "Current evidence does not show that omega-3 supplements, selenium, or exercise alone reliably prevent postpartum depression. They may support overall health but are not considered effective standalone prevention strategies." },
  { id: 1541, category: 'postpartum', keywords: ['early intervention for postpartum depression prevention'], question: "How early should prevention start for postpartum depression?", response: "Prevention should begin during pregnancy, ideally in the second trimester. Early identification of risk factors and starting therapy or medication before delivery provides the best protection." },
  { id: 1542, category: 'postpartum', keywords: ['partner support for preventing postpartum depression'], question: "How can partners help prevent postpartum depression?", response: "Partners can help by: attending prenatal appointments, learning about postpartum depression, planning for practical support, being emotionally available, and encouraging professional help if warning signs appear." },
  { id: 1543, category: 'postpartum', keywords: ['high-risk prevention postpartum depression'], question: "What's recommended for someone at very high risk of postpartum depression?", response: "For very high-risk individuals (severe prior PPD, bipolar disorder), a combination approach is best: prophylactic antidepressants starting at delivery, ongoing therapy, close monitoring, and strong support systems." },

  // === Postpartum Depression: Adverse Consequences (IDs 1544–1558) ===
  { id: 1544, category: 'postpartum', keywords: ['postpartum depression and maternal infant bonding'], question: "How does postpartum depression affect bonding with the baby?", response: "Postpartum depression can interfere with maternal-infant bonding. Mothers may have difficulty feeling connected, responding to cues, or enjoying time with their baby. This is treatable, and bonding can improve with treatment." },
  { id: 1545, category: 'postpartum', keywords: ['postpartum depression and breastfeeding'], question: "Does postpartum depression affect breastfeeding?", response: "It is associated with lower rates of starting breastfeeding and shorter duration. Many depressed mothers still want to breastfeed and can succeed with the right support and treatment." },
  { id: 1546, category: 'postpartum', keywords: ['postpartum depression and partner relationship'], question: "How does postpartum depression affect relationships?", response: "It can strain partner relationships through increased conflict, reduced intimacy, and communication difficulties. Partner involvement in treatment can improve both the relationship and maternal outcomes." },
  { id: 1547, category: 'postpartum', keywords: ['postpartum depression and suicide risk'], question: "Can postpartum depression lead to suicide?", response: "Yes. Suicide is a leading cause of maternal mortality. Severe depression, especially with thoughts of self-harm, requires immediate professional help. Call 988 or go to the ER if you have these thoughts." },
  { id: 1548, category: 'postpartum', keywords: ['postpartum depression and child cognitive development'], question: "How does postpartum depression affect child cognitive development?", response: "Untreated postpartum depression is associated with delays in cognitive development, including lower scores on developmental assessments. Early treatment protects against these effects." },
  { id: 1549, category: 'postpartum', keywords: ['postpartum depression and child behavioral problems'], question: "Does postpartum depression cause behavioral problems in children?", response: "Children of mothers with untreated postpartum depression have higher rates of behavioral problems, including hyperactivity and conduct issues. Treatment reduces this risk." },
  { id: 1550, category: 'postpartum', keywords: ['postpartum depression and child emotional development'], question: "How does postpartum depression affect a child's emotional development?", response: "It can increase the risk of emotional difficulties in children, including anxiety, depression, and difficulty regulating emotions. Secure attachment and early intervention protect against these outcomes." },
  { id: 1551, category: 'postpartum', keywords: ['postpartum depression and infant sleep'], question: "Does postpartum depression affect infant sleep?", response: "Maternal depression is associated with more infant sleep problems. This can create a cycle where poor sleep worsens maternal mood. Addressing both maternal depression and infant sleep can help break this cycle." },
  { id: 1552, category: 'postpartum', keywords: ['postpartum depression and language development'], question: "Can postpartum depression affect language development?", response: "Some studies show delays in language development in children of mothers with untreated postpartum depression. Early treatment and responsive interaction support healthy language development." },
  { id: 1553, category: 'postpartum', keywords: ['postpartum depression and attachment security'], question: "How does postpartum depression affect attachment?", response: "Untreated depression increases the risk of insecure attachment. However, treatment improves maternal sensitivity and attachment outcomes. It's never too late to seek help." },
  { id: 1554, category: 'postpartum', keywords: ['long-term effects of postpartum depression on children'], question: "What are the long-term effects of postpartum depression on children?", response: "Untreated postpartum depression is associated with increased risk of mental health issues, academic difficulties, and social problems in childhood and adolescence. Early treatment significantly reduces these risks." },
  { id: 1555, category: 'postpartum', keywords: ['postpartum depression and parenting quality'], question: "Does postpartum depression affect parenting quality?", response: "Depression can reduce sensitive, responsive parenting. Mothers may be less engaged or more intrusive. Treatment improves parenting quality and parent-child interactions." },
  { id: 1556, category: 'postpartum', keywords: ['postpartum depression and family functioning'], question: "How does postpartum depression affect the whole family?", response: "It impacts the entire family system, including partner mental health, sibling relationships, and overall family functioning. Family-based treatment approaches can address these broader impacts." },
  { id: 1557, category: 'postpartum', keywords: ['postpartum depression and economic impact'], question: "What is the economic impact of postpartum depression?", response: "Postpartum depression has significant economic costs through healthcare utilization, lost productivity, and impacts on child development. Investment in prevention and treatment provides substantial societal benefits." },
  { id: 1558, category: 'postpartum', keywords: ['postpartum depression and breastfeeding'], question: "Does postpartum depression affect breastfeeding?", response: "It is associated with lower rates of starting breastfeeding and shorter duration. Many depressed mothers still want to breastfeed and can succeed with the right support and treatment." },

  // === Postpartum Contraception (IDs 1559–1581) ===
  { id: 1559, category: 'postpartum', keywords: ['when does ovulation return after birth'], question: "When can I get pregnant again after giving birth?", response: "Ovulation can return as early as 25 days after delivery in non-breastfeeding people, though it's more commonly around 45–94 days. You can get pregnant before your first period returns, which is why starting contraception on time is important." },
  { id: 1560, category: 'postpartum', keywords: ['why start contraception soon after birth'], question: "Why is it important to start contraception soon after giving birth?", response: "Many people resume sex before their 6-week checkup, and ovulation can return early. Starting effective contraception before you leave the hospital or at your early postpartum visit helps prevent unintended pregnancy and supports healthy birth spacing." },
  { id: 1561, category: 'postpartum', keywords: ['how soon after birth can I have sex'], question: "When is it safe to have sex again after giving birth?", response: "Most providers recommend waiting until bleeding stops and any tears or incisions have healed — usually around 4–6 weeks. Go at your own pace and use lubrication if you're breastfeeding. Talk to your provider about contraception before resuming sex." },
  { id: 1562, category: 'postpartum', keywords: ['how to choose postpartum contraception'], question: "How should I choose which birth control to use after having a baby?", response: "Think about whether you want more children and when, what's most important to you (effectiveness, convenience, no hormones, etc.), your medical history, and whether you're breastfeeding. A shared decision-making conversation with your provider helps match the best method to your life." },
  { id: 1563, category: 'postpartum', keywords: ['reproductive life plan after birth'], question: "What is a reproductive life plan and why does it matter after having a baby?", response: "It's a conversation about whether and when you want more children. Discussing this during pregnancy or right after birth helps you choose contraception that fits your goals and supports healthy spacing between pregnancies (ideally at least 18–24 months)." },
  { id: 1564, category: 'postpartum', keywords: ['tubal ligation after birth'], question: "Can I get my tubes tied right after giving birth?", response: "Yes. Permanent contraception (tubal ligation or salpingectomy) can be done right after a vaginal or cesarean birth. It's highly effective. If you're sure you don't want more children, discuss this option during pregnancy so it can be arranged." },
  { id: 1565, category: 'postpartum', keywords: ['vasectomy after partner gives birth'], question: "Can my partner get a vasectomy after I have the baby?", response: "Yes. Vasectomy is a simple, highly effective permanent option for male partners. It can be done anytime and has very low risk. It's a good choice if you're certain you don't want more children together." },
  { id: 1566, category: 'postpartum', keywords: ['IUD right after birth'], question: "Can I get an IUD placed right after giving birth?", response: "Yes. An IUD (copper or hormonal) can be placed immediately after delivery of the placenta. This is called postplacental placement. It's safe and convenient, though there is a higher chance of the IUD coming out (expulsion) compared with placement at 6 weeks." },
  { id: 1567, category: 'postpartum', keywords: ['IUD expulsion after birth'], question: "What are the chances my IUD will fall out if I get it right after birth?", response: "Expulsion risk is higher with immediate placement (roughly 10–15% in the first year) compared with placement at 6+ weeks. It's still lower than the risk of unintended pregnancy if you don't have reliable contraception. Many people still successfully use an IUD placed right after birth." },
  { id: 1568, category: 'postpartum', keywords: ['when to check IUD strings after birth'], question: "When should I have my IUD checked after getting it right after birth?", response: "Many providers recommend an ultrasound or string check around 4–6 weeks postpartum to confirm position, especially after immediate placement. Let your provider know if you can't feel the strings or have pain or bleeding." },
  { id: 1569, category: 'postpartum', keywords: ['IUD perforation after birth'], question: "Is there a higher risk of IUD perforation if placed after giving birth?", response: "The overall risk of perforation is low. Some studies show a slightly higher risk with placement between 4–8 weeks postpartum compared with later placement, but it remains uncommon. Breastfeeding may slightly increase risk, but the absolute numbers are still very small." },
  { id: 1570, category: 'postpartum', keywords: ['birth control implant after birth'], question: "Can I get the birth control implant right after having my baby?", response: "Yes. The etonogestrel implant (Nexplanon) can be placed anytime after delivery, including before you go home. It's highly effective, long-acting, and doesn't affect breastfeeding." },
  { id: 1571, category: 'postpartum', keywords: ['Depo shot after birth'], question: "Can I get the Depo-Provera shot right after giving birth?", response: "Yes. The progestin injection can be given immediately after delivery. It provides 3 months of contraception and can be a good bridge until your postpartum visit. Discuss any concerns about mood changes with your provider." },
  { id: 1572, category: 'postpartum', keywords: ['progestin only pill after birth'], question: "Can I start the mini-pill right after giving birth?", response: "Yes. Progestin-only pills can be started immediately after delivery. They are safe while breastfeeding. Remember to take them at the same time every day for best effectiveness." },
  { id: 1573, category: 'postpartum', keywords: ['when can I start combined birth control after birth'], question: "When can I start the regular birth control pill, patch, or ring after giving birth?", response: "You should wait at least 3 weeks (21 days) after delivery to start any estrogen-containing method because of increased blood clot risk. If you have additional risk factors, your provider may recommend waiting 6 weeks." },
  { id: 1574, category: 'postpartum', keywords: ['does hormonal birth control affect breastfeeding'], question: "Will hormonal birth control affect my milk supply?", response: "Most progestin-only methods (implant, IUD, mini-pill, shot) have little to no effect on milk supply for most people. Estrogen-containing methods may have more impact and are usually delayed until breastfeeding is well established. Discuss your priorities with your provider." },
  { id: 1575, category: 'postpartum', keywords: ['best birth control while breastfeeding'], question: "What's the best birth control if I'm breastfeeding?", response: "Progestin-only methods (implant, hormonal IUD, mini-pill, shot) and non-hormonal options (copper IUD, condoms) are excellent choices. They don't significantly affect milk supply for most people and are safe while breastfeeding." },
  { id: 1576, category: 'postpartum', keywords: ['blood clot risk and birth control after birth'], question: "Why can't I start estrogen birth control right after having a baby?", response: "Your risk of blood clots is naturally higher in the weeks after delivery. Adding estrogen further increases that risk, so it's safest to wait at least 3 weeks (longer if you have other risk factors) before starting any estrogen-containing method." },
  { id: "Yes. Both the copper IUD and levonorgestrel pill are safe options postpartum. Ulipristal (ella) is also an option, but you should pump and discard breast milk for 24 hours after taking it if you're breastfeeding." },
  { id: 1578, category: 'postpartum', keywords: ['birth control for teens after birth'], question: "What birth control options are best for young parents after having a baby?", response: "Long-acting reversible contraception (IUD or implant) placed right after birth is highly effective and helps prevent repeat pregnancy. All methods are available — the best choice depends on the individual's preferences and life situation." },
  { id: 1579, category: 'postpartum', keywords: ['birth control with history of depression'], question: "Can I use hormonal birth control if I have a history of depression or postpartum depression?", response: "Yes. Hormonal contraception is generally considered safe for people with depression. There is no clear evidence that most methods worsen mood, though individual responses vary. Discuss any concerns with your provider." },
  { id: 1580, category: 'postpartum', keywords: ['what if I am unsure about birth control after birth'], question: "What if I'm not sure what birth control I want after having my baby?", response: "That's okay. You can start with a highly effective method like an implant or IUD (which can be removed later) while you decide. You can also use condoms or abstinence in the short term. Talk with your provider at your postpartum visits — you don't have to decide everything at once." },
  { id: 1581, category: 'postpartum', keywords: ['birth spacing after having a baby'], question: "How long should I wait before getting pregnant again?", response: "Most experts recommend waiting at least 18–24 months after a birth before trying to conceive again. This gives your body time to recover and is associated with better outcomes for both mother and baby." },

  // === Treatment of Mild–Moderate Postpartum Depression (IDs 1582–1599) ===
  { id: 1582, category: 'postpartum', keywords: ['mild vs moderate vs severe postpartum depression'], question: "How do I know if my postpartum depression is mild, moderate, or severe?", response: "Mild to moderate depression usually involves 5–6 symptoms and you can still function day-to-day, though it's hard. Severe depression involves more symptoms, significant impairment, and often thoughts of self-harm. Your provider can help assess severity using tools like the Edinburgh scale or PHQ-9." },
  { id: 1583, category: 'postpartum', keywords: ['postpartum blues vs postpartum depression'], question: "What's the difference between baby blues and postpartum depression?", response: "Baby blues are mild mood swings, tearfulness, and irritability that usually start a few days after birth and go away within two weeks. Postpartum depression is more intense, lasts longer than two weeks, and interferes with functioning or bonding. If symptoms persist or worsen, get evaluated." },
  { id: 1584, category: 'postpartum', keywords: ['psychotherapy for postpartum depression'], question: "Is therapy effective for postpartum depression?", response: "Yes. Psychotherapy, especially Cognitive Behavioral Therapy (CBT) and Interpersonal Psychotherapy (IPT), is an effective first-line treatment for mild to moderate postpartum depression. Many women prefer therapy, especially while breastfeeding." },
  { id: 1585, category: 'postpartum', keywords: ['CBT for postpartum depression'], question: "What is CBT and how does it help with postpartum depression?", response: "Cognitive Behavioral Therapy (CBT) helps you identify and change unhelpful thought patterns and behaviors that fuel depression. It is one of the most well-studied and effective therapies for postpartum depression and can be done individually or in groups." },
  { id: 1586, category: 'postpartum', keywords: ['interpersonal therapy for postpartum depression'], question: "What is interpersonal therapy (IPT) for postpartum depression?", response: "Interpersonal Psychotherapy (IPT) focuses on relationship changes, role transitions (like becoming a parent), and interpersonal issues that contribute to depression. It is highly effective for postpartum depression and helps improve both mood and relationships." },
  { id: 1587, category: 'postpartum', keywords: ['antidepressants for mild moderate postpartum depression'], question: "Do I need medication for mild to moderate postpartum depression?", response: "Medication is not always required. Many women do well with therapy alone. Antidepressants are a reasonable option if therapy isn't enough, isn't available, or if you've responded well to them in the past. Most are considered compatible with breastfeeding when monitored." },
  { id: 1588, category: 'postpartum', keywords: ['zuranolone for postpartum depression'], question: "What is zuranolone and is it used for postpartum depression?", response: "Zuranolone is a newer oral medication specifically approved for postpartum depression. It is taken for a short course (usually 14 days). It may be an option for some women, but discuss risks, benefits, and breastfeeding compatibility with your provider." },
  { id: 1589, category: 'postpartum', keywords: ['behavioral activation for postpartum depression'], question: "What is behavioral activation and how can it help?", response: "Behavioral activation is a therapy that helps you gradually re-engage in rewarding activities and break the cycle of withdrawal and low mood. It can be very effective for postpartum depression, either on its own or as part of CBT." },
  { id: 1590, category: 'postpartum', keywords: ['exercise for postpartum depression'], question: "Can exercise help with postpartum depression?", response: "Yes. Regular exercise (walking, yoga, strength training) can reduce depressive symptoms in postpartum women. Even modest activity helps. It works best when combined with other treatments like therapy or social support." },
  { id: 1591, category: 'postpartum', keywords: ['peer support for postpartum depression'], question: "Does talking to other moms help with postpartum depression?", response: "Yes. Peer support and mother-to-mother groups can reduce feelings of isolation and improve symptoms. Connecting with others who understand what you're going through is often very helpful alongside professional treatment." },
  { id: 1592, category: 'postpartum', keywords: ['parenting support and postpartum depression'], question: "Can learning parenting skills help my mood?", response: "Yes. Programs that teach practical parenting skills (especially around infant sleep, crying, and soothing) can reduce stress and improve mood in mothers with postpartum depression by increasing confidence and sense of control." },
  { id: 1593, category: 'postpartum', keywords: ['monitoring postpartum depression treatment'], question: "How will my provider know if treatment is working?", response: "Your provider will use tools like the Edinburgh Postnatal Depression Scale or PHQ-9 to track your symptoms over time. You should notice gradual improvement. Regular check-ins help adjust the plan if needed." },
  { id: 1594, category: 'postpartum', keywords: ['what if therapy is not helping enough'], question: "What if therapy isn't helping my postpartum depression enough?", response: "If you're only getting partial improvement, your provider may increase session frequency, add more sessions, switch therapy type, or add medication. Don't give up — many women need a combination or adjustment of treatments to feel better." },
  { id: 1595, category: 'postpartum', keywords: ['what if nothing is helping postpartum depression'], question: "What if my postpartum depression isn't getting better with treatment?", response: "If symptoms persist despite therapy and/or medication, your provider may refer you to a perinatal psychiatrist, consider additional options, or evaluate for other contributing factors. More intensive support or different treatments can still help." },
  { id: 1596, category: 'postpartum', keywords: ['how long to stay on treatment after postpartum depression'], question: "How long should I stay on treatment after postpartum depression improves?", response: "Many women continue treatment for 6–24 months after feeling better to reduce the risk of recurrence. Your provider will work with you to decide the right duration based on your history and risk factors." },
  { id: 1597, category: 'postpartum', keywords: ['planning for future pregnancies after postpartum depression'], question: "What should I do if I want another baby after having postpartum depression?", response: "Talk with your provider before trying to conceive again. Many women restart or continue preventive treatment (therapy and/or medication) during pregnancy and after birth. Planning ahead significantly reduces the chance of recurrence." },
  { id: 1598, category: 'postpartum', keywords: ['therapy while breastfeeding postpartum depression'], question: "Can I do therapy while breastfeeding?", response: "Yes. Therapy (CBT, IPT, etc.) has no impact on breastfeeding and is often the preferred first treatment for breastfeeding mothers with mild to moderate postpartum depression." },
  { id: 1599, category: 'postpartum', keywords: ['medication safety while breastfeeding postpartum depression'], question: "Is it safe to take antidepressants while breastfeeding?", response: "Most antidepressants are considered compatible with breastfeeding. The amount that passes into breast milk is usually low, and benefits of treating depression generally outweigh risks. Your provider and pediatrician can help choose the safest option and monitor your baby." },

  // === NEW UpToDate Treatment of Postpartum Psychosis RAG Entries (IDs 1611–1628) ===
  // Emergency Nature & Safety
  { id: 1611, category: 'postpartum', keywords: ['postpartum psychosis emergency'], question: "Is postpartum psychosis a medical emergency?", response: "Yes. Postpartum psychosis is a psychiatric emergency. It usually starts suddenly within the first few weeks after birth and can involve confusion, hallucinations, delusions, and disorganized thinking. Immediate evaluation and treatment are needed to protect the mother and baby." },
  { id: 1612, category: 'postpartum', keywords: ['hospitalization for postpartum psychosis'], question: "Do I need to go to the hospital if I have postpartum psychosis?", response: "In most cases, yes. Hospitalization is usually recommended so the mother can be kept safe and treated quickly. The baby should not be left alone with someone experiencing postpartum psychosis until symptoms are under control." },
  { id: 1613, category: 'postpartum', keywords: ['mother baby separation postpartum psychosis'], question: "Will I be separated from my baby if I have postpartum psychosis?", response: "Temporarily, yes — for safety. While separation is difficult, it is often necessary until the mother is stable. Many hospitals try to support supervised visits when it is safe. The goal is always to reunite mother and baby as soon as it is safe to do so." },

  // Initial Medication Approach
  { id: 1614, category: 'postpartum', keywords: ['lithium and antipsychotic for postpartum psychosis'], question: "What is the usual medication treatment for postpartum psychosis?", response: "The preferred initial treatment is usually a combination of lithium and a second-generation antipsychotic. This approach is used because many people with postpartum psychosis later receive a diagnosis of bipolar disorder." },
  { id: 1615, category: 'postpartum', keywords: ['why lithium for postpartum psychosis'], question: "Why is lithium used in postpartum psychosis?", response: "Lithium is often added because postpartum psychosis is strongly linked to bipolar disorder. Studies show that adding lithium significantly improves outcomes and helps maintain stability after the acute episode." },
  { id: 1616, category: 'postpartum', keywords: ['second generation antipsychotic postpartum psychosis'], question: "Which antipsychotic is best for postpartum psychosis?", response: "Second-generation antipsychotics (such as olanzapine, quetiapine, or lurasidone) are generally preferred because they tend to have fewer movement-related side effects. The specific choice depends on the person's symptoms, other health conditions, and whether they are breastfeeding." },

  // Special Situations
  { id: 1617, category: 'postpartum', keywords: ['postpartum psychosis with depression'], question: "What if postpartum psychosis comes with strong depressive symptoms?", response: "If there are clear depressive symptoms (such as anhedonia or thoughts of self-harm), an SSRI antidepressant may be added after starting lithium and an antipsychotic. However, if there is emotional lability or irritability, antidepressants are usually avoided because they can worsen symptoms or trigger mania." },
  { id: 1618, category: 'postpartum', keywords: ['lithium monotherapy postpartum psychosis'], question: "Can lithium be used alone for postpartum psychosis?", response: "Sometimes, but only in mild cases with very little disorganization. Most people need both lithium and an antipsychotic. Lithium monotherapy is used infrequently and requires close monitoring." },
  { id: 1619, category: 'postpartum', keywords: ['antipsychotic alone postpartum psychosis'], question: "What if someone can't take lithium?", response: "If lithium is not an option (for example, due to kidney problems), treatment starts with a second-generation antipsychotic alone. If that is not enough, another medication such as valproate may be considered, though it is usually avoided long-term due to risks in future pregnancies." },

  // Insomnia & Agitation
  { id: 1620, category: 'postpartum', keywords: ['benzodiazepines for insomnia in postpartum psychosis'], question: "What helps with severe insomnia or agitation in postpartum psychosis?", response: "A short-acting benzodiazepine (such as lorazepam) is often added to help restore sleep and reduce agitation. Good sleep is very important in recovery from postpartum psychosis." },

  // Next Steps & Inadequate Response
  { id: 1621, category: 'postpartum', keywords: ['what if treatment is not working for postpartum psychosis'], question: "What if someone isn't getting better with lithium and an antipsychotic?", response: "The team may switch to a different antipsychotic and strongly consider electroconvulsive therapy (ECT). ECT can work more quickly than medications and is especially useful when there is high risk of harm to self or baby." },
  { id: 1622, category: 'postpartum', keywords: ['ECT for postpartum psychosis'], question: "Is ECT used for postpartum psychosis?", response: "Yes. Electroconvulsive therapy (ECT) is an effective and relatively fast treatment for postpartum psychosis when medications are not enough or when rapid improvement is needed for safety. It is generally considered safe in the postpartum period." },

  // Continuation & Maintenance
  { id: 1623, category: 'postpartum', keywords: ['how long to stay on medication after postpartum psychosis'], question: "How long do I need to stay on medication after postpartum psychosis?", response: "After a good response, the antipsychotic is usually continued for at least 3–6 months and lithium for at least 9–12 months. Some people need longer treatment, especially if they have an underlying bipolar diagnosis or high risk of recurrence." },
  { id: 1624, category: 'postpartum', keywords: ['psychotherapy after postpartum psychosis'], question: "Is therapy helpful after postpartum psychosis?", response: "Yes. Once acute symptoms are under control, psychotherapy (focused on education, support, and medication adherence) is recommended as an important part of recovery and relapse prevention." },

  // Breastfeeding
  { id: 1625, category: 'postpartum', keywords: ['breastfeeding with postpartum psychosis'], question: "Can I breastfeed if I have postpartum psychosis?", response: "It depends on safety and stability. Many women can breastfeed while taking antipsychotics or lithium, but some with more severe symptoms may need to pause until they are more stable. The decision should be made with the care team, weighing risks and benefits." },
  { id: 1626, category: 'postpartum', keywords: ['medication safety while breastfeeding postpartum psychosis'], question: "Are antipsychotics and lithium safe while breastfeeding?", response: "Most antipsychotics and many antidepressants pass into breast milk in low amounts with minimal short-term effects on the baby. Lithium has more uncertainty. Decisions are made case-by-case with close monitoring of the infant. Never stop medication without medical advice." },

  // General Support & Planning
  { id: 1627, category: 'postpartum', keywords: ['planning future pregnancies after postpartum psychosis'], question: "What if I want another baby after having postpartum psychosis?", response: "This requires careful planning with a perinatal psychiatrist. Many women stay on mood stabilizers (especially lithium) during and after pregnancy to prevent recurrence. Early and proactive care greatly improves outcomes." },
  { id: 1628, category: 'postpartum', keywords: ['support for family after postpartum psychosis'], question: "How can family support someone with postpartum psychosis?", response: "Family support is essential. Help with practical tasks, encourage medication adherence, watch for warning signs of relapse, and support the mother emotionally without judgment. Professional guidance for the whole family is often beneficial." },

  // === NEW UpToDate Headache in Pregnancy & Postpartum RAG Entries (IDs 1646–1660) ===
  // Red Flags & When to Seek Care
  { id: 1646, category: 'pregnancy', keywords: ['headache in pregnancy when to worry'], question: "When should I worry about a headache during pregnancy?", response: "Any new or severe headache after 20 weeks needs prompt evaluation to rule out preeclampsia. Also seek care for sudden severe headache, vision changes, confusion, neck stiffness, seizures, or headache with high blood pressure. These can signal serious problems." },
  { id: 1647, category: 'pregnancy', keywords: ['preeclampsia headache symptoms'], question: "What does a preeclampsia headache feel like?", response: "It is often constant, throbbing, and felt all over the head. It may come with vision changes, upper belly pain, swelling, or high blood pressure. Any headache after 20 weeks should be checked, especially with these other symptoms." },
  { id: 1648, category: 'postpartum', keywords: ['postpartum headache red flags'], question: "When is a headache after birth concerning?", response: "Seek care for severe or worsening headache, vision changes, confusion, seizures, high blood pressure, or headache with neck stiffness. These can signal preeclampsia, blood clots, or other serious issues. Post-dural puncture headache (from epidural/spinal) is also common and treatable." },

  // Migraine in Pregnancy
  { id: 1649, category: 'pregnancy', keywords: ['migraine during pregnancy what to expect'], question: "What usually happens to migraines during pregnancy?", response: "Many women (60–70%) notice improvement, especially in the second and third trimesters. Some stay the same, and a small number worsen. Migraines often return in the first week or month after delivery, especially if you're not breastfeeding." },
  { id: 1650, category: 'pregnancy', keywords: ['safe migraine treatment in pregnancy'], question: "What can I safely take for migraine while pregnant?", response: "Acetaminophen is the safest first choice. If it's not enough, your provider may add metoclopramide or consider a short course of certain other medications depending on how far along you are. Triptans can be used in some cases when benefits outweigh risks. Always check with your provider before taking anything." },
  { id: 1651, category: 'pregnancy', keywords: ['triptans in pregnancy'], question: "Are triptans safe during pregnancy?", response: "Sumatriptan has the most safety data and is often considered acceptable when other treatments fail. Other triptans may also be used. Your provider will weigh the benefits and risks based on your specific situation and gestational age." },
  { id: 1652, category: 'pregnancy', keywords: ['preventive migraine treatment pregnancy'], question: "What can I take daily to prevent migraines while pregnant?", response: "Beta blockers (like propranolol) and some calcium channel blockers are commonly used. Certain antidepressants or nutraceuticals (magnesium, riboflavin) may also be options. Preventive treatment is usually reserved for frequent or disabling migraines. Discuss options with your provider." },

  // Tension-Type Headache
  { id: 1653, category: 'pregnancy', keywords: ['tension headache in pregnancy'], question: "How are tension headaches treated during pregnancy?", response: "Acetaminophen is the first-line treatment. Non-medication approaches like rest, heat/ice, massage, hydration, and stress reduction are also very helpful. Tension headaches often stay stable or improve slightly during pregnancy." },

  // Cluster Headache
  { id: 1654, category: 'pregnancy', keywords: ['cluster headache pregnancy'], question: "What helps with cluster headaches during pregnancy?", response: "100% oxygen is often the safest and most effective abortive treatment. Sumatriptan can be considered if oxygen isn't enough. Preventive options include verapamil or short courses of steroids after the first trimester. Ergotamine should be avoided." },

  // Postpartum Headache
  { id: 1655, category: 'postpartum', keywords: ['post dural puncture headache'], question: "What is a post-dural puncture headache and how is it treated?", response: "It's a headache that worsens when sitting or standing and improves when lying flat. It can occur after an epidural or spinal. Treatment often includes hydration, caffeine, and sometimes a blood patch. It's very treatable and breastfeeding is not a contraindication." },
  { id: 1656, category: 'postpartum', keywords: ['headache while breastfeeding what is safe'], question: "What headache medications are safe while breastfeeding?", response: "Acetaminophen and ibuprofen are generally safe. Some triptans are acceptable with timing adjustments. Avoid ergotamine and limit opioids. Always check with your provider or a lactation consultant before taking medication." },

  // General Safety Principles
  { id: 1657, category: 'pregnancy', keywords: ['headache medication safety by trimester'], question: "Which headache medications are safest in each trimester?", response: "Acetaminophen is safest throughout pregnancy. NSAIDs are generally avoided after 20 weeks. Triptans and certain other medications may be used when benefits outweigh risks. Your provider will choose based on gestational age, severity, and your overall health." },
  { id: 1658, category: 'pregnancy', keywords: ['non medication ways to treat headache in pregnancy'], question: "What can I do for headache without medication during pregnancy?", response: "Rest in a dark, quiet room, apply cold or warm compresses, stay hydrated, eat regular meals, maintain consistent sleep, reduce stress, and try gentle massage or relaxation techniques. These approaches are safe and often helpful." },

  // Medication Overuse
  { id: 1659, category: 'pregnancy', keywords: ['medication overuse headache pregnancy'], question: "Can taking pain medicine too often cause more headaches in pregnancy?", response: "Yes. Frequent use of pain relievers (even acetaminophen) can lead to medication overuse headaches. If you're using headache medication more than a couple of times per week, talk to your provider about preventive strategies and safer long-term options." },

  // When to Get Help
  { id: 1660, category: 'pregnancy', keywords: ['when to go to hospital for headache pregnant'], question: "When should I go to the hospital for a headache while pregnant or postpartum?", response: "Go if the headache is sudden and severe, comes with vision changes, confusion, seizures, high blood pressure, neck stiffness, or if it's the worst headache of your life. These symptoms need urgent evaluation to rule out serious causes." },

  // === NEW UpToDate Perinatal OCD RAG Entries (IDs 1661–1674) ===
  // Common Intrusive Thoughts vs OCD
  { id: 1661, category: 'postpartum', keywords: ['intrusive thoughts about harming baby normal'], question: "Is it normal to have scary thoughts about harming my baby?", response: "Yes — fleeting, unwanted thoughts of accidental harm to the baby are extremely common in new mothers, even those without any mental health history. These thoughts do not mean you will act on them. However, if the thoughts are frequent, very distressing, and lead to compulsive behaviors, it may be perinatal OCD." },
  { id: 1662, category: 'postpartum', keywords: ['postpartum OCD vs normal intrusive thoughts'], question: "How is postpartum OCD different from normal scary thoughts about the baby?", response: "In normal intrusive thoughts, the ideas are occasional and quickly dismissed. In perinatal OCD, the thoughts are frequent, cause intense anxiety or guilt, and lead to repetitive behaviors (like excessive checking, avoiding the baby, or mental rituals) that interfere with daily life and bonding." },

  // Symptoms in Pregnancy vs Postpartum
  { id: 1663, category: 'pregnancy', keywords: ['OCD symptoms during pregnancy'], question: "What does OCD look like during pregnancy?", response: "Common obsessions include fears of fetal harm, contamination, or miscarriage. Compulsions often involve excessive checking on the baby's well-being, repeated cleaning, or ritualized behaviors to 'protect' the pregnancy." },
  { id: 1664, category: 'postpartum', keywords: ['postpartum OCD harm thoughts'], question: "What kind of thoughts occur in postpartum OCD?", response: "Many women experience vivid, unwanted thoughts or images of accidentally or intentionally harming their baby (e.g., dropping the baby, drowning, or suffocating). These thoughts are extremely distressing and ego-dystonic (feel foreign and unwanted). They do not predict actual harm." },

  // Differentiation from Postpartum Psychosis
  { id: 1665, category: 'postpartum', keywords: ['postpartum OCD vs postpartum psychosis'], question: "How is postpartum OCD different from postpartum psychosis?", response: "In OCD, the thoughts are unwanted, resisted, and cause great distress (ego-dystonic). The mother usually has good insight and would never act on them. In postpartum psychosis, thoughts may feel real or justified (ego-syntonic), insight is often poor, and there is higher risk of acting on delusions. This distinction is critical for safety." },

  // Screening & Assessment
  { id: 1666, category: 'postpartum', keywords: ['screening for perinatal OCD'], question: "How is perinatal OCD screened for?", response: "There is no universal standard, but brief questions about intrusive thoughts (especially harm-related) can be helpful. The Perinatal Obsessive-Compulsive Scale (POCS) is a validated tool specifically designed for pregnancy and postpartum. Any positive screen should lead to a full clinical assessment." },
  { id: 1667, category: 'postpartum', keywords: ['assessing risk in perinatal OCD'], question: "How do clinicians assess safety when someone has thoughts of harming their baby?", response: "Clinicians evaluate frequency, intensity, insight, and whether the person is acting on or avoiding the thoughts. They also assess for comorbid depression or psychosis. Most women with OCD have good insight and are at low risk of acting on harm thoughts, but a full evaluation is essential." },

  // Treatment
  { id: 1668, category: 'postpartum', keywords: ['treatment of perinatal OCD'], question: "How is OCD treated during pregnancy and after birth?", response: "Cognitive Behavioral Therapy with Exposure and Response Prevention (ERP) is the first-line treatment. When symptoms are severe, comorbid depression is present, or therapy access is limited, SSRIs are added. Treatment decisions balance the risks of medication against the risks of untreated OCD." },
  { id: 1669, category: 'postpartum', keywords: ['CBT for postpartum OCD'], question: "Is therapy effective for postpartum OCD?", response: "Yes. CBT with Exposure and Response Prevention is highly effective. It helps women understand that intrusive thoughts are common and not dangerous, and reduces compulsive behaviors. Therapy is often preferred during pregnancy and breastfeeding when possible." },
  { id: 1670, category: 'postpartum', keywords: ['SSRIs for perinatal OCD'], question: "Are antidepressants safe for OCD during pregnancy or breastfeeding?", response: "SSRIs are generally considered compatible with pregnancy and breastfeeding when clinically indicated. Sertraline is often preferred due to lower passage into breast milk. The decision involves weighing benefits of treating OCD against potential risks, ideally with shared decision-making." },

  // Impact on Mother-Infant Relationship
  { id: 1671, category: 'postpartum', keywords: ['postpartum OCD and bonding with baby'], question: "Can postpartum OCD affect bonding with my baby?", response: "Yes. Avoidance of the baby, excessive checking, or mental rituals can interfere with bonding and responsive parenting. Early treatment helps protect the mother-infant relationship. Dyadic therapy or infant massage can be helpful adjuncts in some cases." },
  { id: 1672, category: 'postpartum', keywords: ['does postpartum OCD mean I will hurt my baby'], question: "If I have OCD thoughts about harming my baby, does that mean I'm dangerous?", response: "No. In OCD, these thoughts are unwanted and cause intense distress. They do not predict harmful behavior. Women with OCD almost always have good insight and would never intentionally harm their child. Postpartum psychosis is different and carries higher risk." },

  // Prognosis & Support
  { id: 1673, category: 'postpartum', keywords: ['prognosis of perinatal OCD'], question: "What is the outlook for someone with perinatal OCD?", response: "With proper treatment (especially CBT ± medication), most women improve significantly. Untreated OCD can affect bonding and increase risk of postpartum depression. Early recognition and treatment lead to better outcomes for both mother and baby." },
  { id: 1674, category: 'postpartum', keywords: ['support for partners of women with perinatal OCD'], question: "How can partners support someone with perinatal OCD?", response: "Partners can help by learning about OCD, avoiding participating in rituals, encouraging professional treatment, and providing emotional support without judgment. Involvement in therapy sessions can also be very helpful." },
];