// RAG Clinical Entries Part 1 (IDs 1386–2200)
// Covers: Postpartum physiology/care, exercise in pregnancy, bipolar/psychosis/OCD postpartum,
// headaches in pregnancy, chronic hypertension, menstrual cycle physiology, abnormal uterine bleeding,
// menopause clinical (hot flashes, GSM, MHT), contraception deep-dive, menstrual suppression,
// iron deficiency, breast health, cervical/uterine cancer, FSH testing, LEEP, colposcopy,
// perimenopause, sexual dysfunction, insomnia, bone health, sexual health, secondary amenorrhea,
// POI, PMDD diagnosis, menstruation basics, heavy periods, PMS overview

export const ragEntriesClinical1 = [

  // === Postpartum physiology IDs 1386–1430 ===
  { id: 1386, category: 'postpartum', keywords: ['when does milk come in breast milk supply'], question: "When does breast milk usually come in?", response: "Milk typically comes in between 24 and 72 hours after birth, though it can take up to 5–7 days. Your breasts may feel full, firm, and tender. Frequent feeding helps establish supply." },
  { id: 1387, category: 'postpartum', keywords: ['blood pressure changes after birth postpartum'], question: "Can blood pressure go up after giving birth?", response: "Yes. Blood pressure can spike or stay high after delivery and increase the risk of stroke. If your readings are 140/90 or higher, contact your provider immediately." },
  { id: 1388, category: 'postpartum', keywords: ['when does period return after birth postpartum'], question: "When will my period come back after giving birth?", response: "It varies. If you're not breastfeeding, periods often return around 6–12 weeks. If you're exclusively breastfeeding, it can be delayed for many months. Ovulation can return before your first period, so contraception is still needed." },
  { id: 1389, category: 'postpartum', keywords: ['afterpains postpartum cramping'], question: "What are afterpains?", response: "Afterpains are cramps caused by the uterus contracting as it shrinks. They're often stronger while breastfeeding because of oxytocin release. They usually improve within a week. Ibuprofen or acetaminophen help." },
  { id: 1390, category: 'postpartum', keywords: ['pain relief after vaginal birth postpartum'], question: "What's the best pain relief after a vaginal birth?", response: "Most people do well with ibuprofen and acetaminophen. These are preferred over opioids. Cold packs, sitz baths, and good perineal care also help. Opioids are rarely needed after an uncomplicated vaginal birth." },
  { id: 1391, category: 'postpartum', keywords: ['postpartum depression screening EPDS Edinburgh'], question: "Why do they screen for postpartum depression?", response: "Postpartum depression and anxiety are common. Screening helps identify people who need support early. Tools like the Edinburgh Postnatal Depression Scale are used because early treatment makes a big difference." },
  { id: 1392, category: 'postpartum', keywords: ['baby blues vs depression postpartum'], question: "What's the difference between baby blues and postpartum depression?", response: "Baby blues are mild mood swings, tearfulness, and irritability that usually peak around day 3–5 and resolve within two weeks. Postpartum depression is more intense, lasts longer, and interferes with daily life. If symptoms persist or worsen, reach out for help." },
  { id: 1393, category: 'postpartum', keywords: ['postpartum checkup when timing'], question: "When should I have my postpartum checkup?", response: "ACOG recommends contact with your provider within the first 3 weeks, with a full comprehensive visit by 12 weeks. Many people also benefit from an early visit at 1–2 weeks, especially after a cesarean or if they have high blood pressure or mood concerns." },
  { id: 1394, category: 'postpartum', keywords: ['6 week postpartum checkup what happens'], question: "What happens at the 6-week postpartum visit?", response: "Your provider will check your healing, blood pressure, mood, bleeding, and discuss contraception, breastfeeding, and how you're adjusting. It's a good time to ask any questions about your recovery or future pregnancies." },
  { id: 1395, category: 'postpartum', keywords: ['when can I have sex after birth postpartum'], question: "When is it safe to have sex after giving birth?", response: "Most providers recommend waiting until bleeding stops and any tears or incisions have healed — usually around 4–6 weeks. Go at your own pace. Use plenty of lubricant if you're breastfeeding, as dryness is common." },
  { id: 1396, category: 'postpartum', keywords: ['birth control after having a baby postpartum contraception'], question: "When should I start birth control after giving birth?", response: "You can start many methods immediately, even while breastfeeding. Progestin-only options (mini-pill, implant, IUD, shot) are safe right away. Discuss your options with your provider before leaving the hospital." },

  // === Postpartum bipolar IDs 1457–1490 ===
  { id: 1457, category: 'postpartum', keywords: ['postpartum bipolar disorder'], question: "What is postpartum bipolar disorder?", response: "Postpartum bipolar disorder refers to mood episodes (depression, mania, or hypomania) that occur in people with bipolar disorder during or shortly after pregnancy. The risk of relapse is significantly higher in the weeks and months after giving birth compared to other times." },
  { id: 1458, category: 'postpartum', keywords: ['risk of bipolar relapse after birth postpartum'], question: "How common is it for bipolar disorder to relapse after giving birth?", response: "Studies show that about 37–39% of people with bipolar disorder experience a mood episode after delivery. The risk is much higher in the first few weeks postpartum, especially without consistent medication." },
  { id: 1459, category: 'postpartum', keywords: ['postpartum mania or hypomania elevated mood'], question: "Can mania or hypomania happen after giving birth?", response: "Yes. Some people experience elevated or irritable mood, decreased need for sleep, racing thoughts, increased energy, impulsivity, or risky behavior. These episodes can come on quickly and may include psychotic symptoms." },
  { id: 1460, category: 'postpartum', keywords: ['postpartum psychosis bipolar emergency'], question: "When is postpartum psychosis an emergency?", response: "If you or someone you know is experiencing delusions, hallucinations, confusion, severe agitation, or thoughts of harm to self or baby, seek emergency help right away. Early treatment is critical for safety and recovery." },
  { id: 1461, category: 'postpartum', keywords: ['treatment for postpartum bipolar disorder'], question: "How is postpartum bipolar disorder treated?", response: "Treatment often includes mood stabilizers, antipsychotics, and sometimes antidepressants, along with therapy. Medication decisions are especially important during pregnancy and breastfeeding. Work closely with a psychiatrist experienced in perinatal mental health." },

  // === Postpartum depression deep dive IDs 1472–1506 ===
  { id: 1472, category: 'postpartum', keywords: ['what is postpartum depression unipolar'], question: "What is postpartum depression?", response: "Postpartum depression is a type of major depression that occurs after giving birth. It involves persistent sadness, loss of interest, and other symptoms that interfere with daily life and caring for yourself or your baby. It is common, treatable, and not a sign of weakness." },
  { id: 1473, category: 'postpartum', keywords: ['how common is postpartum depression prevalence'], question: "How common is postpartum depression?", response: "It affects about 10 to 15 percent of women after giving birth. Rates may be higher in certain populations. Many people experience it, and effective help is available." },
  { id: 1474, category: 'postpartum', keywords: ['when does postpartum depression start onset'], question: "When does postpartum depression usually begin?", response: "It can start during pregnancy or after delivery. When it begins after birth, it most often appears in the first few months, with the highest risk in the first several weeks." },
  { id: 1475, category: 'postpartum', keywords: ['risk factors for postpartum depression'], question: "What increases the risk of postpartum depression?", response: "The strongest risk factors are having depression during pregnancy or a history of depression (before or during pregnancy). Other factors include high stress, lack of support, relationship difficulties, financial stress, young age, and a history of abuse or trauma." },
  { id: 1476, category: 'postpartum', keywords: ['symptoms of postpartum depression'], question: "What are the symptoms of postpartum depression?", response: "Common symptoms include persistent sadness or emptiness, loss of interest in things you used to enjoy, feeling worthless or guilty, trouble concentrating, changes in sleep or appetite, fatigue, and difficulty bonding with your baby. These symptoms last longer than two weeks and affect daily functioning." },
  { id: 1477, category: 'postpartum', keywords: ['postpartum depression vs baby blues'], question: "How is postpartum depression different from the baby blues?", response: "Baby blues are mild mood swings, tearfulness, and irritability that usually start a few days after birth and go away within two weeks. Postpartum depression is more intense, lasts longer than two weeks, and makes it hard to function or care for yourself and your baby." },
  { id: 1478, category: 'postpartum', keywords: ['Edinburgh Postnatal Depression Scale EPDS'], question: "What is the Edinburgh Postnatal Depression Scale?", response: "It is a widely used 10-question screening tool that helps identify possible postpartum depression. A higher score suggests you may benefit from further evaluation. It is quick to complete and helps start important conversations with your provider." },
  { id: 1479, category: 'postpartum', keywords: ['postpartum depression treatment overview'], question: "How is postpartum depression treated?", response: "Treatment often includes therapy (such as cognitive behavioral therapy), antidepressant medication when appropriate, and strong social support. Many people improve significantly with the right help. Your provider will work with you to find the best plan, including considerations for breastfeeding." },
  { id: 1480, category: 'postpartum', keywords: ['getting help for postpartum depression what to do'], question: "What should I do if I think I have postpartum depression?", response: "Reach out to your OB, midwife, or primary care provider. Screening and talking openly are the first steps. Treatment (therapy, medication, or both) is effective for most people. You deserve support." },

  // === Postpartum psychosis IDs 1506–1519 ===
  { id: 1506, category: 'postpartum', keywords: ['what is postpartum psychosis definition'], question: "What is postpartum psychosis?", response: "Postpartum psychosis is a rare but serious mental health emergency that can occur after giving birth. It involves sudden changes in thinking, mood, and behavior, including hallucinations, delusions, confusion, and disorganization. It usually starts within the first two weeks after delivery and requires immediate medical attention." },
  { id: 1507, category: 'postpartum', keywords: ['who is at highest risk for postpartum psychosis bipolar'], question: "Who is at highest risk for postpartum psychosis?", response: "The highest risk is in people with a history of bipolar disorder, previous postpartum psychosis, or a family history of postpartum psychosis or bipolar disorder. It can also occur in people with schizophrenia or no prior history." },
  { id: 1508, category: 'postpartum', keywords: ['early signs of postpartum psychosis warning'], question: "What are early signs of postpartum psychosis?", response: "One of the earliest and most important signs is severe insomnia that is not explained by caring for the baby. Other early signs can include rapid mood changes, irritability, anxiety, and feeling confused or 'off.'" },
  { id: 1509, category: 'postpartum', keywords: ['symptoms of postpartum psychosis hallucinations delusions'], question: "What are the main symptoms of postpartum psychosis?", response: "Symptoms often include hallucinations (seeing or hearing things that aren't there), delusions (strongly held false beliefs), disorganized thinking or speech, confusion, agitation, and mood swings. Symptoms can appear and change quickly." },
  { id: 1510, category: 'postpartum', keywords: ['postpartum psychosis treatment lithium antipsychotic'], question: "What is the usual medication treatment for postpartum psychosis?", response: "The preferred initial treatment is usually a combination of lithium and a second-generation antipsychotic. This approach is used because many people with postpartum psychosis later receive a diagnosis of bipolar disorder." },
  { id: 1511, category: 'postpartum', keywords: ['ECT for postpartum psychosis electroconvulsive'], question: "Is ECT used for postpartum psychosis?", response: "Yes. Electroconvulsive therapy is a safe and rapidly effective treatment for severe postpartum psychosis, particularly when medication response is inadequate." },
  { id: 1512, category: 'postpartum', keywords: ['support after postpartum psychosis recovery'], question: "What kind of support is needed after postpartum psychosis?", response: "Recovery often requires medication, close monitoring, therapy, and strong support from family. Planning for future pregnancies with a perinatal mental health specialist is very important to reduce risk in subsequent pregnancies." },

  // === Treatment of postpartum psychosis IDs 1611–1628 ===
  { id: 1611, category: 'postpartum', keywords: ['postpartum psychosis hospitalization mother baby'], question: "Do I need to go to the hospital if I have postpartum psychosis?", response: "In most cases, yes. Hospitalization is usually recommended so the mother can be kept safe and treated quickly. The baby should not be left alone with someone experiencing postpartum psychosis until symptoms are under control." },
  { id: 1612, category: 'postpartum', keywords: ['breastfeeding with postpartum psychosis medication'], question: "Can I breastfeed if I have postpartum psychosis?", response: "It depends on safety and stability. Many women can breastfeed while taking antipsychotics or lithium, but some with more severe symptoms may need to pause until they are more stable. The decision should be made with the care team, weighing risks and benefits." },
  { id: 1613, category: 'postpartum', keywords: ['planning future pregnancies after postpartum psychosis'], question: "What if I want another baby after having postpartum psychosis?", response: "This requires careful planning with a perinatal psychiatrist. Many women stay on mood stabilizers (especially lithium) during and after pregnancy to prevent recurrence. Early and proactive care greatly improves outcomes." },

  // === Headache in pregnancy/postpartum IDs 1646–1660 ===
  { id: 1646, category: 'pregnancy', keywords: ['headache in pregnancy preeclampsia when to worry'], question: "When should I worry about a headache during pregnancy?", response: "Any new or severe headache after 20 weeks needs prompt evaluation to rule out preeclampsia. Also seek care for sudden severe headache, vision changes, confusion, neck stiffness, seizures, or headache with high blood pressure. These can signal serious problems." },
  { id: 1647, category: 'pregnancy', keywords: ['migraine during pregnancy safe treatment'], question: "What can I safely take for migraine while pregnant?", response: "Acetaminophen is the safest first choice. If it's not enough, your provider may add metoclopramide or consider a short course of certain other medications depending on how far along you are. Triptans can be used in some cases when benefits outweigh risks. Always check with your provider before taking anything." },
  { id: 1648, category: 'pregnancy', keywords: ['preventive migraine treatment pregnancy propranolol'], question: "What can I take daily to prevent migraines while pregnant?", response: "Beta blockers (like propranolol) and some calcium channel blockers are commonly used. Certain antidepressants or nutraceuticals (magnesium, riboflavin) may also be options. Preventive treatment is usually reserved for frequent or disabling migraines." },
  { id: 1649, category: 'postpartum', keywords: ['post dural puncture headache epidural treatment'], question: "What is a post-dural puncture headache and how is it treated?", response: "It's a headache that worsens when sitting or standing and improves when lying flat. It can occur after an epidural or spinal. Treatment often includes hydration, caffeine, and sometimes a blood patch. It's very treatable and breastfeeding is not a contraindication." },
  { id: 1650, category: 'postpartum', keywords: ['headache while breastfeeding safe medication'], question: "What headache medications are safe while breastfeeding?", response: "Acetaminophen and ibuprofen are generally safe. Some triptans are acceptable with timing adjustments. Avoid ergotamine and limit opioids. Always check with your provider or a lactation consultant before taking medication." },

  // === Perinatal OCD IDs 1661–1674 ===
  { id: 1661, category: 'postpartum', keywords: ['intrusive thoughts about harming baby OCD normal'], question: "Is it normal to have scary thoughts about harming my baby?", response: "Yes — fleeting, unwanted thoughts of accidental harm to the baby are extremely common in new mothers. These thoughts do not mean you will act on them. However, if the thoughts are frequent, very distressing, and lead to compulsive behaviors, it may be perinatal OCD." },
  { id: 1662, category: 'postpartum', keywords: ['postpartum OCD vs normal intrusive thoughts harm'], question: "How is postpartum OCD different from normal scary thoughts about the baby?", response: "In normal intrusive thoughts, the ideas are occasional and quickly dismissed. In perinatal OCD, the thoughts are frequent, cause intense anxiety or guilt, and lead to repetitive behaviors (like excessive checking, avoiding the baby) that interfere with daily life and bonding." },
  { id: 1663, category: 'postpartum', keywords: ['treatment of perinatal OCD CBT ERP SSRI'], question: "How is OCD treated during pregnancy and after birth?", response: "Cognitive Behavioral Therapy with Exposure and Response Prevention (ERP) is the first-line treatment. When symptoms are severe, comorbid depression is present, or therapy access is limited, SSRIs are added. Sertraline is often preferred during breastfeeding." },

  // === Chronic hypertension in pregnancy IDs 1696–1710 ===
  { id: 1696, category: 'pregnancy', keywords: ['what is chronic hypertension in pregnancy'], question: "What is chronic hypertension in pregnancy?", response: "Chronic hypertension means you had high blood pressure before pregnancy or it was first found before 20 weeks. It is different from gestational hypertension or preeclampsia, which start later in pregnancy." },
  { id: 1697, category: 'pregnancy', keywords: ['safe blood pressure medications in pregnancy labetalol nifedipine'], question: "Which blood pressure medications are safe in pregnancy?", response: "Labetalol and extended-release nifedipine are commonly used and generally considered safe. Methyldopa is an older option. ACE inhibitors, ARBs, and some other drugs are not safe and should be stopped before or early in pregnancy." },
  { id: 1698, category: 'pregnancy', keywords: ['low dose aspirin chronic hypertension pregnancy preeclampsia'], question: "Should I take low-dose aspirin if I have chronic hypertension?", response: "Yes. Low-dose aspirin (usually 81 mg daily) is recommended starting after 12 weeks to help reduce the risk of preeclampsia in people with chronic hypertension." },
  { id: 1699, category: 'pregnancy', keywords: ['when to deliver with chronic hypertension pregnancy'], question: "When is delivery recommended if I have chronic hypertension?", response: "For well-controlled hypertension without complications, delivery is often planned between 37 and 39+6 weeks. Earlier delivery may be needed if preeclampsia develops or there are concerns about the baby's growth or your health." },

  // === Normal menstrual cycle IDs 1766–1779 ===
  { id: 1766, category: 'menstrual', keywords: ['what is a normal menstrual cycle length'], question: "What is considered a normal menstrual cycle?", response: "A normal cycle usually occurs every 24 to 38 days, lasts up to 8 days of bleeding, and has fairly consistent timing from month to month. The amount of bleeding should not significantly interfere with your daily life. There is natural variation, especially in teens and people approaching menopause." },
  { id: 1767, category: 'menstrual', keywords: ['follicular phase menstrual cycle hormones FSH'], question: "What happens during the follicular phase?", response: "This phase starts on day 1 of your period and ends at ovulation. FSH stimulates several follicles to grow in the ovary. One becomes dominant and produces rising levels of estrogen, which thickens the uterine lining in preparation for a possible pregnancy." },
  { id: 1768, category: 'menstrual', keywords: ['when does ovulation happen LH surge'], question: "When does ovulation usually occur?", response: "Ovulation typically happens around day 14 in a 28-day cycle, but it can vary. It is triggered by a surge in LH (luteinizing hormone). The mature egg is released from the ovary and can be fertilized for about 12–24 hours." },
  { id: 1769, category: 'menstrual', keywords: ['luteal phase progesterone corpus luteum'], question: "What happens during the luteal phase?", response: "After ovulation, the empty follicle becomes the corpus luteum and produces progesterone. This hormone prepares the uterine lining for possible implantation. If pregnancy doesn't occur, progesterone and estrogen levels drop, triggering your period about 14 days later." },
  { id: 1770, category: 'menstrual', keywords: ['why cycles vary in length stress illness'], question: "Why does my cycle length change from month to month?", response: "Cycle length can vary due to stress, illness, weight changes, sleep, or hormonal fluctuations. Variation of up to 7–9 days is usually normal, especially in younger people or those nearing perimenopause. Very irregular cycles may need evaluation." },
  { id: 1771, category: 'menstrual', keywords: ['when is menstrual bleeding abnormal when to see doctor'], question: "When should I be concerned about my menstrual bleeding?", response: "See a provider if your periods are very irregular, extremely heavy, last longer than 8 days, occur more often than every 24 days or less often than every 38 days, or if you have severe pain, bleeding between periods, or bleeding after sex. These can signal an underlying issue." },

  // === Abnormal uterine bleeding in teens IDs 1780–1791 ===
  { id: 1780, category: 'menstrual', keywords: ['normal period length teens cycle irregular menarche'], question: "What is a normal menstrual cycle for a teenager?", response: "In the first few years after starting periods, cycles are often longer and more irregular than in adults. Most teens have cycles every 21 to 45 days with bleeding lasting 2 to 7 days. It can take 1–4 years for cycles to become more regular and predictable." },
  { id: 1781, category: 'menstrual', keywords: ['abnormal uterine bleeding teens heavy irregular'], question: "What counts as abnormal uterine bleeding in adolescents?", response: "Abnormal bleeding includes periods that are too frequent (less than every 21 days), too infrequent (more than every 45 days), very heavy, last longer than 7–8 days, or occur at unpredictable times. It also includes bleeding between periods or missing periods for long stretches after they've started." },
  { id: 1782, category: 'menstrual', keywords: ['heavy periods bleeding disorders teens von Willebrand'], question: "When should heavy periods make me think of a bleeding disorder?", response: "Consider a bleeding disorder (like von Willebrand disease) if heavy bleeding started with your very first period, you've needed a blood transfusion, you have anemia that doesn't improve, or you also have easy bruising, frequent nosebleeds, or bleeding gums. Tell your provider — specific blood tests can check for this." },
  { id: 1783, category: 'menstrual', keywords: ['PCOS irregular periods teens check hormones'], question: "When should irregular periods be checked for PCOS?", response: "If you have irregular periods plus signs like excess hair growth, severe acne, or weight gain, your provider may check hormone levels (testosterone, 17-hydroxyprogesterone) and possibly do an ultrasound. PCOS is a common cause of irregular bleeding in teens." },

  // === Ovulation detection IDs 1792–1804 ===
  { id: 1792, category: 'menstrual', keywords: ['how to tell if I ovulated basal body temperature LH'], question: "How can I tell if I'm ovulating?", response: "You can track ovulation with several methods: charting your cycle length, checking basal body temperature daily, using ovulation predictor kits that detect the LH surge, or having a blood test for progesterone about a week before your period. Ultrasound is the most accurate but usually done in a clinic." },
  { id: 1793, category: 'menstrual', keywords: ['basal body temperature ovulation BBT tracking'], question: "How does basal body temperature show ovulation?", response: "After ovulation, progesterone causes a small but noticeable rise in your resting body temperature (about 0.5°F). Tracking your temperature every morning before getting out of bed can confirm that ovulation has occurred, though it won't predict it in advance." },
  { id: 1794, category: 'menstrual', keywords: ['ovulation predictor kits LH surge how they work'], question: "How do ovulation predictor kits work?", response: "These urine tests detect the luteinizing hormone (LH) surge that happens about 24–36 hours before ovulation. Start testing a few days before you expect ovulation. A positive result means you're likely to ovulate soon — this is one of the best ways to time intercourse if you're trying to conceive." },
  { id: 1795, category: 'menstrual', keywords: ['when is the fertile window conception timing'], question: "When is the fertile window in my cycle?", response: "The fertile window is roughly the 5–6 days leading up to and including ovulation. The highest chance of conception is usually 1–2 days before ovulation. Tracking ovulation helps you identify this window more accurately than calendar methods alone." },
  { id: 1796, category: 'menstrual', keywords: ['ovarian reserve testing AMH FSH antral follicle'], question: "What is ovarian reserve testing?", response: "Ovarian reserve testing estimates how many eggs you have left. Common tests include early-cycle FSH + estradiol, anti-Müllerian hormone (AMH), and antral follicle count on ultrasound. These are especially useful if you're over 35 or having trouble conceiving." },
  { id: 1797, category: 'menstrual', keywords: ['does stress affect ovulation cycle delay'], question: "Can stress stop me from ovulating?", response: "Yes. Significant physical or emotional stress, large weight changes, intense exercise, or illness can disrupt the hormonal signals needed for ovulation, leading to delayed or missed periods. Tracking can help you see these patterns." },

  // === Abnormal uterine bleeding evaluation IDs 1811–1825 ===
  { id: 1811, category: 'menstrual', keywords: ['what is abnormal uterine bleeding definition patterns'], question: "What is considered abnormal uterine bleeding?", response: "Abnormal uterine bleeding includes periods that are too frequent (less than every 24 days), too infrequent (more than every 38 days), irregular in timing, last longer than 8 days, or are heavier than what interferes with your daily life. Bleeding between periods or very light periods can also be abnormal." },
  { id: 1812, category: 'menstrual', keywords: ['heavy menstrual bleeding definition soaking pad'], question: "What counts as heavy menstrual bleeding?", response: "Heavy menstrual bleeding is when the amount of bleeding interferes with your physical, emotional, social, or material quality of life. Passing large clots, soaking through protection hourly, or bleeding that lasts more than 8 days are common signs." },
  { id: 1813, category: 'menstrual', keywords: ['intermenstrual bleeding spotting between periods causes'], question: "What is intermenstrual bleeding?", response: "Intermenstrual bleeding is bleeding or spotting that occurs between regular menstrual periods. Common causes include polyps, hormonal contraception, infection, or (less commonly) more serious conditions." },
  { id: 1814, category: 'menstrual', keywords: ['first steps evaluation abnormal bleeding workup'], question: "What are the first steps when I have abnormal bleeding?", response: "Your provider will ask about your bleeding pattern, medical history, medications, and sexual history. They will do a pregnancy test, physical exam, and often blood work. A pelvic ultrasound is frequently needed to look for structural causes like fibroids or polyps." },
  { id: 1815, category: 'menstrual', keywords: ['endometrial biopsy when needed abnormal bleeding'], question: "When is an endometrial biopsy needed for abnormal bleeding?", response: "Endometrial sampling is recommended for women 45 and older with abnormal bleeding, or younger people with risk factors like obesity, chronic irregular cycles, or specific genetic conditions. It helps rule out endometrial hyperplasia or cancer." },
  { id: 1816, category: 'menstrual', keywords: ['ultrasound for abnormal bleeding hysteroscopy SIS'], question: "Why is ultrasound used for abnormal bleeding?", response: "Pelvic ultrasound is the first-line imaging test. It can detect fibroids, adenomyosis, polyps, ovarian issues, and other structural causes. Saline infusion sonography or hysteroscopy may be added if intracavitary lesions are suspected." },
  { id: 1817, category: 'menstrual', keywords: ['when to see doctor for abnormal bleeding'], question: "When should I see a doctor for abnormal bleeding?", response: "See a provider for bleeding that is very heavy, lasts longer than 8 days, occurs between periods, is irregular, or is new for you — especially if you're over 45, have risk factors for endometrial issues, feel dizzy/weak, or have severe pain. Early evaluation helps identify treatable causes." },

  // === Menstrual suppression IDs 1826–1837 ===
  { id: 1826, category: 'menstrual', keywords: ['is it safe to stop periods birth control'], question: "Is it safe to use birth control to stop or reduce periods?", response: "Yes. Monthly bleeding is not medically necessary. Using hormonal contraception to reduce or eliminate periods is safe for most people and has the same risks as regular cyclic use. Many people prefer fewer or no periods for medical or lifestyle reasons." },
  { id: 1827, category: 'menstrual', keywords: ['who benefits from menstrual suppression endometriosis PMDD'], question: "Who might benefit from stopping or reducing periods?", response: "People with heavy or painful periods, endometriosis, adenomyosis, fibroids, bleeding disorders, severe anemia, menstrual migraines, PMDD, or those who find periods inconvenient. It can also help with hygiene challenges or medical treatments." },
  { id: 1828, category: 'menstrual', keywords: ['best methods stopping periods LNG IUD DMPA continuous pill'], question: "Which birth control methods are best for stopping periods completely?", response: "The most effective options for achieving amenorrhea include the levonorgestrel 52 mg IUD, depot medroxyprogesterone acetate (DMPA) shots, and continuous or extended-use combined estrogen-progestin pills or rings. The LNG 52 mg IUD and DMPA often lead to no periods over time, though it can take months." },
  { id: 1829, category: 'menstrual', keywords: ['continuous vs extended cycle birth control pills difference'], question: "What is the difference between continuous and extended birth control pill use?", response: "Extended use means taking active pills for 3–6 months or more before taking a short break for a withdrawal bleed. Continuous use means taking active pills every day with no breaks. Both reduce or eliminate scheduled periods; unscheduled spotting is common at first but usually improves." },
  { id: 1830, category: 'menstrual', keywords: ['DMPA depo shot stopping periods effectiveness'], question: "How well does the Depo-Provera shot stop periods?", response: "About 50–75% of people using DMPA for one year develop amenorrhea, and this increases with longer use. It is one of the most effective methods for stopping periods but can cause irregular bleeding at first. It is given as an injection every 3 months." },
  { id: 1831, category: 'menstrual', keywords: ['fertility after stopping period suppression return'], question: "Does using birth control to stop periods affect future fertility?", response: "For most methods (pills, ring, hormonal IUD, implant), fertility returns quickly after stopping — usually within 1–3 months. The Depo shot can sometimes delay return of periods and fertility a bit longer. Menstrual suppression itself does not cause long-term infertility." },

  // === Uterine and cervical cancer IDs 1846–1895 ===
  { id: 1846, category: 'cancer', keywords: ['uterine cancer symptoms postmenopausal bleeding'], question: "What are the symptoms of uterine cancer?", response: "The most common symptom is abnormal vaginal bleeding. This includes bleeding between periods, very heavy periods, or any vaginal bleeding after menopause. Other possible symptoms include pelvic pain or a persistent cough if the cancer has spread. These symptoms can also be caused by non-cancer conditions, so it's important to get checked." },
  { id: 1847, category: 'cancer', keywords: ['how is uterine cancer diagnosed endometrial biopsy'], question: "How is uterine cancer diagnosed?", response: "Diagnosis usually starts with a pelvic ultrasound and an endometrial biopsy (a small sample of the uterine lining is taken and examined under a microscope). Sometimes a hysteroscopy or D&C is needed. Imaging like CT or MRI may be used later to check for spread." },
  { id: 1848, category: 'cancer', keywords: ['uterine cancer treatment hysterectomy surgery'], question: "How is uterine cancer treated?", response: "The main treatment is surgery to remove the uterus, ovaries, and fallopian tubes. Depending on the stage and type, some people also need radiation, chemotherapy, or hormone therapy. Treatment is personalized based on how far the cancer has spread and your overall health." },
  { id: 1849, category: 'cancer', keywords: ['cervical cancer symptoms HPV screening Pap'], question: "What are the symptoms of cervical cancer and how is it screened?", response: "Early cervical cancer often has no symptoms. When symptoms appear, they can include bleeding between periods, bleeding after sex, or vaginal bleeding after menopause. Screening uses a Pap test and/or an HPV test. Screening can find precancerous changes or early cancer when it is highly treatable." },
  { id: 1850, category: 'cancer', keywords: ['HPV vaccine cervical cancer prevention'], question: "Can the HPV vaccine prevent cervical cancer?", response: "Yes. The HPV vaccine prevents infection with the high-risk HPV types that cause most cervical cancers. It works best when given before sexual activity begins, but it can still offer protection even if you've already been exposed to some types." },
  { id: 1851, category: 'cancer', keywords: ['cervical cancer treatment options fertility'], question: "How is cervical cancer treated?", response: "Treatment depends on the stage, your age, overall health, and whether you want to preserve fertility. Options include surgery, radiation therapy, and chemotherapy. Some early cases may be treated with surgery that preserves the uterus." },
  { id: 1852, category: 'cancer', keywords: ['precancerous cervical cells colposcopy LEEP'], question: "What if I have precancerous cells on my cervix?", response: "Precancerous changes (also called cervical dysplasia or CIN) are not cancer but can progress if untreated. Your doctor may recommend monitoring, removing the abnormal cells (via procedures like LEEP or cone biopsy), or other management based on the severity and your situation." },

  // === FSH test IDs 1861–1870 ===
  { id: 1861, category: 'testing', keywords: ['what is an FSH test follicle stimulating hormone'], question: "What is an FSH test?", response: "An FSH test measures the level of follicle-stimulating hormone in your blood. FSH is made by the pituitary gland and plays a key role in puberty, the menstrual cycle, and fertility. In females, it helps stimulate follicle (egg) development in the ovaries." },
  { id: 1862, category: 'testing', keywords: ['why get an FSH blood test ovarian reserve'], question: "Why would I need an FSH blood test?", response: "Doctors order an FSH test to investigate irregular or missed periods, early or delayed puberty, infertility, or to prepare for IVF. It can also help evaluate other hormone-related symptoms." },
  { id: 1863, category: 'testing', keywords: ['high FSH levels meaning ovarian reserve menopause'], question: "What does a high FSH level mean?", response: "High FSH can suggest that the ovaries are not responding well to signals from the brain (diminished ovarian reserve). In younger people it may indicate primary ovarian insufficiency. Your doctor will interpret the result in the context of your age, symptoms, and other tests." },
  { id: 1864, category: 'testing', keywords: ['low FSH levels hypothalamic amenorrhea pituitary'], question: "What does a low FSH level mean?", response: "Low FSH may indicate a problem with the pituitary gland or hypothalamus, or it can occur in conditions like hypothalamic amenorrhea (often related to stress, weight loss, or over-exercise). Further testing is usually needed." },
  { id: 1865, category: 'testing', keywords: ['FSH test timing cycle IVF fertility'], question: "When should an FSH test be done during my cycle?", response: "If you still have periods, the test is usually done early in your cycle (typically day 2–4). If you're not having periods, it can be done on any day. Your doctor will tell you the best timing for your situation." },

  // === LEEP and colposcopy IDs 1927–1950 ===
  { id: 1927, category: 'procedure', keywords: ['what is a LEEP procedure loop electrosurgical'], question: "What is a LEEP procedure?", response: "LEEP stands for Loop Electrosurgical Excision Procedure. It is a quick outpatient surgery that uses a thin wire loop with an electrical current to remove abnormal or precancerous cells from the cervix. It is also sometimes called LLETZ (large loop excision of the transformation zone)." },
  { id: 1928, category: 'procedure', keywords: ['why is LEEP done abnormal Pap HPV'], question: "Why would I need a LEEP?", response: "Your doctor may recommend a LEEP if a Pap test, HPV test, or cervical biopsy showed abnormal or precancerous cells. Removing these cells helps prevent them from progressing to cervical cancer and allows the tissue to be examined more thoroughly in the lab." },
  { id: 1929, category: 'procedure', keywords: ['LEEP risks future pregnancy preterm birth'], question: "Does LEEP affect future pregnancies?", response: "Yes, it can. Removing part of the cervix can increase the risk of preterm birth, second-trimester miscarriage, or cervical insufficiency in future pregnancies. The risk is generally higher if a larger area of tissue is removed. Discuss this with your doctor if you plan to have children." },
  { id: 1930, category: 'procedure', keywords: ['recovery after LEEP aftercare instructions'], question: "What is recovery like after a LEEP?", response: "Most people go home the same day. You may have cramping, light bleeding, or dark discharge for several days to a couple of weeks. You will be given instructions about activity restrictions, avoiding tampons and sex for a period of time, and when to call your doctor." },
  { id: 1931, category: 'procedure', keywords: ['what is a colposcopy procedure cervix'], question: "What is a colposcopy?", response: "A colposcopy is a procedure that allows your doctor to closely examine your cervix, vagina, or vulva using a special magnifying instrument called a colposcope. It is often done after an abnormal Pap test or HPV test to get a better look at any concerning areas." },
  { id: 1932, category: 'procedure', keywords: ['what happens during colposcopy biopsy'], question: "What happens during a colposcopy?", response: "You will lie on an exam table with your feet in stirrups. The doctor inserts a speculum and uses a colposcope (which doesn't touch you) to magnify the cervix. They apply a vinegar-like solution (acetic acid) to highlight abnormal areas. If abnormal areas are found, small tissue samples (biopsies) may be taken." },
  { id: 1933, category: 'procedure', keywords: ['recovery after colposcopy bleeding discharge'], question: "What is recovery like after a colposcopy?", response: "You can usually return to normal activities right away. If you had a biopsy, you may have light bleeding or dark discharge for a few days. Avoid sex, tampons, and douching for at least 48 hours (or as instructed) to allow healing." },

  // === Perimenopause IDs 1901–1910 ===
  { id: 1901, category: 'perimenopause', keywords: ['what is perimenopause transition irregular periods'], question: "What is perimenopause?", response: "Perimenopause is the transition time leading up to menopause, when periods eventually stop. It usually starts about 4 years before your last period (average age around 47). During this time, hormone levels — especially estrogen — fluctuate significantly, causing irregular periods and other symptoms." },
  { id: 1902, category: 'perimenopause', keywords: ['perimenopause symptoms hot flashes night sweats mood'], question: "What are common symptoms of perimenopause?", response: "The main symptoms include changes in menstrual cycle length and flow (periods may come closer together, farther apart, or be heavier/lighter). Other common symptoms are hot flashes, night sweats, mood changes (including depression or anxiety), and sleep difficulties. Vaginal dryness often appears later." },
  { id: 1903, category: 'perimenopause', keywords: ['hot flashes perimenopause common how long last'], question: "Are hot flashes common in perimenopause?", response: "Yes. Hot flashes and night sweats are very common during perimenopause due to estrogen fluctuations. They can feel like a sudden wave of heat, often starting in the chest and face. Night sweats can disrupt sleep. Hormone therapy is the most effective treatment for these symptoms." },
  { id: 1904, category: 'perimenopause', keywords: ['irregular periods perimenopause why'], question: "Why do periods become irregular in perimenopause?", response: "As you approach menopause, ovulation becomes less predictable and estrogen levels swing up and down. This causes periods to come at irregular intervals, vary in length, or change in heaviness. This is a normal part of the transition." },
  { id: 1905, category: 'perimenopause', keywords: ['hormone therapy for perimenopause symptoms MHT'], question: "Can hormone therapy help with perimenopause symptoms?", response: "Yes. Estrogen (usually combined with progesterone if you still have a uterus) is the most effective treatment for hot flashes and night sweats. It can also help with sleep and mood in many people. It is generally considered safe for most healthy people under 60 who are within 10 years of menopause onset." },
  { id: 1906, category: 'perimenopause', keywords: ['when to see doctor about perimenopause symptoms'], question: "When should I see a doctor about perimenopause symptoms?", response: "See your doctor if your periods become very heavy, last a long time, or if you have bleeding between periods or after sex. Also seek care for bothersome hot flashes, mood changes, sleep problems, or if you're under 45 and having symptoms. Good treatment options are available." },

  // === Breast pain IDs 1956–1965 ===
  { id: 1956, category: 'breast', keywords: ['types of breast pain cyclical noncyclical'], question: "What are the different types of breast pain?", response: "There are three main types: Cyclical breast pain is related to your menstrual cycle and hormone changes. Noncyclical breast pain is not tied to your cycle and can have many causes. Extramammary pain feels like it's in the breast but actually comes from nearby structures like chest muscles or ribs." },
  { id: 1957, category: 'breast', keywords: ['cyclical breast pain causes hormones luteal'], question: "What causes cyclical breast pain?", response: "Cyclical breast pain is very common and is caused by normal hormone fluctuations during the menstrual cycle. Breasts often feel sore or tender in the week or two before your period. It usually improves after your period starts." },
  { id: 1958, category: 'breast', keywords: ['is breast pain a sign of cancer'], question: "Is breast pain usually a sign of breast cancer?", response: "No. Breast pain is very common and is rarely a sign of breast cancer, especially when it's cyclical. However, any new, persistent, or changing breast pain should be evaluated by a doctor to rule out other causes." },
  { id: 1959, category: 'breast', keywords: ['treatment for breast pain supportive bra ibuprofen'], question: "How is breast pain treated?", response: "Most breast pain improves with simple measures. Helpful options include wearing a well-fitted, supportive bra (including at night if needed), taking over-the-counter pain relievers like ibuprofen or acetaminophen, using warm or cool compresses, and gentle massage." },
  { id: 1960, category: 'breast', keywords: ['when to see doctor about breast pain'], question: "When should I see a doctor about breast pain?", response: "See your doctor if breast pain is new or worsening, lasts more than a few weeks, is one-sided and persistent, or is accompanied by a lump, nipple discharge, skin changes, or signs of infection (fever, redness, warmth). Any breast symptom that concerns you deserves evaluation." },

  // === Iron deficiency IDs 1971–1981 ===
  { id: 1971, category: 'nutrition', keywords: ['what is iron deficiency anemia symptoms'], question: "What are symptoms of iron deficiency?", response: "Common symptoms include fatigue, weakness (especially with activity), irritability, headaches, hair loss, and restless legs syndrome. Some people develop unusual cravings (pica), such as wanting to eat ice, clay, or starch. Severe anemia can cause chest pain or shortness of breath." },
  { id: 1972, category: 'nutrition', keywords: ['ferritin test iron deficiency blood test CBC'], question: "What blood test checks for iron deficiency?", response: "The best test is ferritin, which measures your body's iron stores. Doctors also check hemoglobin (as part of a CBC) to see if you have anemia, and sometimes transferrin saturation. A low ferritin level is the earliest and most reliable sign of iron deficiency." },
  { id: 1973, category: 'nutrition', keywords: ['heavy periods iron deficiency cause anemia'], question: "Can heavy periods cause iron deficiency?", response: "Yes. Heavy or prolonged menstrual bleeding is one of the most common causes of iron deficiency in women of reproductive age. If you have heavy periods and symptoms of low iron, it's important to get tested and discuss options to reduce bleeding." },
  { id: 1974, category: 'nutrition', keywords: ['how to take iron supplements absorption tips'], question: "How should I take iron supplements?", response: "Take iron once a day or every other day on an empty stomach for best absorption. Avoid taking it with coffee, tea, dairy, eggs, or whole grains at the same time. Vitamin C (from orange juice or supplements) can help absorption. Don't take more than prescribed — too much iron can be harmful." },
  { id: 1975, category: 'nutrition', keywords: ['side effects of iron pills constipation nausea'], question: "What side effects do iron pills cause?", response: "Common side effects include nausea, constipation, stomach upset, and dark or black stools. These are normal but can be bothersome. Taking iron every other day, with food (if needed), or switching to a different formulation or IV iron can help reduce side effects." },
  { id: 1976, category: 'nutrition', keywords: ['IV iron vs oral pills when is IV iron better'], question: "When is IV iron better than pills?", response: "IV iron is often better if you can't tolerate oral iron, have absorption problems (after weight loss surgery or with inflammatory bowel disease), have very low iron levels, or are in late pregnancy. IV iron delivers a full dose quickly, often in one or two visits." },

  // === Menopause IDs 1986–1996 ===
  { id: 1986, category: 'menopause', keywords: ['what is menopause definition age periods stop'], question: "What is menopause?", response: "Menopause is the point when menstrual periods naturally stop permanently. It is diagnosed after you have gone 12 consecutive months without a period. The ovaries stop releasing eggs and produce much lower levels of estrogen and progesterone. The average age is 51, but it normally occurs between 45 and 55." },
  { id: 1987, category: 'menopause', keywords: ['perimenopause vs menopause difference'], question: "What is the difference between perimenopause and menopause?", response: "Perimenopause is the transition period leading up to menopause, when hormone levels fluctuate and periods become irregular. Menopause is the specific point when you have gone 12 months without a period. Symptoms often start during perimenopause and can continue for years after menopause." },
  { id: 1988, category: 'menopause', keywords: ['common menopause symptoms hot flashes night sweats mood'], question: "What are the most common symptoms of menopause?", response: "Common symptoms include hot flashes, night sweats, sleep disturbances, mood changes (including depression and anxiety), trouble concentrating, vaginal dryness, and joint pain. Hot flashes often begin during perimenopause and can continue for years after periods stop." },
  { id: 1989, category: 'menopause', keywords: ['hormone therapy menopause effective hot flashes'], question: "Is hormone therapy effective for menopause symptoms?", response: "Yes. Estrogen (combined with progesterone if you still have a uterus) is the most effective treatment for hot flashes and night sweats. It can also help with sleep, mood, and vaginal symptoms. It is generally considered safe and effective for most healthy people under age 60 or within 10 years of menopause." },
  { id: 1990, category: 'menopause', keywords: ['who should not take hormone therapy menopause'], question: "Who should not take hormone therapy for menopause?", response: "Hormone therapy is usually not recommended if you have a history of breast cancer, heart attack, stroke, or blood clots. Your doctor will review your personal medical history and risk factors to help decide if it is safe for you." },
  { id: 1991, category: 'menopause', keywords: ['non-hormonal treatments hot flashes menopause SSRIs'], question: "What non-hormonal treatments help with hot flashes?", response: "Options include certain antidepressants (such as paroxetine or venlafaxine), the medication fezolinetant (Veozah), and some anti-seizure medicines. These can be good choices for people who cannot or prefer not to use hormone therapy, including many breast cancer survivors." },
  { id: 1992, category: 'menopause', keywords: ['vaginal estrogen dryness menopause GSM treatment'], question: "How is vaginal dryness treated after menopause?", response: "Low-dose vaginal estrogen (creams, tablets, or a ring) is highly effective for vaginal dryness and painful sex. It has very low absorption into the rest of the body. Non-hormonal vaginal moisturizers used several times a week and lubricants during sex can also help." },
  { id: 1993, category: 'menopause', keywords: ['can I still get pregnant during menopause transition perimenopause'], question: "Can I still get pregnant while going through menopause?", response: "Yes. As long as you are still having periods (even if irregular), pregnancy is possible. You should continue using contraception until you have gone a full 12 months without a period. After that, pregnancy is very unlikely." },
  { id: 1994, category: 'menopause', keywords: ['bone health after menopause calcium vitamin D exercise'], question: "How can I protect my bones after menopause?", response: "Estrogen helps protect bones. After menopause, focus on getting enough calcium and vitamin D, staying physically active (especially weight-bearing and resistance exercise), and asking your doctor about bone density testing. Some people may need prescription medications to prevent bone loss." },

  // === Abnormal uterine bleeding management IDs 2031–2040 ===
  { id: 2031, category: 'bleeding', keywords: ['abnormal uterine bleeding treatment LNG IUD pill options'], question: "What are the main treatments for abnormal uterine bleeding?", response: "Treatment depends on the cause and may include hormonal birth control pills, progestin therapy, a progestin IUD, or procedures such as endometrial ablation, hysteroscopy to remove polyps, or surgery (myomectomy or hysterectomy) for fibroids or persistent bleeding." },
  { id: 2032, category: 'bleeding', keywords: ['progestin IUD LNG heavy bleeding effective'], question: "Can a hormonal IUD help with heavy or irregular bleeding?", response: "Yes. Progestin-releasing IUDs (such as Mirena or Liletta) significantly reduce menstrual bleeding and can make periods much lighter or stop them altogether. They are often a good long-term option for managing abnormal uterine bleeding without surgery." },
  { id: 2033, category: 'bleeding', keywords: ['postmenopausal bleeding causes evaluation'], question: "What causes bleeding after menopause?", response: "Common causes include thinning of the uterine lining (atrophy), polyps, fibroids, infection, or (less commonly) endometrial cancer or precancer. Any bleeding after menopause should be evaluated promptly, usually with an ultrasound and endometrial biopsy." },
  { id: 2034, category: 'bleeding', keywords: ['red flags abnormal uterine bleeding when to get help'], question: "What bleeding symptoms need prompt medical attention?", response: "Seek care for very heavy bleeding, bleeding that soaks through protection hourly, bleeding with dizziness or fainting, bleeding after menopause, or bleeding accompanied by severe pain or fever. These can signal significant blood loss or other serious issues." },

  // === Menopausal transition clinical IDs 2049–2057 ===
  { id: 2049, category: 'menopause', keywords: ['STRAW staging system menopause early late transition'], question: "What is the difference between early and late menopausal transition?", response: "In the early transition, menstrual cycles vary by 7 or more days. In the late transition, cycles become more irregular with skipped periods and longer stretches of amenorrhea. Hot flashes become more common in the late transition. The late stage typically lasts 1–3 years before the final menstrual period." },
  { id: 2050, category: 'menopause', keywords: ['when to measure FSH for menopause perimenopause diagnosis'], question: "Is FSH testing useful for diagnosing menopause or perimenopause?", response: "FSH is often not necessary in women over 45 with typical symptoms and irregular cycles. A single FSH level can be misleading because levels fluctuate widely during the transition. FSH is more useful in women under 45 with irregular cycles or when the diagnosis is unclear." },
  { id: 2051, category: 'menopause', keywords: ['genitourinary syndrome of menopause GSM definition'], question: "What is genitourinary syndrome of menopause (GSM)?", response: "GSM refers to symptoms caused by low estrogen and androgen levels affecting the vulva, vagina, urethra, and bladder. It includes vaginal dryness, burning, painful sex, and urinary symptoms. Symptoms often appear later than hot flashes and respond well to low-dose vaginal estrogen or non-hormonal moisturizers." },
  { id: 2052, category: 'menopause', keywords: ['mood changes perimenopause depression anxiety risk'], question: "Are mood changes common during the menopausal transition?", response: "Yes. There is an increased risk of new or recurrent depression and anxiety during perimenopause, especially in women with a prior history. Symptoms often improve after the final menstrual period. Both hormonal changes and sleep disruption contribute. Effective treatments are available." },
  { id: 2053, category: 'menopause', keywords: ['primary ovarian insufficiency early menopause age 40 diagnosis'], question: "What is the difference between primary ovarian insufficiency and early menopause?", response: "Primary ovarian insufficiency (premature ovarian failure) occurs before age 40. Early menopause occurs between ages 40 and 45. Both are associated with higher risks of cardiovascular disease, bone loss, and cognitive concerns compared with menopause at the average age." },

  // === Menopausal hormone therapy IDs 2066–2090 ===
  { id: 2066, category: 'menopause', keywords: ['what is menopausal hormone therapy MHT estrogen progestin'], question: "What is menopausal hormone therapy?", response: "Menopausal hormone therapy uses estrogen (and progestin if you have a uterus) to relieve bothersome menopause symptoms like hot flashes and vaginal dryness. Estrogen is the hormone that treats the symptoms. Progestin is added to protect the uterine lining from overgrowth when you still have a uterus." },
  { id: 2067, category: 'menopause', keywords: ['transdermal estrogen patch vs oral pill menopause preference'], question: "Is the estrogen patch better than pills for menopause?", response: "Many experts prefer the estradiol patch over pills because it has a lower risk of blood clots. Both are effective for hot flashes and bone health. The patch is changed once or twice a week depending on the brand." },
  { id: 2068, category: 'menopause', keywords: ['why add progestin with estrogen menopause uterus protection'], question: "Why do I need to take progestin if I take estrogen after menopause?", response: "If you still have a uterus, estrogen alone can cause the uterine lining to thicken and increase the risk of uterine cancer or precancer. Taking progestin (or using a levonorgestrel IUD) protects the lining. If you've had a hysterectomy, you can take estrogen alone." },
  { id: 2069, category: 'menopause', keywords: ['is hormone therapy safe menopause benefits risks'], question: "Is menopausal hormone therapy safe?", response: "For most healthy people under age 60 or within 10 years of menopause onset, hormone therapy is considered safe and effective for treating hot flashes and other symptoms. Risks are higher if started many years after menopause or in people with certain medical conditions." },
  { id: 2070, category: 'menopause', keywords: ['how long can I stay on hormone therapy menopause duration'], question: "How long can I stay on menopausal hormone therapy?", response: "This is individualized. Some experts suggest trying to taper after about 5 years, while others support longer use if symptoms persist and benefits outweigh risks. Many women need therapy for 7–10+ years because hot flashes can last a long time. Discuss your personal situation with your clinician." },
  { id: 2071, category: 'menopause', keywords: ['vaginal estrogen low dose for GSM menopause dryness'], question: "What is low-dose vaginal estrogen used for?", response: "Low-dose vaginal estrogen (cream, tablet, or ring) treats genitourinary syndrome of menopause — vaginal dryness, burning, painful sex, and some urinary symptoms. It has very low absorption into the bloodstream and does not usually require progestin. It does not treat hot flashes." },
  { id: 2072, category: 'menopause', keywords: ['compounded bioidentical hormones not recommended menopause'], question: "Are compounded bioidentical hormones recommended?", response: "No. Expert groups do not recommend compounded bioidentical hormone products. They are not FDA-regulated like standard hormone therapy, and there is no good evidence they are safer or more effective. Approved estradiol and micronized progesterone are already bioidentical." },
  { id: 2073, category: 'menopause', keywords: ['micronized progesterone vs MPA progestogen preference'], question: "Why is micronized progesterone preferred over medroxyprogesterone acetate?", response: "Micronized progesterone (bioidentical) is metabolically neutral, has a good safety profile for the breast and cardiovascular system, and is effective for endometrial protection. It is usually given as 200 mg for 12 days per month (cyclic) or 100 mg daily (continuous)." },

  // === Hot flashes IDs 2113–2122 ===
  { id: 2113, category: 'hot flashes', keywords: ['how common are hot flashes menopause prevalence'], question: "How common are hot flashes during menopause?", response: "Hot flashes occur in up to 80% of women during the menopausal transition. They are most frequent in the late transition and early postmenopause. Only about 20–30% of women seek medical treatment for them." },
  { id: 2114, category: 'hot flashes', keywords: ['how long do hot flashes last menopause duration'], question: "How long do hot flashes typically last?", response: "Hot flashes often persist for many years. The median total duration is about 7.4 years, with symptoms continuing for a median of 4.5 years after the final menstrual period. Some women experience them for 10–20 years or longer." },
  { id: 2115, category: 'hot flashes', keywords: ['pathophysiology hot flashes causes estrogen hypothalamus'], question: "What causes hot flashes?", response: "Hot flashes result from thermoregulatory dysfunction in the hypothalamus triggered by estrogen withdrawal. KNDy neurons in the hypothalamus play a central role in mediating both the hormonal pulses and the temperature changes." },
  { id: 2116, category: 'hot flashes', keywords: ['hormone therapy hot flashes most effective treatment'], question: "How effective is hormone therapy for hot flashes?", response: "Menopausal hormone therapy (estrogen ± progestin) is the most effective treatment for hot flashes. It typically reduces frequency and severity by 75% or more. It is the preferred option for most healthy women with moderate to severe symptoms who have no contraindications." },
  { id: 2117, category: 'hot flashes', keywords: ['nonhormonal treatments hot flashes SSRIs fezolinetant gabapentin'], question: "What nonhormonal treatments work for hot flashes?", response: "Effective nonhormonal options include certain SSRIs/SNRIs (e.g., escitalopram, venlafaxine, desvenlafaxine), gabapentin, and neurokinin 3 receptor antagonists (fezolinetant and elinzanetant). These are good choices for women who cannot or prefer not to use hormone therapy." },
  { id: 2118, category: 'hot flashes', keywords: ['fezolinetant NK3 receptor antagonist hot flashes'], question: "How effective is fezolinetant for hot flashes?", response: "Fezolinetant, a neurokinin 3 receptor antagonist, significantly reduces both the frequency and severity of hot flashes. It is a nonhormonal option approved for moderate to severe vasomotor symptoms. Liver function monitoring is now recommended due to rare cases of hepatotoxicity." },
  { id: 2119, category: 'hot flashes', keywords: ['hot flashes breast cancer survivors safe treatment'], question: "How are hot flashes managed in women with breast cancer?", response: "Hormone therapy is generally avoided. Nonhormonal options such as SSRIs/SNRIs (avoiding strong CYP2D6 inhibitors like paroxetine in women on tamoxifen), gabapentin, or fezolinetant/elinzanetant are preferred. Neurokinin antagonists are particularly useful in this population." },

  // === GSM IDs 2153–2161 ===
  { id: 2153, category: 'menopause', keywords: ['what is GSM genitourinary syndrome of menopause definition'], question: "What is genitourinary syndrome of menopause (GSM)?", response: "GSM is a collection of symptoms caused by low estrogen levels affecting the vulva, vagina, urethra, and bladder. It includes vaginal dryness, burning, irritation, painful sex, urinary urgency, and recurrent UTIs. It used to be called vaginal atrophy or atrophic vaginitis." },
  { id: 2154, category: 'menopause', keywords: ['symptoms of GSM vaginal dryness painful sex burning'], question: "What are the most common symptoms of GSM?", response: "Common symptoms include vaginal dryness, decreased lubrication during sex, pain with intercourse, vulvar burning or irritation, urinary urgency or burning, and more frequent urinary tract infections. Some people also notice vaginal itching or light bleeding after sex." },
  { id: 2155, category: 'menopause', keywords: ['first-line treatment GSM moisturizer lubricant vaginal estrogen'], question: "What is first-line treatment for genitourinary syndrome of menopause?", response: "Nonhormonal vaginal moisturizers (used 2–3 times per week) and lubricants (used during sexual activity) are first-line therapy for most patients with GSM. Low-dose vaginal estrogen is the most effective treatment for moderate-to-severe symptoms that do not respond to moisturizers and lubricants." },
  { id: 2156, category: 'menopause', keywords: ['vaginal DHEA prasterone for GSM dyspareunia'], question: "What is the role of vaginal DHEA (prasterone) in GSM?", response: "Vaginal DHEA (6.5 mg daily suppository) is FDA-approved for dyspareunia due to GSM. It improves vaginal maturation, dryness, and pain. It is a reasonable option for patients who prefer to avoid estrogen, though daily dosing is less convenient than twice-weekly estrogen." },
  { id: 2157, category: 'menopause', keywords: ['ospemifene for GSM dyspareunia oral SERM'], question: "When should ospemifene be used for GSM?", response: "Ospemifene (60 mg oral daily) is a SERM approved for moderate-to-severe dyspareunia and vaginal dryness due to GSM. It is a good option for patients who cannot or prefer not to use vaginal products. Main side effects are hot flashes and a potential risk of VTE." },

  // === Abnormal uterine bleeding evaluation IDs 2162–2170 ===
  { id: 2162, category: 'abnormal uterine bleeding', keywords: ['AUB patterns definition FIGO PALM-COEIN'], question: "What are the main patterns of abnormal uterine bleeding?", response: "AUB includes bleeding that is too frequent (<24 days), infrequent (>38 days), irregular (cycle variance >7–9 days depending on age), prolonged (>8 days), heavy (interferes with quality of life), or occurs between periods (intermenstrual). Heavy menstrual bleeding is defined by its impact on the patient's life, not just volume." },
  { id: 2163, category: 'abnormal uterine bleeding', keywords: ['when to evaluate abnormal uterine bleeding criteria'], question: "When should abnormal uterine bleeding be evaluated?", response: "Any single episode of postmenopausal bleeding needs evaluation. In reproductive-age patients, evaluate persistent or bothersome bleeding, heavy bleeding causing anemia or quality-of-life issues, intermenstrual bleeding, or bleeding with risk factors for endometrial cancer. A single isolated event in otherwise normal cycles may only need a menstrual diary." },
  { id: 2164, category: 'abnormal uterine bleeding', keywords: ['pregnancy test in abnormal bleeding always do'], question: "Should I always do a pregnancy test in patients with abnormal uterine bleeding?", response: "Yes. Pregnancy should be excluded in all reproductive-age patients with AUB, even if they report recent bleeding, no sexual activity, or contraceptive use. A urine hCG is a good start; use serum hCG if early pregnancy is still suspected despite a negative urine test." },
  { id: 2165, category: 'abnormal uterine bleeding', keywords: ['heavy menstrual bleeding workup CBC ferritin TSH'], question: "What is the initial workup for heavy menstrual bleeding?", response: "Start with history, physical exam, pregnancy test, and CBC (to check for anemia). Consider ferritin, TSH, and bleeding disorder evaluation if indicated. Pelvic ultrasound is usually the first imaging test to look for fibroids, adenomyosis, or polyps. Endometrial sampling is added for patients with risk factors for hyperplasia or cancer." },
  { id: 2166, category: 'abnormal uterine bleeding', keywords: ['endometrial sampling indications age obesity risk factors'], question: "When should I do endometrial sampling for abnormal uterine bleeding?", response: "For patients age 45 to menopause: sample for frequent, heavy, prolonged, or intermenstrual bleeding. For patients under 45: sample if bleeding persists ≥6 months plus obesity, chronic anovulation, failed medical therapy, or high-risk features (tamoxifen, Lynch syndrome)." },

  // === Female sexual dysfunction IDs 2184–2193 ===
  { id: 2184, category: 'sexual health', keywords: ['how common is female sexual dysfunction prevalence'], question: "How common is female sexual dysfunction?", response: "Approximately 40% of females worldwide report sexual problems, but only about 12% have a sexual problem associated with personal or interpersonal distress (meeting criteria for sexual dysfunction). Low desire is the most common concern, followed by arousal and orgasm difficulties." },
  { id: 2185, category: 'sexual health', keywords: ['key risk factors for female sexual dysfunction GSM SSRI menopause'], question: "What are the major risk factors for female sexual dysfunction?", response: "Key risk factors include relationship difficulties, history of sexual or physical abuse, depression/anxiety, fatigue and stress, genitourinary syndrome of menopause, pelvic floor disorders, certain medications (especially SSRIs), and medical conditions that affect energy, body image, or pelvic health." },
  { id: 2186, category: 'sexual health', keywords: ['how to treat low libido menopause vaginal estrogen therapy'], question: "What helps improve low libido and sexual satisfaction during menopause?", response: "Many women notice changes in desire and arousal around menopause due to lower estrogen, vaginal dryness, sleep disruption, and hot flashes. Treating vaginal dryness with moisturizers and low-dose vaginal estrogen often helps. Reducing stress, improving sleep, and addressing relationship issues are also very effective." },
  { id: 2187, category: 'sexual health', keywords: ['SSRIs and sexual dysfunction in women antidepressants'], question: "Do SSRIs cause sexual problems and what can be done?", response: "SSRIs (and some other antidepressants) commonly reduce desire, arousal, and ability to orgasm. Options include lowering the dose, switching to bupropion or another medication with fewer sexual side effects, or adding a medication to counteract the problem. Never stop or change antidepressants without talking to your prescriber." },
  { id: 2188, category: 'sexual health', keywords: ['pelvic floor physical therapy dyspareunia sexual pain'], question: "How does pelvic floor physical therapy help with sexual pain?", response: "Pelvic floor PT is very effective for dyspareunia caused by muscle tension, levator spasm, or vaginismus. Therapists use manual techniques, biofeedback, dilators, and exercises to reduce pain, improve muscle relaxation, and restore comfortable penetration. It is often combined with other treatments." },
  { id: 2189, category: 'sexual health', keywords: ['testosterone for low libido postmenopausal women'], question: "Is testosterone helpful for low libido in women?", response: "Testosterone can provide a small improvement in desire for some postmenopausal women with distressing low libido and no other clear cause. However, no testosterone product is FDA-approved for this use in women, benefits are modest, and side effects can occur. Long-term safety is not well established." },

  // === PMDD diagnosis IDs 2194–2202 ===
  { id: 2194, category: 'PMDD', keywords: ['difference between PMS and PMDD severity criteria'], question: "What is the difference between PMS and PMDD?", response: "PMS involves one or more physical or behavioral symptoms that cause some impairment and occur in the luteal phase. PMDD is more severe and requires at least 5 symptoms (one of which must be affective, such as irritability, mood swings, anxiety, or hopelessness) that cause significant distress or functional impairment. PMDD is diagnosed using DSM-5 criteria." },
  { id: 2195, category: 'PMDD', keywords: ['most common symptoms of PMDD irritability anger mood'], question: "What are the most common symptoms of PMDD?", response: "The hallmark symptoms of PMDD are affective: irritability/anger, mood swings, anxiety/tension, and depressed mood or hopelessness. Common physical symptoms include bloating, breast tenderness, fatigue, and headaches. Irritability is often the most prominent and distressing symptom." },
  { id: 2196, category: 'PMDD', keywords: ['timing PMS PMDD symptoms luteal phase follicular'], question: "When do PMS and PMDD symptoms typically occur?", response: "Symptoms begin in the late luteal phase (usually the 4–5 days before menses) and resolve within a few days after menses starts. There should be a clear symptom-free interval in the follicular phase. Symptoms lasting throughout the entire cycle suggest another diagnosis." },
  { id: 2197, category: 'PMDD', keywords: ['how to diagnose PMDD prospective tracking DRSP'], question: "How is PMDD diagnosed?", response: "Diagnosis requires prospective daily symptom tracking for at least two cycles using a validated tool (such as the Daily Record of Severity of Problems – DRSP). At least 5 symptoms must be present in the late luteal phase (one affective), cause significant distress or impairment, and resolve after menses. Other medical and psychiatric conditions must be ruled out." },
  { id: 2198, category: 'PMDD', keywords: ['PMDD vs premenstrual exacerbation of depression differentiation'], question: "How do you distinguish PMDD from premenstrual exacerbation of a mood disorder?", response: "In PMDD, symptoms are absent or minimal during the follicular phase. In premenstrual exacerbation of depression or anxiety, symptoms are present throughout the cycle but worsen before menses. Prospective charting is essential to make this distinction." },
  { id: 2199, category: 'PMDD', keywords: ['suicidality in PMDD suicide risk elevated'], question: "Is there increased suicide risk in PMDD?", response: "Yes. Individuals with PMDD, especially those with more severe symptoms, have an elevated risk of suicidal ideation and attempts. Clinicians should screen for suicidal thoughts and refer promptly to mental health support when indicated." },

  // === Heavy periods IDs 2231–2238 ===
  { id: 2231, category: 'heavy bleeding', keywords: ['what counts as a heavy period menorrhagia'], question: "How much bleeding is considered a heavy period?", response: "Heavy periods (menorrhagia) are defined as bleeding that affects your physical health, emotional health, or quality of life. Common signs include soaking through a pad or tampon every 1–3 hours on your heaviest days, bleeding for more than 7 days, passing large clots, or needing to change protection at night." },
  { id: 2232, category: 'heavy bleeding', keywords: ['causes of heavy periods fibroids polyps anovulation'], question: "What are the most common causes of heavy periods?", response: "The most common causes include not ovulating regularly (anovulation), uterine growths such as polyps, fibroids, or adenomyosis, bleeding disorders (like von Willebrand disease), and certain medications or the copper IUD. Anovulation is especially common in teenagers and in perimenopause." },
  { id: 2233, category: 'heavy bleeding', keywords: ['when to go to ER for very heavy bleeding soaking'], question: "When should I get help for very heavy bleeding?", response: "Go to the emergency department or call your provider if you soak through two pads or tampons in one hour for two hours in a row. This level of bleeding can be serious. You should also seek care if you feel very weak, dizzy, or short of breath, as these can be signs of significant blood loss or anemia." },
  { id: 2234, category: 'heavy bleeding', keywords: ['hormonal IUD LNG Mirena heavy periods effective'], question: "How well does the hormonal IUD work for heavy periods?", response: "The levonorgestrel IUD (Mirena or Liletta) is one of the most effective medical treatments for heavy bleeding. It can significantly reduce or even stop periods for many users. It also provides contraception for up to 8 years. Irregular spotting is common in the first few months but usually improves over time." },
  { id: 2235, category: 'heavy bleeding', keywords: ['tranexamic acid Lysteda heavy periods non-hormonal'], question: "What is tranexamic acid and how does it help heavy periods?", response: "Tranexamic acid (Lysteda) is a non-hormonal medication that helps blood clot and can quickly reduce heavy menstrual bleeding. You only take it for a few days each month during your period. It does not affect your ability to get pregnant and can be combined with other treatments." },
  { id: 2236, category: 'heavy bleeding', keywords: ['endometrial ablation heavy periods outpatient treatment'], question: "What is endometrial ablation and is it a good option for heavy periods?", response: "Endometrial ablation destroys or removes most of the uterine lining to reduce or stop heavy bleeding. It is done as an outpatient procedure and has a relatively quick recovery. It is not recommended if you might want to become pregnant in the future, and it works best when heavy bleeding is not caused by anovulation or large fibroids." },

  // === PMS/PMDD treatment IDs 2239–2247 ===
  { id: 2239, category: 'PMDD', keywords: ['first line treatment for PMDD SSRIs sertraline fluoxetine'], question: "What is the best first-line treatment for PMDD?", response: "Selective serotonin reuptake inhibitors (SSRIs) such as fluoxetine, sertraline, or escitalopram are the most effective treatments. They work for 60–75% of women with PMDD. They can be taken daily or only during the luteal phase (second half of the cycle). It usually takes 1–2 cycles to see full benefit." },
  { id: 2240, category: 'PMDD', keywords: ['GnRH agonists for severe PMDD when to use'], question: "When are GnRH agonists used for PMDD?", response: "GnRH agonists (with estrogen + progestin add-back) are reserved for severe PMDD that does not respond to SSRIs or birth control pills. They temporarily shut down ovarian hormone production and can be very effective, but they cause menopausal symptoms and require add-back hormones to protect bone health." },
  { id: 2241, category: 'PMDD', keywords: ['PMDD vs depression how to tell apart cycle tracking'], question: "How do you tell PMDD apart from depression?", response: "In true PMDD, symptoms are absent or minimal in the first half of the cycle (roughly days 4–12) and appear only in the luteal phase. In depression or anxiety disorders, symptoms are usually present throughout the month, though they may worsen before menses. Prospective daily tracking helps make this distinction." },

  // === Secondary amenorrhea IDs 2395–2403 ===
  { id: 2395, category: 'amenorrhea', keywords: ['secondary amenorrhea definition absent periods evaluation'], question: "How is secondary amenorrhea defined?", response: "Secondary amenorrhea is the absence of menses for more than 3 months in women who previously had regular cycles, or 6 months in those with irregular cycles. Oligomenorrhea (cycles >35 days or <9 menses/year) is evaluated similarly. Pregnancy must always be ruled out first." },
  { id: 2396, category: 'amenorrhea', keywords: ['initial lab workup secondary amenorrhea FSH prolactin TSH'], question: "What is the initial laboratory evaluation for secondary amenorrhea?", response: "After ruling out pregnancy, initial labs include serum FSH, prolactin, TSH, and estradiol. These help evaluate for primary ovarian insufficiency, hyperprolactinemia, thyroid disease, and estrogen status. If hyperandrogenism is present, add total testosterone ± 17-hydroxyprogesterone." },
  { id: 2397, category: 'amenorrhea', keywords: ['PCOS evaluation amenorrhea irregular periods'], question: "How is PCOS evaluated in women with amenorrhea?", response: "PCOS is a common cause of secondary amenorrhea with hyperandrogenism. Diagnosis requires clinical/biochemical hyperandrogenism plus ovulatory dysfunction (after ruling out other causes). Measure testosterone; consider 17-hydroxyprogesterone to exclude nonclassic CAH. Ultrasound may show polycystic ovarian morphology." },
  { id: 2398, category: 'amenorrhea', keywords: ['functional hypothalamic amenorrhea FHA causes low FSH'], question: "What causes functional hypothalamic amenorrhea?", response: "Functional hypothalamic amenorrhea occurs when the body's energy supply is insufficient (from excessive exercise, stress, eating disorders, or low calorie intake). This suppresses GnRH pulsatility, lowering FSH, LH, and estradiol. It is a diagnosis of exclusion after ruling out pregnancy, PCOS, hyperprolactinemia, and thyroid disease." },
  { id: 2399, category: 'amenorrhea', keywords: ['primary ovarian insufficiency POI irregular periods elevated FSH'], question: "When should primary ovarian insufficiency be considered with irregular periods?", response: "Primary ovarian insufficiency (POI) should be considered in women under 40 with irregular or absent periods, especially with hot flashes or night sweats. It is diagnosed by elevated FSH on two occasions. Early menopause (ages 40–45) is also possible. Both require evaluation for underlying causes and hormone replacement considerations." },

  // === POI pathogenesis IDs 2443–2451 ===
  { id: 2443, category: 'POI', keywords: ['primary ovarian insufficiency POI definition diagnosis elevated FSH'], question: "How is primary ovarian insufficiency (POI) defined?", response: "POI (formerly premature ovarian failure) is primary hypogonadism in a woman under age 40, characterized by loss of oocytes, lack of folliculogenesis, ovarian estrogen production, and infertility. It is diagnosed by elevated FSH with low or undetectable estradiol. More than 50% of women show some evidence of intermittent or partial ovarian activity over time." },
  { id: 2444, category: 'POI', keywords: ['FMR1 premutation fragile X and POI risk'], question: "What is the relationship between FMR1 premutation and POI?", response: "Women who carry an FMR1 premutation (55–200 CGG repeats) have a 12–28% risk of POI. The prevalence of FMR1 premutations is 2–5% in sporadic POI and 12–16% in familial POI. ACOG recommends screening all women with POI or elevated FSH before age 40 for FMR1 premutations." },
  { id: 2445, category: 'POI', keywords: ['chemotherapy radiation and POI fertility preservation'], question: "How do chemotherapy and radiation cause POI?", response: "Chemotherapeutic agents (especially alkylators) and pelvic/abdominal radiation are the most common iatrogenic causes of POI. Risk depends on age, dose, and specific agents. Even sub-sterilizing doses can accelerate ovarian aging. Fertility preservation should be discussed before gonadotoxic therapy." },

  // === Painful sex dyspareunia IDs 2511–2519 ===
  { id: 2511, category: 'sexual health', keywords: ['painful sex dyspareunia causes definition'], question: "What is painful sex (dyspareunia)?", response: "Painful sex (dyspareunia) is pain or discomfort that occurs just before, during, or after sexual activity. In females, pain can be at the vulva (superficial), inside the vagina, or deep in the pelvis/lower abdomen. It is more common in females than males and has many treatable causes." },
  { id: 2512, category: 'sexual health', keywords: ['common causes of painful sex women GSM vulvodynia'], question: "What are common causes of painful sex in women?", response: "Common causes include genitourinary syndrome of menopause (vaginal dryness and thinning), endometriosis, postpartum changes, vulvodynia, bladder pain syndrome, chronic pelvic pain, vaginal or bladder infections, skin conditions, insufficient arousal/lubrication, past trauma or painful experiences, relationship issues, and sometimes hormonal birth control." },
  { id: 2513, category: 'sexual health', keywords: ['when to see a doctor for painful sex evaluation'], question: "When should someone see a doctor for painful sex?", response: "Anyone experiencing pain with sex should see a clinician. Evaluation includes a history, pelvic exam, and possible urine or vaginal testing for infection. Red flags include new or worsening pain, bleeding, discharge, or pain associated with other symptoms." },
  { id: 2514, category: 'sexual health', keywords: ['treatment of painful sex in women GSM PT lubricants'], question: "How is painful sex treated in women?", response: "Treatment is cause-specific and may include: treating infections, vaginal moisturizers/lubricants or low-dose vaginal estrogen for GSM, pelvic floor physical therapy for muscle tension or vulvodynia, counseling for relationship or trauma-related issues, numbing agents, or (rarely) surgery. A multimodal approach is often most effective." },

  // === Insomnia management IDs 2320–2328 ===
  { id: 2320, category: 'sleep', keywords: ['CBT-I first line chronic insomnia treatment'], question: "What is the first-line treatment for chronic insomnia?", response: "Cognitive behavioral therapy for insomnia (CBT-I) is first-line treatment for chronic insomnia disorder. It is as effective as medication in the short term and superior for long-term outcomes. CBT-I addresses maladaptive thoughts and behaviors and gives patients lifelong skills. Medication is an acceptable initial alternative when CBT-I is not accessible or when rapid relief is clinically needed." },
  { id: 2321, category: 'sleep', keywords: ['insomnia in menopause management vasomotor symptoms'], question: "How should insomnia be managed during the menopausal transition?", response: "Insomnia is common in perimenopause and menopause due to vasomotor symptoms, hormonal fluctuations, increased OSA risk, and mood changes. CBT-I is effective whether or not hot flashes are present. When hot flashes are prominent, menopausal hormone therapy, venlafaxine, gabapentin, or suvorexant may improve both sleep and vasomotor symptoms." },
  { id: 2322, category: 'sleep', keywords: ['insomnia in pregnancy nonpharmacologic management'], question: "How should insomnia be managed during pregnancy?", response: "Nonpharmacologic approaches, especially CBT-I (in-person or digital), are preferred. Sleep disturbance increases across trimesters. Screen for restless legs syndrome and address it with iron if indicated. Over-the-counter antihistamines (doxylamine, diphenhydramine) can be considered when medication is needed. Most prescription insomnia medications are generally avoided due to limited safety data." },
  { id: 2323, category: 'sleep', keywords: ['key perpetuating factors chronic insomnia sleep hygiene'], question: "What are common perpetuating factors in chronic insomnia?", response: "Common perpetuating factors include irregular sleep schedules, excessive time in bed, napping, clock-watching, high anxiety about sleep ('insomnia phobia'), unrealistic sleep expectations, and poor sleep hygiene. These are the primary targets of CBT-I. Addressing them is essential even when medications are used." },

  // === Premenopausal osteoporosis IDs 2175–2183 ===
  { id: 2175, category: 'bone health', keywords: ['premenopausal osteoporosis definition fragility fracture Z-score'], question: "How is osteoporosis defined in premenopausal women?", response: "In premenopausal women, osteoporosis is diagnosed by a history of fragility (low-trauma) fracture(s), especially at major sites like the spine or hip, or by low BMD (Z-score ≤-2.0 or T-score ≤-2.5) plus a known secondary cause of bone loss. Low BMD alone is not sufficient to diagnose osteoporosis in this population." },
  { id: 2176, category: 'bone health', keywords: ['secondary causes premenopausal osteoporosis eating disorder glucocorticoids'], question: "What are common secondary causes of low bone mass or fracture in premenopausal women?", response: "Common causes include estrogen deficiency (from eating disorders, RED-S, hyperprolactinemia, premature ovarian insufficiency), glucocorticoid use, inflammatory bowel disease, celiac disease, hyperparathyroidism, hypercalciuria, smoking, and certain medications. A thorough evaluation for secondary causes is essential in all premenopausal women with low BMD or fractures." },
  { id: 2177, category: 'bone health', keywords: ['pregnancy lactation associated osteoporosis PLO fracture'], question: "What is pregnancy and lactation-associated osteoporosis (PLO)?", response: "PLO is a rare presentation of early-onset osteoporosis in which women develop painful fractures (often vertebral) in the third trimester or early postpartum period. Many cases are considered idiopathic, though some women have identifiable risk factors or genetic variants. Bone loss during lactation is physiologic but can unmask underlying fragility in susceptible women." },
  { id: 2178, category: 'bone health', keywords: ['postmenopausal osteoporosis first line treatment bisphosphonates'], question: "What is first-line pharmacologic therapy for most postmenopausal women with osteoporosis?", response: "Oral bisphosphonates (alendronate or risedronate) are first-line for most women due to proven fracture reduction, cost, and long-term safety data. They are contraindicated in women with esophageal disorders, inability to remain upright, or eGFR <30–35 mL/min." },
  { id: 2179, category: 'bone health', keywords: ['anabolic therapy very high fracture risk teriparatide romosozumab'], question: "When should anabolic therapy be used first for osteoporosis?", response: "Anabolic agents (teriparatide, abaloparatide, or romosozumab) are preferred as initial therapy in women with very high fracture risk, such as T-score ≤-3.0, T-score ≤-2.5 plus fragility fracture, or multiple/severe fractures. These agents build bone more effectively than antiresorptives in the highest-risk patients." },
  { id: 2180, category: 'bone health', keywords: ['calcium vitamin D postmenopausal osteoporosis lifestyle'], question: "What lifestyle measures are recommended for all postmenopausal women?", response: "All women should ensure adequate calcium (≈1200 mg/day total) and vitamin D (800 IU/day), engage in regular weight-bearing and muscle-strengthening exercise, stop smoking, limit alcohol, and take fall-prevention measures. These are foundational for everyone, regardless of pharmacotherapy." },

];